### ISSUE TITLE
Hive + databricks ingestion

### ISSUE THREAD

**Issue by albepelle** [datahub-project/datahub#10111]
succesfully deployed datahub on docker via quickstart guide, managed to ingest multiple data sources.
Attempted to ingest the hive_metastore on databricks following the recipe as per official documentation.

attempted ingestion via user interface gives the following error log: 

~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': 'ab520d1f-10b1-4432-bb3f-df3ac1b2ba9c',
 'infos': ['2024-03-22 12:15:40.380167 INFO: Starting execution for task with name=RUN_INGEST',
           "2024-03-22 12:15:46.476249 INFO: Failed to execute 'datahub ingest', exit code 1",
           '2024-03-22 12:15:46.476440 INFO: Caught exception EXECUTING task_id=ab520d1f-10b1-4432-bb3f-df3ac1b2ba9c, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 140, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 282, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Report ~~~~
{
  "cli": {
    "cli_version": "0.13.0",
    "cli_entry_location": "/tmp/datahub/ingest/venv-hive-79357ad588bf7a10/lib/python3.10/site-packages/datahub/__init__.py",
    "py_version": "3.10.13 (main, Jan 17 2024, 06:53:56) [GCC 12.2.0]",
    "py_exec_path": "/tmp/datahub/ingest/venv-hive-79357ad588bf7a10/bin/python3",
    "os_details": "Linux-5.15.146.1-microsoft-standard-WSL2-x86_64-with-glibc2.36",
    "mem_info": "93.61 MB",
    "peak_memory_usage": "93.61 MB",
    "disk_info": {
      "total": "1.08 TB",
      "used": "20.03 GB",
      "used_initally": "20.03 GB",
      "free": "1.01 TB"
    },
    "peak_disk_usage": "20.03 GB",
    "thread_count": 1,
    "peak_thread_count": 1
  },
  "source": {
    "type": "hive",
    "report": {
      "events_produced": 0,
      "events_produced_per_sec": 0,
      "entities": {},
      "aspects": {},
      "warnings": {},
      "failures": {},
      "soft_deleted_stale_entities": [],
      "tables_scanned": 0,
      "views_scanned": 0,
      "entities_profiled": 0,
      "filtered": [],
      "num_view_definitions_parsed": 0,
      "num_view_definitions_failed_parsing": 0,
      "num_view_definitions_failed_column_parsing": 0,
      "view_definitions_parsing_failures": [],
      "start_time": "2024-03-22 12:15:43.143248 (1.02 seconds ago)",
      "running_time": "1.02 seconds"
    }
  },
  "sink": {
    "type": "datahub-rest",
    "report": {
      "total_records_written": 0,
      "records_written_per_second": 0,
      "warnings": [],
      "failures": [],
      "start_time": "2024-03-22 12:15:42.818081 (1.34 seconds ago)",
      "current_time": "2024-03-22 12:15:44.162189 (now)",
      "total_duration_in_seconds": 1.34,
      "max_threads": 15,
      "gms_version": "v0.13.0",
      "pending_requests": 0
    }
  }
}

~~~~ Ingestion Logs ~~~~
Obtaining venv creation lock...
Acquired venv creation lock
venv is already set up
venv setup time = 0 sec
This version of datahub supports report-to functionality
+ exec datahub ingest run -c /tmp/datahub/ingest/ab520d1f-10b1-4432-bb3f-df3ac1b2ba9c/recipe.yml --report-to /tmp/datahub/ingest/ab520d1f-10b1-4432-bb3f-df3ac1b2ba9c/ingestion_report.json
[2024-03-22 12:15:42,793] INFO     {datahub.cli.ingest_cli:147} - DataHub CLI version: 0.13.0
[2024-03-22 12:15:42,821] INFO     {datahub.ingestion.run.pipeline:238} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms:8080
[2024-03-22 12:15:43,731] INFO     {datahub.ingestion.run.pipeline:255} - Source configured successfully.
[2024-03-22 12:15:43,732] INFO     {datahub.cli.ingest_cli:128} - Starting metadata ingestion
[2024-03-22 12:15:44,162] INFO     {datahub.ingestion.reporting.file_reporter:52} - Wrote UNKNOWN report successfully to <_io.TextIOWrapper name='/tmp/datahub/ingest/ab520d1f-10b1-4432-bb3f-df3ac1b2ba9c/ingestion_report.json' mode='w' encoding='UTF-8'>
[2024-03-22 12:15:44,163] INFO     {datahub.cli.ingest_cli:133} - Source (hive) report:
{'events_produced': 0,
 'events_produced_per_sec': 0,
 'entities': {},
 'aspects': {},
 'warnings': {},
 'failures': {},
 'soft_deleted_stale_entities': [],
 'tables_scanned': 0,
 'views_scanned': 0,
 'entities_profiled': 0,
 'filtered': [],
 'num_view_definitions_parsed': 0,
 'num_view_definitions_failed_parsing': 0,
 'num_view_definitions_failed_column_parsing': 0,
 'view_definitions_parsing_failures': [],
 'start_time': '2024-03-22 12:15:43.143248 (1.02 seconds ago)',
 'running_time': '1.02 seconds'}
[2024-03-22 12:15:44,163] INFO     {datahub.cli.ingest_cli:136} - Sink (datahub-rest) report:
{'total_records_written': 0,
 'records_written_per_second': 0,
 'warnings': [],
 'failures': [],
 'start_time': '2024-03-22 12:15:42.818081 (1.35 seconds ago)',
 'current_time': '2024-03-22 12:15:44.163248 (now)',
 'total_duration_in_seconds': 1.35,
 'max_threads': 15,
 'gms_version': 'v0.13.0',
 'pending_requests': 0}

below the recipe template used 

source:
    type: hive
    config:
        host_port: '<databricks workspace URL>:443'
        username: token
        password: API token
        scheme: databricks+pyhive
        options:
            connect_args:
                http_path: 
        stateful_ingestion:
            enabled: false
        profiling:
            enabled: false
            profile_table_level_only: true
`

**Comment by albepelle** [comment]
figured it out, turns out they gave me the warehouse URL rather than the cluster.
It won't give you a clear error in this case just a failed execution so might be hard to troubleshoot.
