### ISSUE TITLE
[spark-lineage-beta] openlineage is too old to support spark 3.3

### ISSUE THREAD

**Issue by lordk911** [datahub-project/datahub#10306]
The current dependent openlineage version is 1.5 ，The latest release is 1.12 ，Is there any plan to upgrade openlineage？

**Comment by lordk911** [comment]
I tested spark 3.3.3 based on the acril-spark-Lineage 0.0.2. jar downloaded from mvnrepository ，will got error: 

```
spark.sql("use test").show 
24/04/17 10:55:56 WARN SQLConf: The SQL config 'spark.sql.adaptive.coalescePartitions.minPartitionNum' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.adaptive.coalescePartitions.minPartitionSize' instead.
24/04/17 10:55:56 WARN SQLConf: The SQL config 'spark.sql.adaptive.coalescePartitions.minPartitionNum' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.adaptive.coalescePartitions.minPartitionSize' instead.
24/04/17 10:55:56 WARN SQLConf: The SQL config 'spark.sql.adaptive.coalescePartitions.minPartitionNum' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.adaptive.coalescePartitions.minPartitionSize' instead.
ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.9.3 used for parser compilation does not match the current runtime version 4.8ANTLR Tool version 4.9.3 used for code generation does not match the current runtime version 4.8ANTLR Runtime version 4.9.3 used for parser compilation does not match the current runtime version 4.824/04/17 10:55:59 DEBUG DatahubSparkListener: Other event called org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionStart
24/04/17 10:55:59 WARN SQLConf: The SQL config 'spark.sql.adaptive.coalescePartitions.minPartitionNum' has been deprecated in Spark v3.2 and may be removed in the future. Use 'spark.sql.adaptive.coalescePartitions.minPartitionSize' instead.
24/04/17 10:56:00 INFO HiveConf: Found configuration file file:/data/soft/spark3/conf/hive-site.xml
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.materializedview.rewriting.incremental does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.metastore.event.db.notification.api.auth does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.server2.webui.cors.allowed.headers does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.hook.proto.base-directory does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.load.data.owner does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.service.metrics.codahale.reporter.classes does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.strict.managed.tables does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.create.as.insert.only does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.metastore.db.type does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.tez.cartesian-product.enabled does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.metastore.warehouse.external.dir does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.heapsize does not exist
24/04/17 10:56:00 WARN HiveConf: HiveConf of name hive.server2.webui.enable.cors does not exist
24/04/17 10:56:00 WARN HiveClientImpl: Detected HiveConf hive.execution.engine is 'tez' and will be reset to 'mr' to disable useless hive logic
24/04/17 10:56:00 INFO metastore: Trying to connect to metastore with URI thrift://hdpdev248.glodondg.com:9083
24/04/17 10:56:00 WARN metastore: Failed to connect to the MetaStore Server...
24/04/17 10:56:00 INFO metastore: Trying to connect to metastore with URI thrift://hdpdev246.glodondg.com:9083
24/04/17 10:56:00 INFO metastore: Opened a connection to metastore, current connections: 1
24/04/17 10:56:00 INFO metastore: Connected to metastore.
24/04/17 10:56:00 DEBUG DatahubSparkListener: Other event called org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionEnd
24/04/17 10:56:01 DEBUG DatahubSparkListener: Other event called org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionStart
++
||
++
++


scala> 24/04/17 10:56:01 WARN LogicalPlanSerializer: Unable to writeValueAsString
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.acryl.shaded.org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:170)
        at io.acryl.shaded.org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:131)
        at io.acryl.shaded.org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:95)
        at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.writeValueAsString(LogicalPlanSerializer.java:105)
        at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.serialize(LogicalPlanSerializer.java:128)
        at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.mapEntry(UnknownEntryFacetListener.java:77)
        at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.build(UnknownEntryFacetListener.java:58)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$populateRun$3(OpenLineageRunEventBuilder.java:309)
        at java.util.Optional.flatMap(Optional.java:241)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:309)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:288)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:231)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:87)
        at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecStart$0(OpenLineageSparkListener.java:91)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecStart(OpenLineageSparkListener.java:91)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:82)
        at datahub.spark.DatahubSparkListener.onOtherEvent(DatahubSparkListener.java:203)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: org.apache.spark.sql.catalyst.plans.logical.GlobalLimit["limitExpr"]->org.apache.spark.sql.catalyst.expressions.Literal["canonicalized"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:944)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:722)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
        ... 36 more
24/04/17 10:56:01 DEBUG DatahubEventEmitter: Emitting lineage: {"eventTime":"2024-04-17T02:56:01.059Z","producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunEvent","eventType":"START","run":{"runId":"98aa87af-19ba-4141-aed6-3c0641d39104","facets":{"processing_engine":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-1-0/ProcessingEngineRunFacet.json#/$defs/ProcessingEngineRunFacet","version":"3.3.3","name":"spark"},"environment-properties":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","environment-properties":{}},"spark_version":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","spark-version":"3.3.3"},"spark.logicalPlan":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","plan":[{"class":"org.apache.spark.sql.catalyst.plans.logical.GlobalLimit","num-children":1,"limitExpr":[{"class":"org.apache.spark.sql.catalyst.expressions.Literal","num-children":0,"value":"21","dataType":"integer"}],"child":0},{"class":"org.apache.spark.sql.catalyst.plans.logical.LocalLimit","num-children":1,"limitExpr":[{"class":"org.apache.spark.sql.catalyst.expressions.Literal","num-children":0,"value":"21","dataType":"integer"}],"child":0},{"class":"org.apache.spark.sql.catalyst.plans.logical.CommandResult","num-children":0,"output":[],"commandLogicalPlan":[{"class":"org.apache.spark.sql.catalyst.plans.logical.SetCatalogAndNamespace","num-children":1,"child":0},{"class":"org.apache.spark.sql.catalyst.analysis.ResolvedDBObjectName","num-children":0,"nameParts":"[test]"}],"commandPhysicalPlan":[{"class":"org.apache.spark.sql.execution.datasources.v2.SetCatalogAndNamespaceExec","num-children":0,"catalogName":"spark_catalog","namespace":"[test]"}],"rows":[]}]}}},"job":{"namespace":"default","name":"spark_shell.collect_limit","facets":{}},"inputs":[],"outputs":[]}
24/04/17 10:56:01 ERROR AsyncEventQueue: Listener DatahubSparkListener threw an exception
java.lang.NullPointerException
        at datahub.spark.DatahubEventEmitter.convertOpenLineageRunEventToDatahubJob(DatahubEventEmitter.java:88)
        at datahub.spark.DatahubEventEmitter.emit(DatahubEventEmitter.java:108)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.start(SparkSQLExecutionContext.java:97)
        at io.openlineage.spark.agent.OpenLineageSparkListener.lambda$sparkSQLExecStart$0(OpenLineageSparkListener.java:91)
        at java.util.Optional.ifPresent(Optional.java:159)
        at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecStart(OpenLineageSparkListener.java:91)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:82)
        at datahub.spark.DatahubSparkListener.onOtherEvent(DatahubSparkListener.java:203)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
24/04/17 10:56:01 DEBUG DatahubSparkListener: Other event called org.apache.spark.sql.execution.ui.SparkListenerSQLExecutionEnd
24/04/17 10:56:01 WARN LogicalPlanSerializer: Unable to writeValueAsString
java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at io.acryl.shaded.org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:170)
        at io.acryl.shaded.org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:131)
        at io.acryl.shaded.org.apache.commons.lang.reflect.MethodUtils.invokeMethod(MethodUtils.java:95)
        at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.writeValueAsString(LogicalPlanSerializer.java:105)
        at io.openlineage.spark.agent.lifecycle.LogicalPlanSerializer.serialize(LogicalPlanSerializer.java:128)
        at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.mapEntry(UnknownEntryFacetListener.java:77)
        at io.openlineage.spark.agent.lifecycle.UnknownEntryFacetListener.build(UnknownEntryFacetListener.java:58)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.lambda$populateRun$3(OpenLineageRunEventBuilder.java:309)
        at java.util.Optional.flatMap(Optional.java:241)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.populateRun(OpenLineageRunEventBuilder.java:309)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:288)
        at io.openlineage.spark.agent.lifecycle.OpenLineageRunEventBuilder.buildRun(OpenLineageRunEventBuilder.java:240)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:126)
        at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:98)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:84)
        at datahub.spark.DatahubSparkListener.onOtherEvent(DatahubSparkListener.java:203)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
Caused by: com.fasterxml.jackson.databind.exc.InvalidDefinitionException: Direct self-reference leading to cycle (through reference chain: org.apache.spark.sql.catalyst.plans.logical.GlobalLimit["limitExpr"]->org.apache.spark.sql.catalyst.expressions.Literal["canonicalized"])
        at com.fasterxml.jackson.databind.exc.InvalidDefinitionException.from(InvalidDefinitionException.java:77)
        at com.fasterxml.jackson.databind.SerializerProvider.reportBadDefinition(SerializerProvider.java:1300)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter._handleSelfReference(BeanPropertyWriter.java:944)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:722)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:728)
        at com.fasterxml.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:774)
        at com.fasterxml.jackson.databind.ser.BeanSerializer.serialize(BeanSerializer.java:178)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider._serialize(DefaultSerializerProvider.java:480)
        at com.fasterxml.jackson.databind.ser.DefaultSerializerProvider.serializeValue(DefaultSerializerProvider.java:319)
        at com.fasterxml.jackson.databind.ObjectMapper._writeValueAndClose(ObjectMapper.java:4568)
        at com.fasterxml.jackson.databind.ObjectMapper.writeValueAsString(ObjectMapper.java:3821)
        ... 34 more
24/04/17 10:56:01 DEBUG DatahubEventEmitter: Emitting lineage: {"eventTime":"2024-04-17T02:56:01.095Z","producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunEvent","eventType":"COMPLETE","run":{"runId":"98aa87af-19ba-4141-aed6-3c0641d39104","facets":{"processing_engine":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/facets/1-1-0/ProcessingEngineRunFacet.json#/$defs/ProcessingEngineRunFacet","version":"3.3.3","name":"spark"},"environment-properties":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","environment-properties":{}},"spark_version":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","spark-version":"3.3.3"},"spark.logicalPlan":{"_producer":"https://github.com/OpenLineage/OpenLineage/tree/1.5.0/integration/spark","_schemaURL":"https://openlineage.io/spec/2-0-2/OpenLineage.json#/$defs/RunFacet","plan":[{"class":"org.apache.spark.sql.catalyst.plans.logical.GlobalLimit","num-children":1,"limitExpr":[{"class":"org.apache.spark.sql.catalyst.expressions.Literal","num-children":0,"value":"21","dataType":"integer"}],"child":0},{"class":"org.apache.spark.sql.catalyst.plans.logical.LocalLimit","num-children":1,"limitExpr":[{"class":"org.apache.spark.sql.catalyst.expressions.Literal","num-children":0,"value":"21","dataType":"integer"}],"child":0},{"class":"org.apache.spark.sql.catalyst.plans.logical.CommandResult","num-children":0,"output":[],"commandLogicalPlan":[{"class":"org.apache.spark.sql.catalyst.plans.logical.SetCatalogAndNamespace","num-children":1,"child":0},{"class":"org.apache.spark.sql.catalyst.analysis.ResolvedDBObjectName","num-children":0,"nameParts":"[test]"}],"commandPhysicalPlan":[{"class":"org.apache.spark.sql.execution.datasources.v2.SetCatalogAndNamespaceExec","num-children":0,"catalogName":"spark_catalog","namespace":"[test]"}],"rows":[]}]}}},"job":{"namespace":"default","name":"spark_shell.collect_limit","facets":{}},"inputs":[],"outputs":[]}
24/04/17 10:56:01 ERROR AsyncEventQueue: Listener DatahubSparkListener threw an exception
java.lang.NullPointerException
        at datahub.spark.DatahubEventEmitter.convertOpenLineageRunEventToDatahubJob(DatahubEventEmitter.java:88)
        at datahub.spark.DatahubEventEmitter.emit(DatahubEventEmitter.java:108)
        at io.openlineage.spark.agent.lifecycle.SparkSQLExecutionContext.end(SparkSQLExecutionContext.java:136)
        at io.openlineage.spark.agent.OpenLineageSparkListener.sparkSQLExecEnd(OpenLineageSparkListener.java:98)
        at io.openlineage.spark.agent.OpenLineageSparkListener.onOtherEvent(OpenLineageSparkListener.java:84)
        at datahub.spark.DatahubSparkListener.onOtherEvent(DatahubSparkListener.java:203)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent(SparkListenerBus.scala:100)
        at org.apache.spark.scheduler.SparkListenerBus.doPostEvent$(SparkListenerBus.scala:28)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.scheduler.AsyncEventQueue.doPostEvent(AsyncEventQueue.scala:37)
        at org.apache.spark.util.ListenerBus.postToAll(ListenerBus.scala:117)
        at org.apache.spark.util.ListenerBus.postToAll$(ListenerBus.scala:101)
        at org.apache.spark.scheduler.AsyncEventQueue.super$postToAll(AsyncEventQueue.scala:105)
        at org.apache.spark.scheduler.AsyncEventQueue.$anonfun$dispatch$1(AsyncEventQueue.scala:105)
        at scala.runtime.java8.JFunction0$mcJ$sp.apply(JFunction0$mcJ$sp.java:23)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:62)
        at org.apache.spark.scheduler.AsyncEventQueue.org$apache$spark$scheduler$AsyncEventQueue$$dispatch(AsyncEventQueue.scala:100)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.$anonfun$run$1(AsyncEventQueue.scala:96)
        at org.apache.spark.util.Utils$.tryOrStopSparkContext(Utils.scala:1446)
        at org.apache.spark.scheduler.AsyncEventQueue$$anon$2.run(AsyncEventQueue.scala:96)
```

**Comment by treff7es** [comment]
yes, sure, I will do it when I will have some time

**Comment by treff7es** [comment]
We have updated the OpenLinege plugin to the latest
