### ISSUE TITLE
[tableau] force_extraction_of_lineage_from_custom_sql_queries is not not permitted

### ISSUE THREAD

**Issue by usmanovbf** [datahub-project/datahub#10357]
**Describe the bug**

``` 
Failed to configure the source (tableau): 1 validation error for TableauConfig
force_extraction_of_lineage_from_custom_sql_queries
  extra fields not permitted (type=value_error.extra)
```
**To Reproduce**
1. Upgrade from 0.12.1 to 0.13.2
2. Add force_extraction_of_lineage_from_custom_sql_queries: true into Tableau recipe
3. Run
4. Get error (see in logs below)

**Expected behavior**
Use property force_extraction_of_lineage_from_custom_sql_queries properly according to the [documentation](https://datahubproject.io/docs/0.13.1/generated/ingestion/sources/tableau)

**Screenshots**
<img width="598" alt="Снимок экрана 2024-04-22 в 22 07 30" src="https://github.com/datahub-project/datahub/assets/18537762/38f4ca0b-e623-42b4-bd12-cd20c9f9f37b">

 - Version v0.13.2

**Additional context**
Logs:

``` 
~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': 'c492b5f2-f932-4e92-bcc8-29848935c685',
 'infos': ['2024-04-22 18:53:06.866682 INFO: Starting execution for task with name=RUN_INGEST',
           "2024-04-22 18:53:10.924058 INFO: Failed to execute 'datahub ingest', exit code 1",
           '2024-04-22 18:53:10.924281 INFO: Caught exception EXECUTING task_id=c492b5f2-f932-4e92-bcc8-29848935c685, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 140, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 282, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Logs ~~~~
Obtaining venv creation lock...
Acquired venv creation lock
venv is already set up
venv setup time = 0 sec
This version of datahub supports report-to functionality
+ exec datahub ingest run -c /tmp/datahub/ingest/c492b5f2-f932-4e92-bcc8-29848935c685/recipe.yml --report-to /tmp/datahub/ingest/c492b5f2-f932-4e92-bcc8-29848935c685/ingestion_report.json
[2024-04-22 18:53:09,382] INFO     {datahub.cli.ingest_cli:147} - DataHub CLI version: 0.13.1.2
[2024-04-22 18:53:09,418] INFO     {datahub.ingestion.run.pipeline:239} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://app-datahub-datahub-gms:8080
Failed to configure the source (tableau): 1 validation error for TableauConfig
force_extraction_of_lineage_from_custom_sql_queries
  extra fields not permitted (type=value_error.extra)

```

Recipe:

```
source:
  type: tableau
  config:
    ingest_owner: true
    extract_usage_stats: false
    extract_column_level_lineage: true
    force_extraction_of_lineage_from_custom_sql_queries: true
    token_value: '${censored}'
    platform_instance: censored
    connect_uri: censored
    site: ""
    extract_lineage_from_unsupported_custom_sql_queries: true
    extract_project_hierarchy: true
    token_name: censored
    stateful_ingestion:
      ignore_old_state: true
      enabled: true
    ingest_tags: true
    page_size: 3
    
```

**Comment by hsheth2** [comment]
@usmanovbf please use CLI version 0.13.1.3

Let me know if upgrading the CLI version doesn't help
