### ISSUE TITLE
dbt cloud ingestion failing

### ISSUE THREAD

**Issue by ipsingh88** [datahub-project/datahub#10523]
**Describe the bug**
dbt cloud ingestion failing with error TypeError: 'NoneType' object is not iterable

**To Reproduce**
1. Go to 'Manage ingestion'
2. Add new dbt cloud ingestion
3. Fill in form and execute
~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': 'ff84b82d-5e7f-4815-b2bf-9146f781adc0',
 'infos': ['2024-05-16 14:53:29.329882 INFO: Starting execution for task with name=RUN_INGEST',
           "2024-05-16 14:53:35.418972 INFO: Failed to execute 'datahub ingest', exit code 1",
           '2024-05-16 14:53:35.419249 INFO: Caught exception EXECUTING task_id=ff84b82d-5e7f-4815-b2bf-9146f781adc0, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 140, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 282, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Report ~~~~
{
  "cli": {
    "cli_version": "0.13.1",
    "cli_entry_location": "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/__init__.py",
    "py_version": "3.10.13 (main, Jan 17 2024, 05:40:33) [GCC 12.2.0]",
    "py_exec_path": "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/bin/python3",
    "os_details": "Linux-6.6.22-linuxkit-aarch64-with-glibc2.36",
    "mem_info": "74.29 MB",
    "peak_memory_usage": "74.29 MB",
    "disk_info": {
      "total": "62.67 GB",
      "used": "14.94 GB",
      "used_initally": "14.94 GB",
      "free": "44.51 GB"
    },
    "peak_disk_usage": "14.94 GB",
    "thread_count": 1,
    "peak_thread_count": 1
  },
  "source": {
    "type": "dbt-cloud",
    "report": {
      "events_produced": 0,
      "events_produced_per_sec": 0,
      "entities": {},
      "aspects": {},
      "warnings": {
        "model.biztech_edw.account": [
          "node is missing a status, schema metadata will be incomplete"
        ]
      },
      "failures": {},
      "soft_deleted_stale_entities": [],
      "sql_statements_parsed": 0,
      "sql_parser_detach_ctes_failures": 0,
      "sql_parser_skipped_missing_code": 0,
      "start_time": "2024-05-16 14:53:30.793670 (2.3 seconds ago)",
      "running_time": "2.3 seconds"
    }
  },
  "sink": {
    "type": "datahub-rest",
    "report": {
      "total_records_written": 0,
      "records_written_per_second": 0,
      "warnings": [],
      "failures": [],
      "start_time": "2024-05-16 14:53:30.718874 (2.38 seconds ago)",
      "current_time": "2024-05-16 14:53:33.093974 (now)",
      "total_duration_in_seconds": 2.38,
      "max_threads": 15,
      "gms_version": "",
      "pending_requests": 0
    }
  }
}

~~~~ Ingestion Logs ~~~~
Obtaining venv creation lock...
Acquired venv creation lock
venv is already set up
venv setup time = 0 sec
This version of datahub supports report-to functionality
+ exec datahub ingest run -c /tmp/datahub/ingest/ff84b82d-5e7f-4815-b2bf-9146f781adc0/recipe.yml --report-to /tmp/datahub/ingest/ff84b82d-5e7f-4815-b2bf-9146f781adc0/ingestion_report.json
[2024-05-16 14:53:30,681] INFO     {datahub.cli.ingest_cli:147} - DataHub CLI version: 0.13.1
[2024-05-16 14:53:30,720] INFO     {datahub.ingestion.run.pipeline:239} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms:8080
[2024-05-16 14:53:30,793] INFO     {datahub.ingestion.run.pipeline:256} - Source configured successfully.
[2024-05-16 14:53:30,793] INFO     {datahub.cli.ingest_cli:128} - Starting metadata ingestion
[2024-05-16 14:53:30,794] INFO     {datahub.ingestion.source.dbt.dbt_cloud:287} - Fetching models from dbt Cloud
[2024-05-16 14:53:31,764] INFO     {datahub.ingestion.source.dbt.dbt_cloud:287} - Fetching seeds from dbt Cloud
[2024-05-16 14:53:32,039] INFO     {datahub.ingestion.source.dbt.dbt_cloud:287} - Fetching sources from dbt Cloud
[2024-05-16 14:53:32,492] INFO     {datahub.ingestion.source.dbt.dbt_cloud:287} - Fetching snapshots from dbt Cloud
[2024-05-16 14:53:32,794] INFO     {datahub.ingestion.source.dbt.dbt_cloud:287} - Fetching tests from dbt Cloud
[2024-05-16 14:53:33,094] INFO     {datahub.ingestion.reporting.file_reporter:52} - Wrote UNKNOWN report successfully to <_io.TextIOWrapper name='/tmp/datahub/ingest/ff84b82d-5e7f-4815-b2bf-9146f781adc0/ingestion_report.json' mode='w' encoding='UTF-8'>
[2024-05-16 14:53:33,095] INFO     {datahub.cli.ingest_cli:133} - Source (dbt-cloud) report:
{'events_produced': 0,
 'events_produced_per_sec': 0,
 'entities': {},
 'aspects': {},
 'warnings': {'model.biztech_edw.account': ['node is missing a status, schema metadata will be incomplete']},
 'failures': {},
 'soft_deleted_stale_entities': [],
 'sql_statements_parsed': 0,
 'sql_parser_detach_ctes_failures': 0,
 'sql_parser_skipped_missing_code': 0,
 'start_time': '2024-05-16 14:53:30.793670 (2.3 seconds ago)',
 'running_time': '2.3 seconds'}
[2024-05-16 14:53:33,095] INFO     {datahub.cli.ingest_cli:136} - Sink (datahub-rest) report:
{'total_records_written': 0,
 'records_written_per_second': 0,
 'warnings': [],
 'failures': [],
 'start_time': '2024-05-16 14:53:30.718874 (2.38 seconds ago)',
 'current_time': '2024-05-16 14:53:33.095271 (now)',
 'total_duration_in_seconds': 2.38,
 'max_threads': 15,
 'gms_version': '',
 'pending_requests': 0}
[2024-05-16 14:53:33,341] ERROR    {datahub.entrypoints:201} - Command failed: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/entrypoints.py", line 188, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 454, in wrapper
    raise e
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 403, in wrapper
    res = func(*args, **kwargs)
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 201, in run
    ret = loop.run_until_complete(run_ingestion_and_check_upgrade())
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 185, in run_ingestion_and_check_upgrade
    ret = await ingestion_future
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 139, in run_pipeline_to_completion
    raise e
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 131, in run_pipeline_to_completion
    pipeline.run()
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 405, in run
    for wu in itertools.islice(
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 147, in auto_stale_entity_removal
    for wu in stream:
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 171, in auto_workunit_reporter
    for wu in stream:
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 253, in auto_browse_path_v2
    for urn, batch in _batch_workunits_by_urn(stream):
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 391, in _batch_workunits_by_urn
    for wu in stream:
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 184, in auto_materialize_referenced_tags
    for wu in stream:
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 91, in auto_status_aspect
    for wu in stream:
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/source/dbt/dbt_common.py", line 839, in get_workunits_internal
    all_nodes, additional_custom_props = self.load_nodes()
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/source/dbt/dbt_cloud.py", line 300, in load_nodes
    nodes = [self._parse_into_dbt_node(node) for node in raw_nodes]
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/source/dbt/dbt_cloud.py", line 300, in <listcomp>
    nodes = [self._parse_into_dbt_node(node) for node in raw_nodes]
  File "/tmp/datahub/ingest/venv-dbt-cloud-b3b89d5496a000a4/lib/python3.10/site-packages/datahub/ingestion/source/dbt/dbt_cloud.py", line 382, in _parse_into_dbt_node
    for column in sorted(node["columns"], key=lambda c: c["index"])
TypeError: 'NoneType' object is not iterable


**Expected behavior**
Expected the ingestion to be able to run.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: mac OS 14.4.1
 - Browser Chrome
 - Version 124.0.6367.203

**Additional context**
dbt configuration:
Platform: Databricks (hive_metastore)
dbt version: 1.7.14

**Comment by hsheth2** [comment]
Already fixed by https://github.com/datahub-project/datahub/pull/10471

**Comment by ipsingh88** [comment]
@hsheth2 Is this already deployed ? What version of datahub should we use to resolve this I am using 0.13.1

**Comment by hsheth2** [comment]
@ipsingh88 use CLI version 0.13.2.3

**Comment by ipsingh88** [comment]
@hsheth2 
I am already using this version of cli:
<img width="285" alt="image" src="https://github.com/datahub-project/datahub/assets/34692103/8d4761d5-49ab-45b6-9c97-c63a656148c7">

I subsequently use `datahub docker quickstart` to start datahub and the version on datahub ui is 0.13.1. I continue to see the  same error.

**Comment by hsheth2** [comment]
You need to set the version in the UI https://datahubproject.io/docs/ui-ingestion#advanced-ingestion-configs

**Comment by ipsingh88** [comment]
Thanks, that resolved this error, Although I got a different one. I will debug that. Thanks again for your support on this.

**Comment by robertnajmik** [comment]
@ipsingh88 Hi, would you mind to share, what was the next error you have run into? I'm dealing with the same issue as mentioned above and the update of CLI version led to another error. Maybe it's the same you got.
`{
          "error": "Unable to emit metadata to DataHub GMS: com.linkedin.metadata.entity.validation.ValidationException: Failed to validate record with class com.linkedin.entity.Entity: ERROR :: /value/com.linkedin.metadata.snapshot.DatasetSnapshot/aspects/5/com.linkedin.dataset.ViewProperties/formattedViewLogic :: unrecognized field found but not allowed\n",
          "info": {
            "exceptionClass": "com.linkedin.restli.server.RestLiServiceException",
            "message": "com.linkedin.metadata.entity.validation.ValidationException: Failed to validate record with class com.linkedin.entity.Entity: ERROR :: /value/com.linkedin.metadata.snapshot.DatasetSnapshot/aspects/5/com.linkedin.dataset.ViewProperties/formattedViewLogic :: unrecognized field found but not allowed\n",
            "status": 422,
            "urn": "urn:li:dataset:(urn:li:dataPlatform:dbt,staging.shipmonk_db.stg_carrier,PROD)"
          }
        },`

**Comment by ipsingh88** [comment]
> @ipsingh88 Hi, would you mind to share, what was the next error you have run into? I'm dealing with the same issue as mentioned above and the update of CLI version led to another error. Maybe it's the same you got. `{ "error": "Unable to emit metadata to DataHub GMS: com.linkedin.metadata.entity.validation.ValidationException: Failed to validate record with class com.linkedin.entity.Entity: ERROR :: /value/com.linkedin.metadata.snapshot.DatasetSnapshot/aspects/5/com.linkedin.dataset.ViewProperties/formattedViewLogic :: unrecognized field found but not allowed\n", "info": { "exceptionClass": "com.linkedin.restli.server.RestLiServiceException", "message": "com.linkedin.metadata.entity.validation.ValidationException: Failed to validate record with class com.linkedin.entity.Entity: ERROR :: /value/com.linkedin.metadata.snapshot.DatasetSnapshot/aspects/5/com.linkedin.dataset.ViewProperties/formattedViewLogic :: unrecognized field found but not allowed\n", "status": 422, "urn": "urn:li:dataset:(urn:li:dataPlatform:dbt,staging.prod_db.stg_carrier,PROD)" } },`

Unable to figure out at the moment. This is what I see in logs:


{'exec_id': '9e8b48b4-b160-43c6-9bc3-cacf27d5902f',
 'infos': ['2024-05-16 22:27:30.729501 INFO: Starting execution for task with name=RUN_INGEST',
           "2024-05-16 22:29:11.715293 INFO: Failed to execute 'datahub ingest', exit code 1",
           '2024-05-16 22:29:11.715708 INFO: Caught exception EXECUTING task_id=9e8b48b4-b160-43c6-9bc3-cacf27d5902f, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 140, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 282, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

**Comment by robertnajmik** [comment]
@hsheth2 Hi, this is my current set-up:
`chart: 'datahub', repoURL: 'https://helm.datahubproject.io', targetRevision: '0.4.4'`
`chart: 'datahub-prerequisites', repoURL: 'https://helm.datahubproject.io', targetRevision: '0.1.10',`
when I'm running the dbt ingestion at the moment it returns the: _TypeError: 'NoneType' object is not iterable_ and from the log I see it runs the "cli_version": "0.13.0" and "gms_version": "v0.13.0";
In case I manually update the "cli_version" to "0.13.2.3" as it was described in this thread then I receive the _"error": "Unable to emit metadata to DataHub GMS_. 
I do apologize but what exactly needs to be updated to which version to fix the dbt ingestion? 

Thank you.

**Comment by hsheth2** [comment]
@robertnajmik you need to update GMS so that it returns `"gms_version": "v0.13.2"`. In your case, that means updating helm
