### ISSUE TITLE
Users with Admin role cannot view Access Tokens

### ISSUE THREAD

**Issue by kespak-altic** [datahub-project/datahub#10620]
**Describe the bug**
After updating DataHub from 0.13.0 to 0.13.2 users with Admin permissions cannot view access tokens. Note that user is authenticated with OIDC (KeyCloak). The displayed error is:
```Unauthorized to perform this action. Please contact your DataHub administrator. (code 403)```
However, the default DataHub root user, ```datahub``` is able to view and manage access tokens. 

Error when querying in GraphQL:
`{
  "errors": [
    {
      "message": "Unauthorized to perform this action. Please contact your DataHub administrator.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "listAccessTokens"
      ],
      "extensions": {
        "code": 403,
        "type": "UNAUTHORIZED",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": null,
  "extensions": {}
}`

Error logged in DataHub GMS service:

> 2024-05-31 06:39:57,031 [Thread-98092] INFO  c.l.d.g.r.a.ListAccessTokensResolver:53 - User urn:li:corpuser:adminuser@example.com listing access tokens with filters [{ field: "ownerUrn", value: "urn:li:corpuser:adminuser@example.com" }]
> 2024-05-31 06:39:57,032 [Thread-98092] ERROR c.d.authorization.AuthorizerChain:83 - Caught exception while attempting to authorize request using Authorizer com.datahub.authorization.DataHubAuthorizer. Skipping authorizer.
> java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to retrieve entity with urn , invalid urn
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> Caused by: java.lang.RuntimeException: Failed to retrieve entity with urn , invalid urn
> 	at com.linkedin.common.urn.UrnUtils.getUrn(UrnUtils.java:56)
> 	at com.datahub.authorization.fieldresolverprovider.DomainFieldResolverProvider.getDomains(DomainFieldResolverProvider.java:83)
> 	at com.datahub.authorization.FieldResolver.lambda$getResolverFromFunction$1(FieldResolver.java:36)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
> 	... 1 common frames omitted
> 2024-05-31 06:39:57,044 [Thread-98092] ERROR c.l.d.g.e.DataHubDataFetcherExceptionHandler:45 - Failed to execute
> java.util.concurrent.CompletionException: java.lang.NullPointerException: Cannot invoke "java.util.List.equals(Object)" because the return value of "com.linkedin.datahub.graphql.generated.FacetFilterInput.getValues()" is null
> 	at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
> 	at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
> 	at java.base/java.lang.Thread.run(Thread.java:840)
> Caused by: java.lang.NullPointerException: Cannot invoke "java.util.List.equals(Object)" because the return value of "com.linkedin.datahub.graphql.generated.FacetFilterInput.getValues()" is null
> 	at com.linkedin.datahub.graphql.resolvers.auth.ListAccessTokensResolver.lambda$isListingSelfTokens$3(ListAccessTokensResolver.java:123)
> 	at java.base/java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
> 	at java.base/java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1602)
> 	at java.base/java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:129)
> 	at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:527)
> 	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:513)
> 	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
> 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
> 	at java.base/java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
> 	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
> 	at java.base/java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:632)
> 	at com.linkedin.datahub.graphql.resolvers.auth.ListAccessTokensResolver.isListingSelfTokens(ListAccessTokensResolver.java:120)
> 	at com.linkedin.datahub.graphql.resolvers.auth.ListAccessTokensResolver.lambda$get$2(ListAccessTokensResolver.java:59)
> 	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
> 	... 1 common frames omitted
> 2024-05-31 06:39:57,045 [Thread-98091] ERROR c.datahub.graphql.GraphQLController:125 - Errors while executing graphQL query: "query {\n  listAccessTokens(\n    input: {\n      start: 0\n      count: 100\n      filters: [{ field: \"ownerUrn\", value: \"urn:li:corpuser:adminuser@example.com\" }]\n    }\n  ) {\n    start\n    count\n    total\n    tokens {\n      urn\n      id\n      actorUrn\n      ownerUrn\n      type\n      \n    }\n  }\n}\n", result: {errors=[{message=An unknown error occurred., locations=[{line=2, column=3}], path=[listAccessTokens], extensions={code=500, type=SERVER_ERROR, classification=DataFetchingException}}], data=null, extensions={tracing={version=1, startTime=2024-05-31T06:39:57.031027127Z, endTime=2024-05-31T06:39:57.045054640Z, duration=14028338, parsing={startOffset=142900, duration=122925}, validation={startOffset=264207, duration=114691}, execution={resolvers=[{path=[listAccessTokens], parentType=Query, returnType=ListAccessTokenResult!, fieldName=listAccessTokens, startOffset=359026, duration=13442528}]}}}}, errors: [DataHubGraphQLError{path=[listAccessTokens], code=SERVER_ERROR, locations=[SourceLocation{line=2, column=3}]}]
> 

**To Reproduce**
1. Log on as a user with Admin role using OIDC provider
2. Click on 'Manage your Datahub Settings'
3. Open 'Access Tokens'

**Expected behavior**
A list of tokens is displayed

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge
 - Version 125.0.2535.67

**Additional context**
DataHub is deployed to Kubernetes using helm charts.

**Comment by paularmand** [comment]
We recently bumped our version to 0.13.2 and noticed our users are not logged in correctly.
SSO / OIDC user used to map to urn:li:corpuser:firstname.lastname@company.com, but the same SSO login now maps to urn:li:corpuser:firstname.lastname .

Coming back to your case, the user might be mapped to a new user without the admin privileges set.

**Comment by uselessidbr** [comment]
Hello @paularmand is there any workaround? The application is unusable because there is no ADMIN user to login.

> We recently bumped our version to 0.13.2 and noticed our users are not logged in correctly. SSO / OIDC user used to map to urn:li:corpuser:[firstname.lastname@company.com](mailto:firstname.lastname@company.com), but the same SSO login now maps to urn:li:corpuser:firstname.lastname .
> 
> Coming back to your case, the user might be mapped to a new user without the admin privileges set.
> 
> ps: if you go to your profile page as a logged in user, you can check the URL in the browser for the user urn that is used.

**Comment by uselessidbr** [comment]
We managed to solve this but in our case the admin role was missing, it seemed that the policies could not be loaded.

We changed two settings, so, i’m not sure of which one fixed the problem:

- SET KAFKA ENV for KERBEROS and also the volumes and volumemounts on “datahubSystemUpdate” and “datahubUpgrade”;
- SET to “true” the ENV REST_API_AUTHORIZATION_ENABLED on “datahub-gms”. 

> Hello @paularmand is there any workaround? The application is unusable because there is no ADMIN user to login.
> 
> > We recently bumped our version to 0.13.2 and noticed our users are not logged in correctly. SSO / OIDC user used to map to urn:li:corpuser:[firstname.lastname@company.com](mailto:firstname.lastname@company.com), but the same SSO login now maps to urn:li:corpuser:firstname.lastname .
> > Coming back to your case, the user might be mapped to a new user without the admin privileges set.
> > ps: if you go to your profile page as a logged in user, you can check the URL in the browser for the user urn that is used.

**Comment by paularmand** [comment]
For us it was related to: https://github.com/acryldata/datahub-helm/issues/414 , but I think your case is different.
