### ISSUE TITLE
Datahub Docker Ingestion Error

### ISSUE THREAD

**Issue by iqqy19** [datahub-project/datahub#10759]
datahub docker ingest-sample-data
Downloading sample data...
Starting ingestion...
[2024-06-21 11:08:42,206] ERROR    {datahub.entrypoints:205} - Command failed: Failed to connect to DataHub: Unable to connect to http://localhost:8080/config with status_code: 504.
Please check your configuration and make sure you are talking to the DataHub GMS (usually <datahub-gms-host>:8080) or Frontend GMS API (usually <frontend>:9002/api/gms).
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datahub/ingestion/run/pipeline.py", line 122, in _add_init_error_context
    yield
  File "/usr/local/lib/python3.11/site-packages/datahub/ingestion/run/pipeline.py", line 218, in __init__
    self.graph.test_connection()
  File "/usr/local/lib/python3.11/site-packages/datahub/ingestion/graph/client.py", line 148, in test_connection
    super().test_connection()
  File "/usr/local/lib/python3.11/site-packages/datahub/emitter/rest_emitter.py", line 185, in test_connection
    raise ConfigurationError(message)
datahub.configuration.common.ConfigurationError: Unable to connect to http://localhost:8080/config with status_code: 504.
Please check your configuration and make sure you are talking to the DataHub GMS (usually <datahub-gms-host>:8080) or Frontend GMS API (usually <frontend>:9002/api/gms).

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/datahub/entrypoints.py", line 192, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datahub/telemetry/telemetry.py", line 454, in wrapper
    raise e
  File "/usr/local/lib/python3.11/site-packages/datahub/telemetry/telemetry.py", line 403, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datahub/cli/docker_cli.py", line 1006, in ingest_sample_data
    pipeline = Pipeline.create(recipe, no_default_report=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/datahub/ingestion/run/pipeline.py", line 365, in create
    return cls(
           ^^^^
  File "/usr/local/lib/python3.11/site-packages/datahub/ingestion/run/pipeline.py", line 215, in __init__
    with _add_init_error_context("connect to DataHub"):
  File "/usr/lib64/python3.11/contextlib.py", line 155, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/usr/local/lib/python3.11/site-packages/datahub/ingestion/run/pipeline.py", line 124, in _add_init_error_context
    raise PipelineInitError(f"Failed to {step}: {e}") from e
datahub.ingestion.run.pipeline.PipelineInitError: Failed to connect to DataHub: Unable to connect to http://localhost:8080/config with status_code: 504.
Please check your configuration and make sure you are talking to the DataHub GMS (usually <datahub-gms-host>:8080) or Frontend GMS API (usually <frontend>:9002/api/gms).

**Comment by yoonhyejin** [comment]
Hello! For troubleshooting, please use our [Slack community](https://datahub.com/slack/). :) I will close this issue, thanks!
