### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by edkry** [datahub-project/datahub#10976]
**Describe the bug**
When deny pattern is added with wildcard (*), datahub ingestion fails with an error. When deny pattern is removed, there is no error.

**To Reproduce**

Add deny pattern as '*_tmp':

```yaml
source:
    type: trino
    config:
        host_port: 'port'
        database: db
        username: user
        include_views: false
        include_tables: true
        profiling:
            enabled: false
            profile_table_level_only: true
        stateful_ingestion:
            enabled: false
        password: pswd
        schema_pattern:
            allow:
                - afd
                - asd
                - acd
                - abc
        table_pattern:
            deny:
                - '*_tmp'

```

Error I get:

```
⏳ Pipeline running successfully so far; produced 1 events in 10.91 seconds.
2024-07-24 08:55:02,063 INFO sqlalchemy.engine.Engine SELECT "table_name"
FROM "information_schema"."tables"
WHERE "table_schema" = ? and "table_type" != 'VIEW'
[2024-07-24 08:55:02,063] INFO     {sqlalchemy.engine.base:1863} - SELECT "table_name"
FROM "information_schema"."tables"
WHERE "table_schema" = ? and "table_type" != 'VIEW'
2024-07-24 08:55:02,064 INFO sqlalchemy.engine.Engine [dialect trino+rest does not support caching 0.00121s] ('macroeconomic_public_data_sodra_raw',)
[2024-07-24 08:55:02,064] INFO     {sqlalchemy.engine.base:1868} - [dialect trino+rest does not support caching 0.00121s] ('macroeconomic_public_data_sodra_raw',)
[2024-07-24 08:55:02,121] ERROR    {datahub.ingestion.source.sql.sql_common:385} - macroeconomic_public_data_sodra_raw => Tables error: nothing to repeat at position 0
Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-trino-2b9c1ab97dc6cd7f/lib/python3.10/site-packages/datahub/ingestion/source/sql/sql_common.py", line 694, in loop_tables
    if not sql_config.table_pattern.allowed(dataset_name):
  File "/tmp/datahub/ingest/venv-trino-2b9c1ab97dc6cd7f/lib/python3.10/site-packages/datahub/configuration/common.py", line 247, in allowed
    if re.match(deny_pattern, string, self.regex_flags):
  File "/usr/local/lib/python3.10/re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "/usr/local/lib/python3.10/re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/local/lib/python3.10/sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/local/lib/python3.10/sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "/usr/local/lib/python3.10/sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "/usr/local/lib/python3.10/sre_parse.py", line 669, in _parse
    raise source.error("nothing to repeat",
re.error: nothing to repeat at position 0
```

**Expected behavior**
Ingestion runs fine and ignores tables which ends with _tmp

**Comment by treff7es** [comment]
@edkry, your regexp pattern is invalid as it starts with a raw wildcard (star) character, and as the error says, there is nothing to repeat.
Correctly, it should be: `.*_tmp`

**Comment by edkry** [comment]
Thanks
