### ISSUE TITLE
`UpdateIndicesHook` failing after update to v0.14.0

### ISSUE THREAD

**Issue by adamstruck** [datahub-project/datahub#11197]
**Describe the bug**

After upgrading I started seeing tons of errors like this one below during my Looker ingest task. 

```
Failed to execute MCL hook with name com.linkedin.metadata.kafka.hook.UpdateIndicesHook
java.lang.NullPointerException: null algorithm name
	at java.base/java.util.Objects.requireNonNull(Objects.java:235)
	at java.base/java.security.MessageDigest.getInstance(MessageDigest.java:182)
	at com.linkedin.metadata.systemmetadata.ElasticSearchSystemMetadataService.toDocId(ElasticSearchSystemMetadataService.java:92)
	at com.linkedin.metadata.systemmetadata.ElasticSearchSystemMetadataService.insert(ElasticSearchSystemMetadataService.java:139)
	at com.linkedin.metadata.service.UpdateIndicesService.updateSystemMetadata(UpdateIndicesService.java:620)
	at com.linkedin.metadata.service.UpdateIndicesService.handleUpdateChangeEvent(UpdateIndicesService.java:186)
	at com.linkedin.metadata.service.UpdateIndicesService.handleChangeEvent(UpdateIndicesService.java:143)
	at com.linkedin.metadata.kafka.hook.UpdateIndicesHook.invoke(UpdateIndicesHook.java:87)
	at com.linkedin.metadata.kafka.MCLKafkaListener.consume(MCLKafkaListener.java:86)
	at jdk.internal.reflect.GeneratedMethodAccessor125.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
	at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
	at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56)
	at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:376)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:92)
	at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:53)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2888)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2866)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.lambda$doInvokeRecordListener$55(KafkaMessageListenerContainer.java:2783)
	at io.micrometer.observation.Observation.observe(Observation.java:565)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2781)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2631)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2517)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:2155)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1495)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1460)
	at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1330)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:840)
```

**Comment by adamstruck** [comment]
Seems like this was fixed in https://github.com/datahub-project/datahub/pull/11191. 

Any plans to cut a new release?

**Comment by adamstruck** [comment]
Looks like I am late to the game: https://github.com/datahub-project/datahub/releases/tag/v0.14.0.1
