### ISSUE TITLE
ingest filesource with URL

### ISSUE THREAD

**Issue by ttekampe** [datahub-project/datahub#11218]
**Describe the bug**
File source seems to not work with an URL to a remote metadata file

**To Reproduce**
Steps to reproduce the behaviour:
run

```
 datahub ingest mcps URL_TO_YOUR_METADATAFILE
```
which returns
```
Error: Invalid value for 'PATH': Path
```

or alternatively something like this:
```
from datahub.ingestion.run.pipeline import Pipeline

recipe: dict = {
        "source": {
            "type": "file",
            "config": {
                "path": URL_TO_YOUR_METADATAFILE
            },      
        },
    }

pipeline = Pipeline.create(recipe, no_default_report=True)
pipeline.run()
_ = pipeline.pretty_print_summary()
```
gives 
```
-[2024-08-21 10:53:10,230] ERROR    {datahub.ingestion.run.pipeline:737} - Ingestion pipeline threw an uncaught exception
Traceback (most recent call last):
  File "/shared/testwiese/datahub/venv/lib/python3.12/site-packages/datahub/ingestion/run/pipeline.py", line 461, in run
    for wu in itertools.islice(
  File "/shared/testwiese/datahub/venv/lib/python3.12/site-packages/datahub/ingestion/api/source_helpers.py", line 147, in auto_workunit_reporter
    for wu in stream:
  File "/shared/testwiese/datahub/venv/lib/python3.12/site-packages/datahub/ingestion/source/file.py", line 212, in get_workunits_internal
    for f in self.get_filenames():
  File "/shared/testwiese/datahub/venv/lib/python3.12/site-packages/datahub/ingestion/source/file.py", line 197, in get_filenames
    fs_class = fs_registry.get(schema)
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/shared/testwiese/datahub/venv/lib/python3.12/site-packages/datahub/ingestion/api/registry.py", line 172, in get
    raise KeyError(f"Did not find a registered class for {key}")
KeyError: 'Did not find a registered class for https'
```

or using the cli with a file recipe like this:
```
source:
  type: file
  config:
    # Coordinates
    filename: HTTPS_URL_TO_YOUR_METADATA_FILE

sink:
  type: "datahub-rest"
  config:
    server: "YOUR_GMS_URL"
    token: "YOUR_TOKEN"

```

**Expected behavior**
The path configurable according to the [docs](https://datahubproject.io/docs/generated/ingestion/sources/metadata-file) is:
> File path to folder or file to ingest, or URL to a remote file. If pointed to a folder, all files with extension {file_extension} (default json) within that folder will be processed.

So I would expect that the file is pulled from the URL and ingested into my datahub instance

**Additional context**
The URL I am using is a presigned URL to a file in an AWS bucket, so it has the structure:
```
https://my_bucket_name.s3.eu-west-1.amazonaws.com/my_metadata_file.metadata.json?response-content-disposition=inline&X-Amz-Security-Token=...SOME_MORE_AUTH_STUFF_HERE...```

**Comment by taabrcr** [comment]
It would be very handy that this supports directly S3 and not just local file system.
