### ISSUE TITLE
Invariant Violation: 8 when trying to raise an incident

### ISSUE THREAD

**Issue by Gerrit-K** [datahub-project/datahub#11828]
**Describe the bug**
When trying to raise a data incident, there's a javascript error in the browser console with the message `Invariant Violation: 8`. The UI is not updated, but the incident is actually created, which can be seen when the page is reloaded.

**To Reproduce**
1. Go to some data asset, e.g. a table
2. Click on 'Incidents'
3. Click on 'Raise Incident'
4. Fill in the form and click 'Add'
5. You'll see a popup 'Failed to raise incident! An unexpected error occurred' and a more detailed error in the browser console:
```
Invariant Violation: Invariant Violation: 8 (see https://github.com/apollographql/invariant-packages)
    at new t (https://my.datahub.instance/assets/index-98a3141e.js:67:3362)
    at https://my.datahub.instance/assets/index-98a3141e.js:99:28292
    at Set.forEach (<anonymous>)
    at e.processSelectionSet (https://my.datahub.instance/assets/index-98a3141e.js:99:27823)
    at e.processFieldValue (https://my.datahub.instance/assets/index-98a3141e.js:99:28729)
    at https://my.datahub.instance/assets/index-98a3141e.js:99:28670
    at Array.map (<anonymous>)
    at e.processFieldValue (https://my.datahub.instance/assets/index-98a3141e.js:99:28644)
    at https://my.datahub.instance/assets/index-98a3141e.js:99:28024
    at Set.forEach (<anonymous>)
```

**Expected behavior**
Creating incidents should not raise an error.

**Desktop (please complete the following information):**
 - OS: macOS 14.7
 - Browser chrome 130.0.6723.117
 - DataHub `v0.14.1`, started via `datahub docker quickstart --standalone_consumers --version v0.14.1` and `datahub docker ingest-sample-data`

**Additional context**
The gms doesn't seem to log any errors.

**Comment by AdrianMachado** [comment]
I believe this is solved now
