### ISSUE TITLE
After associating a Dataset with Structured Property (through GraphiQL), the dataset UI vanished

### ISSUE THREAD

**Issue by raychaudhuri-amitava** [datahub-project/datahub#11995]
Hello,
I tried to associate a Structured Property with Dataset using the following mutation graphql:
mutation upsertStructuredProperties {
  upsertStructuredProperties(
    input: {
      assetUrn: "urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)",
      structuredPropertyInputParams: [
        {
          structuredPropertyUrn: "urn:li:structuredProperty:PIIROWS",
          values: [
            {
              stringValue: "event_name-event_data"
            }
          ]
        }
      ]
    }
  ) {
     properties{
      structuredProperty{
        urn
      }
  }
  }
}
After this I am not able to see anything on UI.
http://localhost:9002/dataset/urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)
DataHub
Something went wrong.
An unexpected error occurred. Please try again later, or reach out to your administrator
Need support? Check out these resources:
  DataHub Project
  DataHub Docs
  DataHub GitHub (edited) 
![Screenshot 2024-12-02 at 3 16 41 AM](https://github.com/user-attachments/assets/99952807-faa9-4039-9d5d-27fbb2df247d)

**Comment by datamacgyver** [comment]
Suspect I'm having the same issue on 0.15.0, even creating structured properties in the UI raises and internal server error. Did you ever fix it @raychaudhuri-amitava ?

**Comment by datamacgyver** [comment]
The logs are exciting: 

025-01-14 21:11:44,444 [ForkJoinPool.commonPool-worker-357] ERROR c.l.d.g.e.DataHubDataFetcherExceptionHandler:45 - Failed to execute
java.util.concurrent.CompletionException: java.lang.NoClassDefFoundError: Could not initialize class com.linkedin.datahub.graphql.types.entitytype.EntityTypeUrnMapper
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:332)
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:347)
        at java.base/java.util.concurrent.CompletableFuture$BiRelay.tryFire(CompletableFuture.java:1498)
        at java.base/java.util.concurrent.CompletableFuture$CoCompletion.tryFire(CompletableFuture.java:1219)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:2162)
        at org.dataloader.DataLoaderHelper.lambda$dispatchQueueBatch$3(DataLoaderHelper.java:273)
        at java.base/java.util.concurrent.CompletableFuture.uniExceptionally(CompletableFuture.java:990)
        at java.base/java.util.concurrent.CompletableFuture$UniExceptionally.tryFire(CompletableFuture.java:974)
        at java.base/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class com.linkedin.datahub.graphql.types.entitytype.EntityTypeUrnMapper
        at com.linkedin.datahub.graphql.types.entitytype.EntityTypeEntityMapper.apply(EntityTypeEntityMapper.java:40)
        at com.linkedin.datahub.graphql.types.entitytype.EntityTypeEntityMapper.map(EntityTypeEntityMapper.java:23)
        at com.linkedin.datahub.graphql.types.entitytype.EntityTypeType.lambda$batchLoad$0(EntityTypeType.java:71)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at com.linkedin.datahub.graphql.types.entitytype.EntityTypeType.batchLoad(EntityTypeType.java:73)
        at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$createDataLoader$266(GmsGraphQLEngine.java:3138)
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 6 common frames omitted
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.IllegalArgumentException: Multiple entries with same key: dataProcessInstance=urn:li:entityType:datahub.dataProcessInstance and dataProcessInstance=urn:li:entityType:datahub.dataProcessInstance [in thread "ForkJoinPool.commonPool-worker-34"]
        at com.google.common.collect.ImmutableMap.conflictException(ImmutableMap.java:378)
        at com.google.common.collect.ImmutableMap.checkNoConflict(ImmutableMap.java:372)
        at com.google.common.collect.RegularImmutableMap.checkNoConflictInKeyBucket(RegularImmutableMap.java:246)
        at com.google.common.collect.RegularImmutableMap.fromEntryArrayCheckingBucketOverflow(RegularImmutableMap.java:133)
        at com.google.common.collect.RegularImmutableMap.fromEntryArray(RegularImmutableMap.java:95)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:572)
        at com.google.common.collect.ImmutableMap$Builder.buildOrThrow(ImmutableMap.java:600)
        at com.google.common.collect.ImmutableMap$Builder.build(ImmutableMap.java:587)
        at com.linkedin.datahub.graphql.types.entitytype.EntityTypeUrnMapper.<clinit>(EntityTypeUrnMapper.java:83)
        ... 19 common frames omitted

**Comment by raychaudhuri-amitava** [comment]
> Suspect I'm having the same issue on 0.15.0, even creating structured properties in the UI raises and internal server error. Did you ever fix it [@raychaudhuri-amitava](https://github.com/raychaudhuri-amitava) ?

I am using custom properties instead of structural properties. I will move to structural properties once this issue is fixed.
