### ISSUE TITLE
Cannot connect to Self-Hosted Tableau Server via Proxy Server with HTTPS

### ISSUE THREAD

**Issue by chenteddybear** [datahub-project/datahub#12069]
Linux version: Ubuntu 24.04 LTS
DataHub CLI version: 0.14.1
Datahub version: 0.14.1
Models: bundled
Python version: 3.12.3 (main, Nov  6 2024, 18:32:19) [GCC 13.2.0]
DataHub  Docker Installation

I’m running into an issue with DataHub where I can’t connect to a self-hosted Tableau server through the proxy using Tableau ingestion. It works fine when I use non-secure HTTP with the server’s IP, but it fails when I try with the DNS URL and HTTPS.

I’ve added the https_proxy details to both the datahub-frontend-react and datahub-actions services in the docker-compose-without-neo4j-m1.quickstart.yml file, but it doesn’t seem to pick up the proxy during the Tableau ingestion process. What’s odd is that when I use curl inside the DataHub container with the same proxy and DNS URL over HTTPS, it connects just fine.

Also, I don’t have any issues connecting to BigQuery using the BigQuery ingestion process, so the proxy setup seems to work properly in other cases. Could you help check if the Tableau ingestion is handling proxy configurations correctly?

**This is my yaml file for Tableau ingestion:**
source:
    type: tableau
    config:
        connect_uri: 'https://luffy.labtest.com'
        stateful_ingestion:
            enabled: true
        ingest_tags: true
        ingest_owner: true
        token_name: DataHub
        token_value: '${Tableau_Token}'
        site: TW

**Please see my test results below:**

Results of Talbleau ingestion via HTTPS/HTTP URL and IP.  
[https_ip_failure.txt](https://github.com/user-attachments/files/18070456/https_ip_failure.txt)
[https_url_failure.txt](https://github.com/user-attachments/files/18070457/https_url_failure.txt)
[http_ip_success.txt](https://github.com/user-attachments/files/18070458/http_ip_success.txt)

Result of successful Curl connection via Proxy
[curl_https_url_success.txt](https://github.com/user-attachments/files/18070495/curl_https_url_success.txt)

**Comment by chenteddybear** [comment]
i tried adding session_trust_env: true the tableau ingestion yaml file and I've got the following error:

[2024-12-10 03:00:18,785] DEBUG    {datahub.ingestion.run.pipeline:364} - Reporter type:file,<class 'datahub.ingestion.reporting.file_reporter.FileReporter'> configured.
[2024-12-10 03:00:19,263] DEBUG    {datahub.entrypoints:215} - Error: Failed to configure the source (tableau): 1 validation error for TableauConfig
session_trust_env
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-tableau-3cbb1ad0ed8a0388/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 136, in _add_init_error_context
    yield
  File "/tmp/datahub/ingest/venv-tableau-3cbb1ad0ed8a0388/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 289, in __init__
    self.source = source_class.create(
  File "/tmp/datahub/ingest/venv-tableau-3cbb1ad0ed8a0388/lib/python3.10/site-packages/datahub/ingestion/source/tableau/tableau.py", line 628, in create
    config = TableauConfig.parse_obj(config_dict)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for TableauConfig
session_trust_env
  extra fields not permitted (type=value_error.extra)

**Comment by chenteddybear** [comment]
i tried the following two options and it got errored out as well:

ingest_external_links_for_charts: false
ingest_external_links_for_dashboards: false


/tmp/datahub/logs/a552ae74-534e-4606-a7e2-ed75ecf75355/artifacts/ingestion_report.json
[2024-12-13 04:36:02,201] INFO     {datahub.cli.ingest_cli:149} - DataHub CLI version: 0.14.1
[2024-12-13 04:36:02,206] INFO     {datahub.ingestion.run.pipeline:254} - No sink configured, attempting to use the default datahub-rest sink.
[2024-12-13 04:36:02,218] INFO     {datahub.ingestion.run.pipeline:271} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms:8080
Failed to configure the source (tableau): 2 validation errors for TableauConfig
ingest_external_link_for_charts
  extra fields not permitted (type=value_error.extra)
ingest_external_link_for_dashboards
  extra fields not permitted (type=value_error.extra)

**Comment by chenteddybear** [comment]
issue solved after upgrading to v1.1.0 with the support of session_trust_env parameter for tableau ingestion.  the parameter wasn't available in v0.14.1
