### ISSUE TITLE
Neo4j connection timeout/retry not sufficient

### ISSUE THREAD

**Issue by gabe-lyons** [datahub-project/datahub#2592]
**Describe the bug**
In certain setups, GMS with raise connection errors with neo4j even when the connection is healthy. 

**To Reproduce**
n/a

**Expected behavior**
GMS should adjust timeout and retry parameters to be more forgiving. Healthy connections should consistently return results.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by RickardCardell** [comment]
**Setup**
Datahub version v0.7.1
Running all containers on a cloud provider.
Neo4j 4.2.2
No active users on the systems

**Description**
We see an intermittent exception in the UI.

When browsing to a dataset, the exception sometimes pops up.
Upon refreshing the page right after, the exception is gone and the dataset is shown immediately.

This is printed in the UI:
```
Exception while fetching data (/dataset/downstreamLineage) : java.lang.RuntimeException: Failed to retrieve entities of type DownstreamEntityRelationships Exception while fetching data (/dataset/upstreamLineage) : java.lang.RuntimeException: Failed to retrieve entities of type UpstreamEntityRelationships
```
<img width="829" alt="Screenshot 2021-05-21 at 09 39 47" src="https://user-images.githubusercontent.com/101401/119160156-4015f000-ba58-11eb-9148-144eaddf535e.png">


The exception originates from GMS, that it suddenly can’t connect to Neo4j.
```
Response status 500, serviceErrorMessage: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database failed
```

GMS log:
```
WARNING: [0xf13cc4a2][bolt-318471] Fatal error occurred in the pipeline
```

Frontend exception:
```
    Exception while fetching data (/dataset/downstreamLineage) : java.lang.RuntimeException: Failed to retrieve entities of type DownstreamEntityRelationships","context":"default","exception":"java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to retrieve entities of type DownstreamEntityRelationships
      at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
      at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
      at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
      at java.lang.Thread.run(Thread.java:748)
    Caused by: java.lang.RuntimeException: Failed to retrieve entities of type DownstreamEntityRelationships
      at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$59(GmsGraphQLEngine.java:459)
      at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
      ... 1 common frames omitted
    Caused by: java.lang.RuntimeException: Failed to batch load Datasets
      at com.linkedin.datahub.graphql.types.lineage.DownstreamLineageType.batchLoad(DownstreamLineageType.java:43)
      at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$59(GmsGraphQLEngine.java:457)
      ... 2 common frames omitted
    Caused by: java.lang.RuntimeException: Failed to batch load DownstreamLineage for entity urn:li:dataset:(<removed>)
      at com.linkedin.datahub.graphql.types.lineage.DownstreamLineageType.lambda$batchLoad$0(DownstreamLineageType.java:39)
      at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
      at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
      at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
      at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
      at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
      at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
      at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
      at com.linkedin.datahub.graphql.types.lineage.DownstreamLineageType.batchLoad(DownstreamLineageType.java:41)
      ... 3 common frames omitted
    Caused by: com.linkedin.restli.client.RestLiResponseException: com.linkedin.restli.client.RestLiResponseException: Response status 500, serviceErrorMessage: org.neo4j.driver.exceptions.ServiceUnavailableException: Connection to the database failed
      at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:130)
      at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
      at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponse(ResponseFutureImpl.java:94)
      at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseEntity(ResponseFutureImpl.java:173)
      at com.linkedin.lineage.client.Lineages.getLineage(Lineages.java:33)
      at com.linkedin.datahub.graphql.types.lineage.DownstreamLineageType.lambda$batchLoad$0(DownstreamLineageType.java:36)
      ... 11 common frames omitted
    Caused by: com.linkedin.restli.client.RestLiResponseException: RestException{_response=RestResponse[headers={Connection=keep-alive, content-length=13096, Date=Wed, 12 May 2021 12:35:21 GMT, server=envoy, x-envoy-upstream-service-time=92, x-restli-error-response=true, x-restli-protocol-version=2.0.0},cookies=[],status=500,entityLength=13096]}
      at com.linkedin.restli.internal.client.ExceptionUtil.exceptionForThrowable(ExceptionUtil.java:102)
      at com.linkedin.restli.client.RestLiCallbackAdapter.convertError(RestLiCallbackAdapter.java:66)
      at com.linkedin.common.callback.CallbackAdapter.onError(CallbackAdapter.java:86)
      at com.linkedin.r2.message.timing.TimingCallback.onError(TimingCallback.java:81)
      at com.linkedin.r2.transport.common.bridge.client.TransportCallbackAdapter.onResponse(TransportCallbackAdapter.java:47)
      at com.linkedin.r2.filter.transport.FilterChainClient.lambda$createWrappedClientTimingCallback$0(FilterChainClient.java:113)
      at com.linkedin.r2.filter.transport.ResponseFilter.onRestError(ResponseFilter.java:79)
      at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
      at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
      at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
      at com.linkedin.r2.filter.message.rest.RestFilter.onRestError(RestFilter.java:84)
      at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
      at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
      at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
      at com.linkedin.r2.filter.message.rest.RestFilter.onRestError(RestFilter.java:84)
      at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
      at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
      at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
      at com.linkedin.r2.filter.message.rest.RestFilter.onRestError(RestFilter.java:84)
      at com.linkedin.r2.filter.TimedRestFilter.onRestError(TimedRestFilter.java:92)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:166)
      at com.linkedin.r2.filter.FilterChainIterator$FilterChainRestIterator.doOnError(FilterChainIterator.java:132)
      at com.linkedin.r2.filter.FilterChainIterator.onError(FilterChainIterator.java:101)
      at com.linkedin.r2.filter.TimedNextFilter.onError(TimedNextFilter.java:48)
      at com.linkedin.r2.filter.transport.ClientRequestFilter.lambda$createCallback$0(ClientRequestFilter.java:102)
      at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:82)
      at com.linkedin.r2.transport.http.client.rest.ExecutionCallback.lambda$onResponse$0(ExecutionCallback.java:64)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
      ... 1 common frames omitted
    Caused by: com.linkedin.r2.message.rest.RestException: Received error 500 from server for URI https://<removed>:443/lineage
      at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:76)
      ... 4 common frames omitted
```

**Comment by RickardCardell** [comment]
We've located the root cause. Our Neo4j instance has a load balancer in front. The LB had an idle timeout of 350s, which reset all connections living for more than 350s, causing a "connection reset by peer" error in GMS.

Setting [MaxConnectionLifetime](https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/Config.ConfigBuilder.html#withMaxConnectionLifetime-long-java.util.concurrent.TimeUnit-) to less than 350s solved the issue. Another option was to set [ConnectionLivenessCheckTimeout](https://neo4j.com/docs/api/java-driver/current/org/neo4j/driver/Config.ConfigBuilder.html#withConnectionLivenessCheckTimeout-long-java.util.concurrent.TimeUnit-) to a low enough value.

The configuration parameters in GMS and other components connecting to Neo4j will be: 
`NEO4j_MAX_CONNECTION_LIFETIME_IN_SECONDS` 
`NEO4J_CONNECTION_LIVENESS_CHECK_TIMEOUT_IN_SECONDS`
