### ISSUE TITLE
Standalone GraphQL Service doesn't support mutate operations / missing authenticated user

### ISSUE THREAD

**Issue by zirx** [datahub-project/datahub#2679]
**Describe the bug**
Standalone GraphQL `datahub-gms-graphql-service` doesn't support mutate operations, because such operations cannot resolve an authenticated `actor` in `update` methods:
```java
    public Tag update(@Nonnull TagUpdate input, @Nonnull QueryContext context) throws Exception {
        // TODO: Verify that updater is owner.
        final CorpuserUrn actor = CorpuserUrn.createFromString(context.getActor());
```
`contex.getActor()` here returns `GmsGraphQLApp` which is not a valid user URN.

**To Reproduce**
1. Checkout the repo to tag `v0.8.1`
2. Set up DATAHUB version: `export DATAHUB_VERSION=v0.8.1` 
3. Spin up all components using `./docker/quickstart.sh`
4. Load sample data `./docker/ingestion/ingestion.sh` with `export DATAHUB_VERSION=v0.8.1`
5. Start GraphQL as an independent service with `export DATAHUB_VERSION=v0.8.1` as `docker-compose -p datahub -f docker-compose.yml -f docker-compose.override.yml -f docker-compose.dev.yml -f docker-compose.graphql-service.yml up --no-deps datahub-gms-graphql-service`
6. Make a simple mutation request from GraphiQL to create a new tag:
```graphql
mutation updateTag($input: TagUpdate!) {
  updateTag(input: $input) {
    urn
    name
    description
  }
}
```
with variables
```graphql
{
  "input": {
  "urn": "urn:li:tag:TEST",
  "name": "TEST",
  "description": "This is a TEST tag"
}}
```

7. See error in `graphql-service` 
```java
datahub-gms-graphql-service    | 2021-06-11 10:53:44.752  WARN 14 --- [onPool-worker-5] n.g.e.SimpleDataFetcherExceptionHandler  : Exception while fetching data (/updateTag) : java.lang.RuntimeException: Failed to perform update against input com.linkedin.datahub.graphql.generated.TagUpdate@638ca822
datahub-gms-graphql-service    |
datahub-gms-graphql-service    | java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to perform update against input com.linkedin.datahub.graphql.generated.TagUpdate@638ca822
datahub-gms-graphql-service    | 	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1592) [na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1582) [na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) ~[na:1.8.0_212]
datahub-gms-graphql-service    | 	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[na:1.8.0_212]
datahub-gms-graphql-service    | Caused by: java.lang.RuntimeException: Failed to perform update against input com.linkedin.datahub.graphql.generated.TagUpdate@638ca822
datahub-gms-graphql-service    | 	at com.linkedin.datahub.graphql.resolvers.mutate.MutableTypeResolver.lambda$get$0(MutableTypeResolver.java:32) ~[datahub-graphql-core.jar!/:na]
datahub-gms-graphql-service    | 	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590) [na:1.8.0_212]
datahub-gms-graphql-service    | 	... 5 common frames omitted
datahub-gms-graphql-service    | Caused by: java.net.URISyntaxException: Urn doesn't start with 'urn:'. Urn: GmsGraphQLApp at index 0: GmsGraphQLApp
datahub-gms-graphql-service    | 	at com.linkedin.common.urn.Urn.<init>(Urn.java:80) ~[core-models-data-template-0.2.49.jar!/:na]
datahub-gms-graphql-service    | 	at com.linkedin.common.urn.Urn.createFromString(Urn.java:231) ~[core-models-data-template-0.2.49.jar!/:na]
datahub-gms-graphql-service    | 	at com.linkedin.common.urn.CorpuserUrn.createFromString(CorpuserUrn.java:27) ~[li-utils-data-template.jar!/:na]
datahub-gms-graphql-service    | 	at com.linkedin.datahub.graphql.types.tag.TagType.update(TagType.java:125) ~[datahub-graphql-core.jar!/:na]
datahub-gms-graphql-service    | 	at com.linkedin.datahub.graphql.types.tag.TagType.update(TagType.java:49) ~[datahub-graphql-core.jar!/:na]
datahub-gms-graphql-service    | 	at com.linkedin.datahub.graphql.resolvers.mutate.MutableTypeResolver.lambda$get$0(MutableTypeResolver.java:30) ~[datahub-graphql-core.jar!/:na]
```

**Expected behavior**
It should be possible to create tags using `graphql-service`. `Actor` user should be set as an optional parameter of GraphQL query, or it should be provided in configuration of `datahub-gms-graphql-service`. UI has authenticated user which is correctly resolved from `context.getActor()`

**Screenshots**
Sample request from GraphiQL UI:
![image](https://user-images.githubusercontent.com/1185278/121676867-740f8e80-cab5-11eb-914c-f28897075306.png)
Stacktrace from graphql-service:
![image](https://user-images.githubusercontent.com/1185278/121676998-9acdc500-cab5-11eb-8df5-b0ad823cc5e2.png) 
An ugly way to make it working:
![image](https://user-images.githubusercontent.com/1185278/121677248-eaac8c00-cab5-11eb-846d-5ec0a6a3e6ac.png)

**Desktop (please complete the following information):**
 - OS: MacOS BigSur
 - Browser (No browser)
 - Version v0.8.1

**Additional context**
An ugly way to make it working:
```bash
diff --git a/datahub-gms-graphql-service/src/main/java/com/linkedin/datahub/graphql/service/QueryGraphQLInvocation.java b/datahub-gms-graphql-service/src/main/java/com/linkedin/datahub/graphql/service/QueryGraphQLInvocation.java
index eb86d42bb..00a8efc3d 100644
--- a/datahub-gms-graphql-service/src/main/java/com/linkedin/datahub/graphql/service/QueryGraphQLInvocation.java
+++ b/datahub-gms-graphql-service/src/main/java/com/linkedin/datahub/graphql/service/QueryGraphQLInvocation.java
@@ -22,7 +22,7 @@ public class QueryGraphQLInvocation implements GraphQLInvocation {
     @Autowired
     GraphQLEngine graphQLEngine;

-    public static final String APPNAME = "GmsGraphQLApp";
+    public static final String APPNAME = "urn:li:corpuser:admin";

     @Override
     public CompletableFuture<ExecutionResult> invoke(GraphQLInvocationData invocationData, WebRequest webRequest) {
```

**Comment by jjoyce0510** [comment]
Hi @zirx.

First of all, totally agree this needs to be addressed. The expectation is that once RBAC is implemented at the GMS layer, one will be able to provide an Authorization header to the standalone GraphQL service which will be a) validated using a public key provided by GMS and b) propagated downstream to GMS (which will actually enforce the authorization piece). 

Is this something you can wait for? We are targeting end of July for the implementation. In the meantime, you could employ an approach like that suggested above^, or alternatively parse & trust the value provided by a special header (say, an "Actor" header) provided to the standalone GQL server.

Thank you for the amazing detail and feedback!

**Comment by anshbansal** [comment]
Closing due to inactivity. Please open new issue if issue persists with latest releases and updated docs.
