### ISSUE TITLE
You can't have commas in search term

### ISSUE THREAD

**Issue by karoliskascenas** [datahub-project/datahub#3776]
**Describe the bug**
If you have a comma in your search term you get `An unknown error occurred.` in the UI.

**To Reproduce**
1.  Quickstart v0.8.19.
2. Type `something, something` in the search bar and hit enter.

**Expected behavior**
I expect the search to work.

**Screenshots**
![image](https://user-images.githubusercontent.com/26895203/146764203-5a904028-2112-4195-b123-7d21affe8984.png)

**Desktop (please complete the following information):**
 - OS: mac
 - Browser: Chrome
 - Version: Version 96.0.4664.110 (Official Build) (x86_64) 

**Additional context**
GMS container logs:
```07:32:24.009 [ForkJoinPool.commonPool-worker-0] INFO  c.l.m.s.a.AllEntitiesSearchAggregator:68 - Searching Search documents across entities: [dataset, dashboard, chart, mlModel, mlModelGroup, mlFeatureTable, dataFlow, dataJob, glossaryTerm, tag, corpuser, corpGroup], input: [something,  something], postFilters: {or=[{and=[]}]}, sortCriterion: null, from: 0, size: 100
07:32:24.033 [ForkJoinPool.commonPool-worker-1] ERROR c.l.m.s.e.query.ESSearchDAO:61 - Search query failed
org.elasticsearch.ElasticsearchStatusException: Elasticsearch exception [type=search_phase_execution_exception, reason=all shards failed]
	at org.elasticsearch.rest.BytesRestResponse.errorFromXContent(BytesRestResponse.java:187)
	at org.elasticsearch.client.RestHighLevelClient.parseEntity(RestHighLevelClient.java:1892)
	at org.elasticsearch.client.RestHighLevelClient.parseResponseException(RestHighLevelClient.java:1869)
	at org.elasticsearch.client.RestHighLevelClient.internalPerformRequest(RestHighLevelClient.java:1626)
	at org.elasticsearch.client.RestHighLevelClient.performRequest(RestHighLevelClient.java:1583)
	at org.elasticsearch.client.RestHighLevelClient.performRequestAndParseEntity(RestHighLevelClient.java:1553)
	at org.elasticsearch.client.RestHighLevelClient.search(RestHighLevelClient.java:1069)
	at com.linkedin.metadata.search.elasticsearch.query.ESSearchDAO.executeAndExtract(ESSearchDAO.java:57)
	at com.linkedin.metadata.search.elasticsearch.query.ESSearchDAO.search(ESSearchDAO.java:89)
	at com.linkedin.metadata.search.elasticsearch.ElasticSearchService.search(ElasticSearchService.java:66)
	at com.linkedin.metadata.search.cache.EntitySearchServiceCache.lambda$getSearcher$0(EntitySearchServiceCache.java:24)
	at com.linkedin.metadata.search.cache.CacheableSearcher.getBatch(CacheableSearcher.java:82)
	at com.linkedin.metadata.search.cache.CacheableSearcher.getSearchResults(CacheableSearcher.java:47)
	at com.linkedin.metadata.search.aggregator.AllEntitiesSearchAggregator.lambda$getSearchResultsForEachEntity$2(AllEntitiesSearchAggregator.java:148)
	at com.linkedin.metadata.utils.ConcurrencyUtils.lambda$null$0(ConcurrencyUtils.java:21)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
	Suppressed: org.elasticsearch.client.ResponseException: method [POST], host [http://elasticsearch:9200], URI [/corpuserindex_v2/_search?typed_keys=true&max_concurrent_shard_requests=5&ignore_unavailable=false&expand_wildcards=open&allow_no_indices=true&ignore_throttled=true&search_type=query_then_fetch&batched_reduce_size=512&ccs_minimize_roundtrips=true], status line [HTTP/1.1 400 Bad Request]
{"error":{"root_cause":[{"type":"query_shard_exception","reason":"Failed to parse query [[something,  something]]","index_uuid":"DB2XSrTFS32-siTGTAbHaQ","index":"corpuserindex_v2"}],"type":"search_phase_execution_exception","reason":"all shards failed","phase":"query","grouped":true,"failed_shards":[{"shard":0,"index":"corpuserindex_v2","node":"ff0VRcDfTY-Nkot3gazphg","reason":{"type":"query_shard_exception","reason":"Failed to parse query [[something,  something]]","index_uuid":"DB2XSrTFS32-siTGTAbHaQ","index":"corpuserindex_v2","caused_by":{"type":"parse_exception","reason":"Cannot parse '[something,  something]': Encountered \" <RANGE_GOOP> \"something \"\" at line 1, column 13.\nWas expecting:\n    \"TO\" ...\n    ","caused_by":{"type":"parse_exception","reason":"Encountered \" <RANGE_GOOP> \"something \"\" at line 1, column 13.\nWas expecting:\n    \"TO\" ...\n    "}}}}]},"status":400}
		at ```

**Comment by maggiehays** [comment]
Thanks for reporting, @karoliskascenas! We have a smaller team on hand during the holidays, but we'll take a look into this ASAP.

**Comment by MikeSchlosser16** [comment]
We also see similar behavior with `-`. It may be related.

**Comment by dexter-mh-lee** [comment]
Hi. We have fixed the issue with this PR! https://github.com/datahub-project/datahub/pull/4570 Will be included in next release
