### ISSUE TITLE
Cannot build docker image on EC2

### ISSUE THREAD

**Issue by AlanZhang95** [datahub-project/datahub#4434]
**Describe the bug**
I have successfully built docker image at my local device. However, Building it on EC2 Linux instance will always report the following error:
~~~
Building datahub-frontend-react
[+] Building 132.0s (12/15)
 => [internal] load build definition from Dockerfile                                                                                      0.0s
 => => transferring dockerfile: 1.94kB                                                                                                    0.0s
 => [internal] load .dockerignore                                                                                                         0.0s
 => => transferring context: 35B                                                                                                          0.0s
 => [internal] load metadata for docker.io/library/node:16.13.0-alpine3.14                                                                0.9s
 => [internal] load metadata for docker.io/library/alpine:3.14                                                                            0.6s
 => [prod-build 1/4] FROM docker.io/library/node:16.13.0-alpine3.14@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0e  2.6s
 => => resolve docker.io/library/node:16.13.0-alpine3.14@sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b          0.0s
 => => sha256:784cd1fd612b7ef9870aa1d85ca7285010993bc089f1a00ae1dcd6644074a398 34.81MB / 34.81MB                                          0.8s
 => => sha256:0ec5d186b713b05c9f9ebb40df5c7c3f3b67133a2effbf3e3215756220136363 2.35MB / 2.35MB                                            0.3s
 => => sha256:98dc27ad6276f18e415689e0d39332e7cac56ed95b678093f61193bb0bd9db01 451B / 451B                                                0.3s
 => => sha256:60ef0bed1dc2ec835cfe3c4226d074fdfaba571fd619c280474cc04e93f0ec5b 1.43kB / 1.43kB                                            0.0s
 => => sha256:5277c7d171e02ee76417bb290ef488aa80e4e64572119eec0cb9fffbcffb8f6a 1.16kB / 1.16kB                                            0.0s
 => => sha256:44e24535dfbf4b537a7ac13e92c524712c3226af52c0e1037eba7415c16a5828 6.53kB / 6.53kB                                            0.0s
 => => extracting sha256:784cd1fd612b7ef9870aa1d85ca7285010993bc089f1a00ae1dcd6644074a398                                                 1.4s
 => => extracting sha256:0ec5d186b713b05c9f9ebb40df5c7c3f3b67133a2effbf3e3215756220136363                                                 0.1s
 => => extracting sha256:98dc27ad6276f18e415689e0d39332e7cac56ed95b678093f61193bb0bd9db01                                                 0.0s
 => CACHED [base 1/3] FROM docker.io/library/alpine:3.14@sha256:635f0aa53d99017b38d1a0aa5b2082f7812b03e3cdb299103fe77b5c8a07f1d2          0.0s
 => [internal] load build context                                                                                                         0.3s
 => => transferring context: 379.86kB                                                                                                     0.3s
 => [base 2/3] RUN addgroup -S datahub && adduser -S datahub -G datahub                                                                   0.7s
 => [base 3/3] RUN apk --no-cache --update-cache --available upgrade     && apk --no-cache add curl openjdk8-jre                          6.0s
 => [prod-build 2/4] RUN apk --no-cache --update-cache --available upgrade     && apk --no-cache add perl openjdk8                        4.9s
 => [prod-build 3/4] COPY . datahub-src                                                                                                   4.4s
 => ERROR [prod-build 4/4] RUN cd datahub-src && ./gradlew :datahub-frontend:dist -PenableEmber=false -PuseSystemNode=true -x test -x   119.1s
------
 > [prod-build 4/4] RUN cd datahub-src && ./gradlew :datahub-frontend:dist -PenableEmber=false -PuseSystemNode=true -x test -x yarnTest -x yarnLint     && cp datahub-frontend/build/distributions/datahub-frontend.zip ../datahub-frontend.zip     && cd .. && rm -rf datahub-src && unzip datahub-frontend.zip:
#12 0.508 Downloading https://services.gradle.org/distributions/gradle-6.9.2-bin.zip
#12 1.480 ......................................................................................................
#12 3.807
#12 3.808 Welcome to Gradle 6.9.2!
#12 3.809
#12 3.809 Here are the highlights of this release:
#12 3.809  - This is a small backport release.
#12 3.810  - Java 16 can be used to compile when used with Java toolchains
#12 3.810  - Dynamic versions can be used within plugin declarations
#12 3.811  - Native support for Apple Silicon processors
#12 3.811
#12 3.812 For more details see https://docs.gradle.org/6.9.2/release-notes.html
#12 3.812
#12 6.706 Configuration on demand is an incubating feature.
#12 55.81
#12 55.81 > Configure project :metadata-integration:java:datahub-client
#12 55.81 In else section
#12 58.31
#12 58.31 > Configure project :metadata-integration:java:spark-lineage
#12 58.31 In else section
#12 105.9 SLF4J: Failed to load class "org.slf4j.impl.StaticLoggerBinder".
#12 105.9 SLF4J: Defaulting to no-operation (NOP) logger implementation
#12 105.9 SLF4J: See http://www.slf4j.org/codes.html#StaticLoggerBinder for further details.
#12 106.6
#12 106.6 > Task :datahub-web-react:nodeSetup SKIPPED
#12 107.5
#12 107.5 > Task :datahub-web-react:yarnSetup
#12 107.5
#12 107.5 added 1 package, and audited 2 packages in 548ms
#12 107.5
#12 107.5 found 0 vulnerabilities
#12 109.5
#12 109.5 > Task :datahub-web-react:yarnInstall
#12 109.5 yarn install v1.22.15
#12 109.5 [1/4] Resolving packages...
#12 109.5 [2/4] Fetching packages...
#12 116.2
#12 116.2 > Task :datahub-web-react:yarnInstall FAILED
#12 117.0 > Task :datahub-frontend:compilePlayBinaryPlayRoutes
#12 117.0
#12 117.0 FAILURE: Build failed with an exception.
#12 117.0
#12 117.0 * What went wrong:
#12 117.0 Execution failed for task ':datahub-web-react:yarnInstall'.
#12 117.0 > Process 'command 'yarn'' finished with non-zero exit value 131
#12 117.0
#12 117.0 * Try:
#12 117.0 Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
#12 117.0
#12 117.0 * Get more help at https://help.gradle.org
#12 117.0
#12 117.0
#12 117.0 BUILD FAILED in 1m 56s
#12 117.0 Deprecated Gradle features were used in this build, making it incompatible with Gradle 7.0.
#12 117.0 Use '--warning-mode all' to show the individual deprecation warnings.
#12 117.0 See https://docs.gradle.org/6.9.2/userguide/command_line_interface.html#sec:command_line_warnings
#12 117.0 3 actionable tasks: 3 executed
------
executor failed running [/bin/sh -c cd datahub-src && ./gradlew :datahub-frontend:dist -PenableEmber=${ENABLE_EMBER} -PuseSystemNode=${USE_SYSTEM_NODE} -x test -x yarnTest -x yarnLint     && cp datahub-frontend/build/distributions/datahub-frontend.zip ../datahub-frontend.zip     && cd .. && rm -rf datahub-src && unzip datahub-frontend.zip]: exit code: 1
ERROR: Service 'datahub-frontend-react' failed to build : Build failed
~~~

**To Reproduce**
After clone the repo. go to /datahub/docker, and run `COMPOSE_DOCKER_CLI_BUILD=1 DOCKER_BUILDKIT=1 docker-compose build`

**Expected behavior**
What should I do to unblock the deployment on EC2?

**Desktop (please complete the following information):**
 - OS: Amazon Linux 2

**Comment by jakeberesford-palmetto** [comment]
I'm running into the same error with yarn when trying to build locally.

**Comment by Dweny** [comment]
get the same error through a local build

**Comment by maggiehays** [comment]
@pedro93 please take a look!

**Comment by keerthiis** [comment]
Facing the same issue when executing on ec2 instance.

**Comment by AlanZhang95** [comment]
I bypassed the issue by building all the images at local, uploading them to the EC2, and use docker-compose to up all images at the same time.

**Comment by sybernatus** [comment]
I don't know if it's related but I have a similar issue with nx command through yarn and the DOCKER_BUILDKIT=1 environment variable.
The image is built correctly without Docker build kit.

```
[+] Building 7.3s (11/13)                                                                                                                                                                                  
 => [internal] load build definition from Dockerfile                                                                                                                                                  0.0s
 => => transferring dockerfile: 32B                                                                                                                                                                   0.0s
 => [internal] load .dockerignore                                                                                                                                                                     0.1s
 => => transferring context: 34B                                                                                                                                                                      0.0s
 => [internal] load metadata for registry.gitlab.com/home-pi-1/kredul/nginx:latest                                                                                                                    0.0s
 => [internal] load metadata for registry.gitlab.com/home-pi-1/kredul/node-dependencies-prod:latest                                                                                                   0.0s
 => [builder 1/4] FROM registry.gitlab.com/home-pi-1/kredul/node-dependencies-prod:latest                                                                                                             0.0s
 => CACHED [runner 1/4] FROM registry.gitlab.com/home-pi-1/kredul/nginx:latest                                                                                                                        0.0s
 => [internal] load build context                                                                                                                                                                     0.4s
 => => transferring context: 89.83kB                                                                                                                                                                  0.3s
 => CACHED [builder 2/4] WORKDIR /build                                                                                                                                                               0.0s
 => [runner 2/4] RUN rm -rf /usr/share/nginx/html/*                                                                                                                                                   2.0s
 => [builder 3/4] COPY . .                                                                                                                                                                            1.7s
 => ERROR [builder 4/4] RUN yarn run kurriculum:build:prod                                                                                                                                            4.9s
------                                                                                                                                                                                                     
 > [builder 4/4] RUN yarn run kurriculum:build:prod:                                                                                                                                                       
#11 1.332 yarn run v1.22.15                                                                                                                                                                                
#11 1.478 $ nx run kurriculum:build:production                                                                                                                                                             
#11 4.513 nx run [project][:target][:configuration] [_..]                                                                                                                                                  
#11 4.513                                                                                                                                                                                                  
#11 4.513 Run a target for a project
#11 4.513     (e.g., nx run myapp:serve:production).
#11 4.513 
#11 4.513     You can also use the infix notation to run a target:
#11 4.513     (e.g., nx serve myapp --configuration=production)
#11 4.513 
#11 4.513     You can skip the use of Nx cache by using the --skip-nx-cache option.
#11 4.513 
#11 4.513 Options:
#11 4.513       --version        Show version number  [boolean]
#11 4.513       --prod           Use the production configuration  [boolean] [default: false]
#11 4.513   -c, --configuration  Target configuration  [string]
#11 4.513       --project        Target project  [string]
#11 4.513 
#11 4.520 Error: Unable to connect to the daemon process.
#11 4.520 Messages from the log:
#11 4.520 [NX Daemon Server] - 2022-05-03T19:59:16.891Z - Started listening on: /build/node_modules/.cache/nx/d/d.sock
#11 4.520 
#11 4.520  >  NX   No native build was found for platform=linux arch=arm64 runtime=node abi=102 uv=1 armv=8 libc=musl node=17.1.0
#11 4.520     loaded from: /build/node_modules/nx/node_modules/@parcel/watcher
#11 4.520 
#11 4.520 
#11 4.520 
#11 4.520 
#11 4.520 
#11 4.520 More information: /build/node_modules/.cache/nx/d/daemon.log
#11 4.520     at daemonProcessException (/build/node_modules/nx/src/daemon/client/client.js:64:16)
#11 4.520     at Socket.<anonymous> (/build/node_modules/nx/src/daemon/client/client.js:152:29)
#11 4.520     at Socket.emit (node:events:390:28)
#11 4.520     at emitErrorNT (node:internal/streams/destroy:164:8)
#11 4.520     at emitErrorCloseNT (node:internal/streams/destroy:129:3)
#11 4.520     at processTicksAndRejections (node:internal/process/task_queues:83:21)
#11 4.568 error Command failed with exit code 1.
#11 4.568 info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
------
executor failed running [/bin/sh -c yarn run kurriculum:build:prod]: exit code: 1
```

Did you try without the Docker build kit activated?
