### ISSUE TITLE
java.lang.IllegalArgumentException: No enum constant com.linkedin.datahub.graphql.generated.FabricType.PRE

### ISSUE THREAD

**Issue by eeepmb** [datahub-project/datahub#4530]
Hi there,
when running [this example](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/examples/library/dataset_schema.py#L20) with `env="PRE"` datahub-gms runs into the error below. Whenever going to a new site on the frontend a message appears displaying `500 - internal server error`.

According to [this document](https://raw.githubusercontent.com/linkedin/datahub/master/li-utils/src/main/pegasus/com/linkedin/common/FabricType.pdl) `PRE` should be a valid env/fabric. I also tested the example with `env="TEST"` and `env="CORP"` which worked as expected. 

* DatahHub v0.8.31
* acryl-datahub v0.8.31

```
08:27:10.570 [ForkJoinPool.commonPool-worker-15] ERROR c.l.datahub.graphql.GmsGraphQLEngine:1241 - Failed to load Entities of type: Dataset, keys: [urn:li:dataset:(urn:li:dataPlatform:hive,realestate_db.sales,PRE)] Failed to batch load Datasets
08:27:10.570 [ForkJoinPool.commonPool-worker-15] ERROR c.l.d.g.e.DataHubDataFetcherExceptionHandler:21 - Failed to execute DataFetcher
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to retrieve entities of type Dataset
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.lang.RuntimeException: Failed to retrieve entities of type Dataset
	at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$138(GmsGraphQLEngine.java:1242)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 common frames omitted
Caused by: java.lang.RuntimeException: Failed to batch load Datasets
	at com.linkedin.datahub.graphql.types.dataset.DatasetType.batchLoad(DatasetType.java:125)
	at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$138(GmsGraphQLEngine.java:1239)
	... 6 common frames omitted
Caused by: java.lang.IllegalArgumentException: No enum constant com.linkedin.datahub.graphql.generated.FabricType.PRE
	at java.lang.Enum.valueOf(Enum.java:238)
	at com.linkedin.datahub.graphql.generated.FabricType.valueOf(FabricType.java:8)
	at com.linkedin.datahub.graphql.types.dataset.mappers.DatasetMapper.mapDatasetKey(DatasetMapper.java:94)
	at com.linkedin.datahub.graphql.types.common.mappers.util.MappingHelper.mapToResult(MappingHelper.java:22)
	at com.linkedin.datahub.graphql.types.dataset.mappers.DatasetMapper.apply(DatasetMapper.java:64)
	at com.linkedin.datahub.graphql.types.dataset.mappers.DatasetMapper.map(DatasetMapper.java:53)
	at com.linkedin.datahub.graphql.types.dataset.DatasetType.lambda$batchLoad$0(DatasetType.java:121)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1384)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at com.linkedin.datahub.graphql.types.dataset.DatasetType.batchLoad(DatasetType.java:123)
	... 7 common frames omitted
08:27:10.571 [ForkJoinPool.commonPool-worker-22] ERROR c.datahub.graphql.GraphQLController:93 - Errors while executing graphQL query: "query getBrowseResults($input: BrowseInput!) {\n  browse(input: $input) {\n    entities {\n      urn\n      type\n      ... on Dataset {\n        name\n        origin\n        properties {\n          name\n          description\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        subTypes {\n          typeNames\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on Dashboard {\n        urn\n        type\n        tool\n        dashboardId\n        properties {\n          name\n          description\n          externalUrl\n          access\n          lastModified {\n            time\n            __typename\n          }\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on GlossaryTerm {\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        properties {\n          name\n          description\n          definition\n          termSource\n          sourceRef\n          sourceUrl\n          customProperties {\n            key\n            value\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      ... on Chart {\n        urn\n        type\n        tool\n        chartId\n        properties {\n          name\n          description\n          externalUrl\n          type\n          access\n          lastModified {\n            time\n            __typename\n          }\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on DataFlow {\n        urn\n        type\n        orchestrator\n        flowId\n        cluster\n        properties {\n          name\n          description\n          project\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on MLFeatureTable {\n        urn\n        type\n        name\n        description\n        featureTableProperties {\n          description\n          mlFeatures {\n            urn\n            __typename\n          }\n          mlPrimaryKeys {\n            urn\n            __typename\n          }\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        __typename\n      }\n      ... on MLModel {\n        name\n        origin\n        description\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        __typename\n      }\n      ... on MLModelGroup {\n        name\n        origin\n        description\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    groups {\n      name\n      count\n      __typename\n    }\n    start\n    count\n    total\n    metadata {\n      path\n      totalNumEntities\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment platformFields on DataPlatform {\n  urn\n  type\n  name\n  properties {\n    type\n    displayName\n    datasetNameDelimiter\n    logoUrl\n    __typename\n  }\n  displayName\n  info {\n    type\n    displayName\n    datasetNameDelimiter\n    logoUrl\n    __typename\n  }\n  __typename\n}\n\nfragment ownershipFields on Ownership {\n  owners {\n    owner {\n      ... on CorpUser {\n        urn\n        type\n        username\n        info {\n          active\n          displayName\n          title\n          email\n          firstName\n          lastName\n          fullName\n          __typename\n        }\n        properties {\n          active\n          displayName\n          title\n          email\n          firstName\n          lastName\n          fullName\n          __typename\n        }\n        editableProperties {\n          displayName\n          title\n          pictureLink\n          email\n          __typename\n        }\n        __typename\n      }\n      ... on CorpGroup {\n        urn\n        type\n        name\n        properties {\n          displayName\n          email\n          __typename\n        }\n        info {\n          displayName\n          email\n          admins {\n            urn\n            username\n            info {\n              active\n              displayName\n              title\n              email\n              firstName\n              lastName\n              fullName\n              __typename\n            }\n            editableInfo {\n              pictureLink\n              teams\n              skills\n              __typename\n            }\n            __typename\n          }\n          members {\n            urn\n            username\n            info {\n              active\n              displayName\n              title\n              email\n              firstName\n              lastName\n              fullName\n              __typename\n            }\n            editableInfo {\n              pictureLink\n              teams\n              skills\n              __typename\n            }\n            __typename\n          }\n          groups\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    type\n    __typename\n  }\n  lastModified {\n    time\n    __typename\n  }\n  __typename\n}\n\nfragment globalTagsFields on GlobalTags {\n  tags {\n    tag {\n      urn\n      name\n      description\n      properties {\n        colorHex\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment glossaryTerms on GlossaryTerms {\n  terms {\n    term {\n      urn\n      name\n      properties {\n        name\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment entityDomain on Domain {\n  urn\n  properties {\n    name\n    __typename\n  }\n  __typename\n}\n", result: {errors=[{message=An unknown error occurred., locations=[{line=3, column=5}], path=[browse, entities], extensions={code=500, type=SERVER_ERROR, classification=DataFetchingException}}], data={browse=null}}, errors: [DataHubGraphQLError{path=[browse, entities], code=SERVER_ERROR, locations=[SourceLocation{line=3, column=5}]}]

```

**Comment by eeepmb** [comment]
Hi @pawel3275 ,
not a real fix but we use another env ad interim.
