### ISSUE TITLE
Error importing DAGs with params from airflow to Datahub

### ISSUE THREAD

**Issue by edulauer** [datahub-project/datahub#4546]
**Describe the bug**
I've seen that some of my running DAGs from Airflow are not getting imported in Datahub. It looks like this error is caused by when the DAGs is configured with a template of the Param Class (https://airflow.apache.org/docs/apache-airflow/2.2.1/concepts/params.html#:~:text=Params%20are%20Airflow's%20concept%20of,depends%20on%20the%20flag%20core.) I don't know exactly why this error occours, but it could be relate to type of params, which is a dictionary type.
```
**Screenshots**
Here is an example of a DAG definition of ours:
dag = DAG(
    'dag_test',
    default_args=default_args,
    schedule_interval="0 4 15 * *",
    catchup=False,
    description=__doc__,
    params={"reference_date": "YYYY-MM-DD"},
    tags=['pgd', 'datamart', 'datalake']
)

```

And here is the stack trace (task log in airflow), after turned graceful_exceptions to false:
```

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1332, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1461, in _execute_task_with_callbacks
    self.task.post_execute(context=context, result=result)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/lineage/__init__.py", line 124, in wrapper
    _backend.send_lineage(operator=self, inlets=self.inlets, outlets=self.outlets, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/lineage/datahub.py", line 117, in send_lineage
    send_lineage_to_datahub(
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/_lineage_core.py", line 144, in send_lineage_to_datahub
    key: repr(value) for (key, value) in SerializedDAG.serialize_dag(dag).items()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 821, in serialize_dag
    raise SerializationError(f'Failed to serialize DAG {dag.dag_id!r}: {e}')
airflow.exceptions.SerializationError: Failed to serialize DAG 'dag_test': 'str' object has no attribute '__module__'
```
**Expected behavior**
Dags and tasks sucessfully imported in Datahub as a new pipeline

**Version**
 - Airflow: v2.2.1
- Datahub: 0.8.31
- acryl-datahub[airflow]:0.8.31

**Comment by treff7es** [comment]
Can you try to use Can you try to use Param as it is the new style of specifying params? ->
https://airflow.apache.org/docs/apache-airflow/2.2.1/concepts/params.html
Here is an issue, that I think is related at the Airflow GitHub  ->
https://github.com/apache/airflow/issues/21082

**Comment by jjoyce0510** [comment]
@treff7es Can you take another pass?

**Comment by jjudy60334** [comment]
I got the same issues. I tried using Param in the new style ,but it still respond the same error.
it seems like it is similar to those two issues.
- https://github.com/apache/airflow/issues/20875 
- https://github.com/open-metadata/OpenMetadata/issues/2735

```  File "/home/***/.local/lib/python3.8/site-packages/***/serialization/serialized_objects.py", line 830, in serialize_dag
    serialize_dag["tasks"] = [cls._serialize(task) for _, task in dag.task_dict.items()]
  File "/home/***/.local/lib/python3.8/site-packages/***/serialization/serialized_objects.py", line 830, in <listcomp>
    serialize_dag["tasks"] = [cls._serialize(task) for _, task in dag.task_dict.items()]
  File "/home/***/.local/lib/python3.8/site-packages/***/serialization/serialized_objects.py", line 308, in _serialize
    return SerializedBaseOperator.serialize_operator(var)
  File "/home/***/.local/lib/python3.8/site-packages/***/serialization/serialized_objects.py", line 578, in serialize_operator
    serialize_op['params'] = cls._serialize_params_dict(op.params)
  File "/home/***/.local/lib/python3.8/site-packages/***/serialization/serialized_objects.py", line 451, in _serialize_params_dict
    if f'{v.__module__}.{v.__class__.__name__}' == '***.models.param.Param':
AttributeError: 'str' object has no attribute '__module__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/***/plugins/datahub_***/src/datahub_***_plugin/datahub_plugin.py", line 336, in custom_on_success_callback
    datahub_on_success_callback(context)
  File "/opt/***/plugins/datahub_***/src/datahub_***_plugin/datahub_plugin.py", line 197, in datahub_on_success_callback
    dataflow = AirflowGenerator.generate_dataflow(
  File "/opt/***/plugins/datahub_provider_plugin/client/***_generator.py", line 131, in generate_dataflow
    if key not in flow_property_bag:
  File "/home/***/.local/lib/python3.8/site-packages/***/serialization/serialized_objects.py", line 851, in serialize_dag
    raise SerializationError(f'Failed to serialize DAG {dag.dag_id!r}: {e}')
***.exceptions.SerializationError: Failed to serialize DAG 'datahub_lineage_backend_test2': 'str' object has no attribute '__module__'
```

**Version**
Airflow: v2.2.5
Datahub: 0.8.40
acryl-datahub[airflow]:0.8.35.6

**Comment by vchiapaikeo** [comment]
We are also seeing a stack trace that may be similar to this issue on our installation:

```
[2022-07-12, 13:19:54 UTC] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1471, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/taskinstance.py", line 1621, in _execute_task_with_callbacks
    self.task.post_execute(context=context, result=result)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/lineage/__init__.py", line 124, in wrapper
    _backend.send_lineage(operator=self, inlets=self.inlets, outlets=self.outlets, context=context)
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/lineage/datahub.py", line 117, in send_lineage
    send_lineage_to_datahub(
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/_lineage_core.py", line 69, in send_lineage_to_datahub
    datajob = AirflowGenerator.generate_datajob(
  File "/home/airflow/.local/lib/python3.9/site-packages/datahub_provider/client/airflow_generator.py", line 204, in generate_datajob
    for (key, value) in SerializedBaseOperator.serialize_operator(task).items()
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 614, in serialize_operator
    return cls._serialize_node(op, include_deps=op.deps is not BaseOperator.deps)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 643, in _serialize_node
    serialize_op['params'] = cls._serialize_params_dict(op.params)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/serialization/serialized_objects.py", line 500, in _serialize_params_dict
    raise ValueError(
ValueError: Params to a DAG or a Task can be only of type airflow.models.param.Param, but param 'underscored_dag_name' is <class 'str'>
```

```
Version:
Airflow: v2.2.5
Datahub: 0.8.40
acryl-datahub[airflow]:0.8.40
```

Trying params in the new style (and also trying ParamsDict) both failed to resolve the issue. We had to set graceful_exceptions back to true for the tasks to complete.
