### ISSUE TITLE
Failed to execute "./gradlew build"

### ISSUE THREAD

**Issue by hooverhe** [datahub-project/datahub#4655]
When I execute "./gradlew build", I failed. Are you guys facing these errors while building? Why so many errors?

My Dev Env:
Centos 7 or 8. In both of them I can't build successfully in several days.
OpenJDK8U-jdk_x64_linux_hotspot_8u322b06
Docker version 20.10.9, build c2ea9bc
docker-compose version 1.29.2, build 5becea4c
python 3.6.8
pip 21.3.1 from /usr/local/lib/python3.6/site-packages/pip (python 3.6)
git version 2.27.0

2022-04-13T12:02:05.689+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2022-04-13T12:02:05.689+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2022-04-13T12:02:05.689+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2022-04-13T12:02:05.689+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Waiting to acquire shared lock on daemon addresses registry.
2022-04-13T12:02:05.689+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Lock acquired on daemon addresses registry.
2022-04-13T12:02:05.689+0800 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on daemon addresses registry.
2022-04-13T12:02:03.600+0800 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] 
2022-04-13T12:02:03.600+0800 [LIFECYCLE] [class org.gradle.internal.buildevents.TaskExecutionLogger] > Task :datahub-web-react:yarnTest
2022-04-13T12:02:14.909+0800 [ERROR] [system.err] PASS src/app/entity/shared/containers/profile/__tests__/EntityProfile.test.tsx (10.662 s)
2022-04-13T12:02:14.927+0800 [ERROR] [system.err]   ● Console
2022-04-13T12:02:14.927+0800 [ERROR] [system.err] 
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]     console.error
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       Warning: Each child in a list should have a unique "key" prop.
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       Check the render method of `TagTermGroup`. See https://reactjs.org/link/warning-keys for more information.
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at TagTermGroup (/usr/local/datahub/datahub-web-react/src/app/shared/tags/TagTermGroup.tsx:56:5)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at SidebarTagsSection (/usr/local/datahub/datahub-web-react/src/app/entity/shared/containers/profile/sidebar/SidebarTagsSection.tsx:12:38)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at EntitySidebar (/usr/local/datahub/datahub-web-react/src/app/entity/shared/containers/profile/sidebar/EntitySidebar.tsx:22:37)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at Pane (/usr/local/datahub/datahub-web-react/node_modules/react-split-pane/dist/index.cjs.js:166:5)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at SplitPane (/usr/local/datahub/datahub-web-react/node_modules/react-split-pane/dist/index.cjs.js:339:5)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at EntityProfile (/usr/local/datahub/datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx:110:5)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at Router (/usr/local/datahub/datahub-web-react/node_modules/react-router/cjs/react-router.js:99:30)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at MemoryRouter (/usr/local/datahub/datahub-web-react/node_modules/react-router/cjs/react-router.js:187:35)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at Object.<anonymous>.exports.ThemeProvider (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/ServerStyleSheet.js:66:13)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at _default (/usr/local/datahub/datahub-web-react/src/utils/test-utils/TestPageContainer.tsx:45:19)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at ApolloProvider (/usr/local/datahub/datahub-web-react/node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           at MockedProvider (/usr/local/datahub/datahub-web-react/node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err] 
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       170 |
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       171 |     return (
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]     > 172 |         <TagWrapper>
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]           |         ^
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       173 |             {domain && (
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       174 |                 <DomainLink urn={domain.urn} name={entityRegistry.getDisplayName(EntityType.Domain, domain) || ''} />
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       175 |             )}
2022-04-13T12:02:14.928+0800 [ERROR] [system.err] 
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       at console.error (node_modules/@testing-library/react/dist/act-compat.js:55:34)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:117:30)
2022-04-13T12:02:14.928+0800 [ERROR] [system.err]       at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:93:5)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at validateExplicitKey (node_modules/react/cjs/react-jsx-dev-runtime.development.js:986:5)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at validateChildKeys (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1013:11)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1174:15)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at TagTermGroup (src/app/shared/tags/TagTermGroup.tsx:172:9)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at updateFunctionComponent (node_modules/react-dom/cjs/react-dom.development.js:17356:20)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at beginWork (node_modules/react-dom/cjs/react-dom.development.js:19063:16)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at beginWork$1 (node_modules/react-dom/cjs/react-dom.development.js:23940:14)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at performUnitOfWork (node_modules/react-dom/cjs/react-dom.development.js:22779:12)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at workLoopSync (node_modules/react-dom/cjs/react-dom.development.js:22707:5)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       at renderRootSync (node_modules/react-dom/cjs/react-dom.development.js:22670:7)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err] 
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]     console.error
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       Warning: Each child in a list should have a unique "key" prop.
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]       Check the render method of `Body`. See https://reactjs.org/link/warning-keys for more information.
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at BodyRow (/usr/local/datahub/datahub-web-react/node_modules/rc-table/lib/Body/BodyRow.js:33:25)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at Body (/usr/local/datahub/datahub-web-react/node_modules/rc-table/lib/Body/index.js:29:19)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at table
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at /usr/local/datahub/datahub-web-react/node_modules/rc-table/lib/Table.js:112:23
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at Table (/usr/local/datahub/datahub-web-react/node_modules/rc-table/lib/Table.js:127:25)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at Spin (/usr/local/datahub/datahub-web-react/node_modules/antd/lib/spin/index.js:104:37)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at Table (/usr/local/datahub/datahub-web-react/node_modules/antd/lib/table/Table.js:75:34)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at DynamicTabularTab (/usr/local/datahub/datahub-web-react/src/app/entity/shared/tabs/Entity/weaklyTypedAspects/DynamicTabularTab.tsx:10:54)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at DynamicTab (/usr/local/datahub/datahub-web-react/src/app/entity/shared/tabs/Entity/weaklyTypedAspects/DynamicTab.tsx:32:38)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at component
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.929+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at Pane (/usr/local/datahub/datahub-web-react/node_modules/react-split-pane/dist/index.cjs.js:166:5)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at SplitPane (/usr/local/datahub/datahub-web-react/node_modules/react-split-pane/dist/index.cjs.js:339:5)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at div
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at I (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/Keyframes.js:20:51)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at EntityProfile (/usr/local/datahub/datahub-web-react/src/app/entity/shared/containers/profile/EntityProfile.tsx:110:5)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at Router (/usr/local/datahub/datahub-web-react/node_modules/react-router/cjs/react-router.js:99:30)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at MemoryRouter (/usr/local/datahub/datahub-web-react/node_modules/react-router/cjs/react-router.js:187:35)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at Object.<anonymous>.exports.ThemeProvider (/usr/local/datahub/datahub-web-react/node_modules/styled-components/src/models/ServerStyleSheet.js:66:13)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at _default (/usr/local/datahub/datahub-web-react/src/utils/test-utils/TestPageContainer.tsx:45:19)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at ApolloProvider (/usr/local/datahub/datahub-web-react/node_modules/@apollo/client/react/context/ApolloProvider.js:5:21)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]           at MockedProvider (/usr/local/datahub/datahub-web-react/node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err] 
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at printWarning (node_modules/react/cjs/react.development.js:220:30)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at error (node_modules/react/cjs/react.development.js:196:5)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at validateExplicitKey (node_modules/react/cjs/react.development.js:2052:5)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at validateChildKeys (node_modules/react/cjs/react.development.js:2078:9)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at Object.createElementWithValidation [as createElement] (node_modules/react/cjs/react.development.js:2233:7)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at node_modules/rc-table/lib/Body/index.js:91:31
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at mountMemo (node_modules/react-dom/cjs/react-dom.development.js:15846:19)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at Object.useMemo (node_modules/react-dom/cjs/react-dom.development.js:16219:16)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at Object.useMemo (node_modules/react/cjs/react.development.js:1532:21)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at Body (node_modules/rc-table/lib/Body/index.js:51:16)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at updateFunctionComponent (node_modules/react-dom/cjs/react-dom.development.js:17356:20)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at updateSimpleMemoComponent (node_modules/react-dom/cjs/react-dom.development.js:17215:10)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err]       at updateMemoComponent (node_modules/react-dom/cjs/react-dom.development.js:17092:14)
2022-04-13T12:02:14.930+0800 [ERROR] [system.err] 
2022-04-13T12:02:15.689+0800 [LIFECYCLE] [org.gradle.cache.internal.DefaultFileLockManager]

**Comment by maggiehays** [comment]
Hi @hooverhe, we're trying to rally the DataHub Community for support on this one - you can join the conversation here -- https://datahubspace.slack.com/archives/CV2UVAPPG/p1650311224769559

**Comment by anshbansal** [comment]
Hi @hooverhe Is this still an issue? If not, we will close this issue in a few days due to inactivity.
