### ISSUE TITLE
The PLATFORM_EVENT_TOPIC_NAME environment variable is not set.

### ISSUE THREAD

**Issue by kwanyoung-ably** [datahub-project/datahub#4683]
https://github.com/datahub-project/datahub/blob/15474cdad5134efd893e79e04f5ad8ce7e0658b8/docker/kafka-setup/kafka-setup.sh#L33

An error occurs because the `PLATFORM_EVENT_TOPIC_NAME` environment variable is not set in DockerFile.

https://github.com/datahub-project/datahub/blob/15474cdad5134efd893e79e04f5ad8ce7e0658b8/docker/kafka-setup/Dockerfile#L45-L52

```
kafka-setup               | Exception in thread "main" joptsimple.OptionMissingRequiredArgumentException: Option topic requires an argument
kafka-setup               | 	at joptsimple.RequiredArgumentOptionSpec.detectOptionArgument(RequiredArgumentOptionSpec.java:48)
kafka-setup               | 	at joptsimple.ArgumentAcceptingOptionSpec.handleOption(ArgumentAcceptingOptionSpec.java:257)
kafka-setup               | 	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:513)
kafka-setup               | 	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:56)
kafka-setup               | 	at joptsimple.OptionParser.parse(OptionParser.java:396)
kafka-setup               | 	at kafka.admin.TopicCommand$TopicCommandOptions.<init>(TopicCommand.scala:691)
kafka-setup               | 	at kafka.admin.TopicCommand$.main(TopicCommand.scala:52)
kafka-setup               | 	at kafka.admin.TopicCommand.main(TopicCommand.scala)
```

**Comment by jjoyce0510** [comment]
Will fix this - thanks for reporting!

**Comment by jjoyce0510** [comment]
Resolved by https://github.com/datahub-project/datahub/pull/4697
