### ISSUE TITLE
error creating bean with name 'cassandraHealthContributor' defined in class path resource 

### ISSUE THREAD

**Issue by yanqinghe** [datahub-project/datahub#4770]
**Describe the bug**
When I run the MAE consumer job built from the source code, I receive an error related to cassandra bean.
The error message is as follows:

> org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cassandraHealthContributor' defined in class path resource [org/springframework/boot/actuate/autoconfigure/cassandra/CassandraHealthContributorConfigurations$CassandraDriverConfiguration.class]: Unsatisfied dependency expressed through method 'cassandraHealthContributor' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'cassandraSession' defined in class path resource [org/springframework/boot/autoconfigure/cassandra/CassandraAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.datastax.oss.driver.api.core.CqlSession]: Factory method 'cassandraSession' threw exception; nested exception is com.datastax.oss.driver.api.core.AllNodesFailedException: Could not reach any contact point, make sure you've provided valid addresses (showing first 1 nodes, use getAllErrors() for more): Node(endPoint=/127.0.0.1:9042, hostId=null, hashCode=4c9bc65a): [com.datastax.oss.driver.api.core.connection.ConnectionInitException: [s0|control|connecting...] Protocol initialization request, step 1 (OPTIONS): failed to send request (io.netty.channel.StacklessClosedChannelException)]
> 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
> 	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
> 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)

**To Reproduce**
1. build mae-consumer-job docker image using  docker/datahub-mae-consumer/Dockerfile
2. run docker image using  our env file
3. See error

**Expected behavior**
When using a MySQL database, the program should not initialize the beans related to Cassandra.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Ubunut]
 - Version [e.g. 16.04]

**Additional context**
I think on  `CassandraAutoConfiguration.class` should be excluded in `SpringBootApplication` annotation on `com.linkedin.metadata.kafka.MaeConsumerApplication`. This avoids injecting Cassandra related beans

I have fixed the problem in the above way. Do I need to submit a PR？

**Comment by aditya-radhakrishnan** [comment]
Hey there, we would love to receive a PR from you! When you open that up, can you add it to this issue?

**Comment by shirshanka** [comment]
@stephenp-gr : could your team look into this?
