### ISSUE TITLE
UI Ingestion fail

### ISSUE THREAD

**Issue by 710700** [datahub-project/datahub#4788]
I'm using the UI Ingestion to add new source , it gives the following errors:

```shell ~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': '4b1c149b-e0be-499e-a18f-b6d8d0a42f93',
 'infos': ['2022-04-29 03:12:00.686499 [exec_id=4b1c149b-e0be-499e-a18f-b6d8d0a42f93] INFO: Starting execution for task with name=RUN_INGEST',
           '2022-04-29 03:28:38.779686 [exec_id=4b1c149b-e0be-499e-a18f-b6d8d0a42f93] INFO: stdout=Requirement already satisfied: pip in '
           '/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages (21.2.4)\n'
           'Collecting pip\n'
           '  Downloading pip-22.0.4-py3-none-any.whl (2.1 MB)\n'
           'Collecting wheel\n'
           '  Downloading wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n'
           'Requirement already satisfied: setuptools in /tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages '
           '(58.1.0)\n'
           'Collecting setuptools\n'
           '  Downloading setuptools-62.1.0-py3-none-any.whl (1.1 MB)\n'
           'Installing collected packages: wheel, setuptools, pip\n'
           '  Attempting uninstall: setuptools\n'
           '    Found existing installation: setuptools 58.1.0\n'
           '    Uninstalling setuptools-58.1.0:\n'
           '      Successfully uninstalled setuptools-58.1.0\n'
           '  Attempting uninstall: pip\n'
           '    Found existing installation: pip 21.2.4\n'
           '    Uninstalling pip-21.2.4:\n'
           '      Successfully uninstalled pip-21.2.4\n'
           'Successfully installed pip-22.0.4 setuptools-62.1.0 wheel-0.37.1\n'
           'Collecting acryl-datahub[clickhouse,datahub-rest]==0.8.32.1\n'
           '  Downloading acryl_datahub-0.8.32.1-py3-none-any.whl (720 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 720.5/720.5 KB 83.5 kB/s eta 0:00:00\n'
           'Collecting click-default-group\n'
           '  Downloading click-default-group-1.2.2.tar.gz (3.3 kB)\n'
           '  Preparing metadata (setup.py): started\n'
           "  Preparing metadata (setup.py): finished with status 'done'\n"
           'Collecting psutil>=5.8.0\n'
           '  Downloading psutil-5.9.0-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.4/280.4 KB 80.2 kB/s eta 0:00:00\n'
           'Collecting types-termcolor>=1.0.0\n'
           '  Downloading types_termcolor-1.1.4-py3-none-any.whl (2.1 kB)\n'
           'Collecting stackprinter\n'
           '  Downloading stackprinter-0.2.6-py3-none-any.whl (28 kB)\n'
           'Collecting tabulate\n'
           '  Downloading tabulate-0.8.9-py3-none-any.whl (25 kB)\n'
           'Collecting avro-gen3==0.7.2\n'
           '  Downloading avro_gen3-0.7.2-py3-none-any.whl (26 kB)\n'
           'Collecting docker\n'
           '  Downloading docker-5.0.3-py2.py3-none-any.whl (146 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 146.2/146.2 KB 65.9 kB/s eta 0:00:00\n'
           'Collecting PyYAML\n'
           '  Downloading PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 661.8/661.8 KB 66.2 kB/s eta 0:00:00\n'
           'Collecting entrypoints\n'
           '  Downloading entrypoints-0.4-py3-none-any.whl (5.3 kB)\n'
           'Collecting typing-inspect\n'
           '  Downloading typing_inspect-0.7.1-py3-none-any.whl (8.4 kB)\n'
           'Collecting Deprecated\n'
           '  Downloading Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)\n'
           'Collecting avro<1.11,>=1.10.2\n'
           '  Downloading avro-1.10.2.tar.gz (68 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.2/68.2 KB 67.2 kB/s eta 0:00:00\n'
           '  Preparing metadata (setup.py): started\n'
           "  Preparing metadata (setup.py): finished with status 'done'\n"
           'Collecting python-dateutil>=2.8.0\n'
           '  Downloading python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 247.7/247.7 KB 92.3 kB/s eta 0:00:00\n'
           'Collecting progressbar2\n'
           '  Downloading progressbar2-4.0.0-py2.py3-none-any.whl (26 kB)\n'
           'Collecting markupsafe<=2.0.1,>=1.1.1\n'
           '  Downloading MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)\n'
           'Collecting click>=6.0.0\n'
           '  Downloading click-8.1.3-py3-none-any.whl (96 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.6/96.6 KB 88.7 kB/s eta 0:00:00\n'
           'Collecting pydantic>=1.5.1\n'
           '  Downloading pydantic-1.9.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.2 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.2/12.2 MB 60.4 kB/s eta 0:00:00\n'
           'Collecting mixpanel>=4.9.0\n'
           '  Downloading mixpanel-4.9.0-py2.py3-none-any.whl (8.9 kB)\n'
           'Collecting expandvars>=0.6.5\n'
           '  Downloading expandvars-0.9.0-py3-none-any.whl (6.6 kB)\n'
           'Collecting types-Deprecated\n'
           '  Downloading types_Deprecated-1.2.7-py3-none-any.whl (3.1 kB)\n'
           'Collecting termcolor>=1.0.0\n'
           '  Downloading termcolor-1.1.0.tar.gz (3.9 kB)\n'
           '  Preparing metadata (setup.py): started\n'
           "  Preparing metadata (setup.py): finished with status 'done'\n"
           'Collecting typing-extensions>=3.10.0.2\n'
           '  Downloading typing_extensions-4.2.0-py3-none-any.whl (24 kB)\n'
           'Collecting toml>=0.10.0\n'
           '  Downloading toml-0.10.2-py2.py3-none-any.whl (16 kB)\n'
           'Collecting mypy-extensions>=0.4.3\n'
           '  Downloading mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)\n'
           'Collecting requests\n'
           '  Downloading requests-2.27.1-py2.py3-none-any.whl (63 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 63.1/63.1 KB 97.9 kB/s eta 0:00:00\n'
           'Collecting great-expectations>=0.14.11\n'
           '  Downloading great_expectations-0.15.3-py3-none-any.whl (5.0 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.0/5.0 MB 59.2 kB/s eta 0:00:00\n'
           'Collecting greenlet\n'
           '  Downloading greenlet-1.1.2-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (153 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 153.6/153.6 KB 120.3 kB/s eta 0:00:00\n'
           'Collecting clickhouse-sqlalchemy==0.1.8\n'
           '  Downloading clickhouse-sqlalchemy-0.1.8.tar.gz (38 kB)\n'
           '  Preparing metadata (setup.py): started\n'
           "  Preparing metadata (setup.py): finished with status 'done'\n"
           'Collecting sqlalchemy==1.3.24\n'
           '  Downloading SQLAlchemy-1.3.24-cp39-cp39-manylinux2010_x86_64.whl (1.3 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.3/1.3 MB 103.9 kB/s eta 0:00:00\n'
           'Collecting Jinja2<3.1.0\n'
           '  Downloading Jinja2-3.0.3-py3-none-any.whl (133 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 133.6/133.6 KB 97.4 kB/s eta 0:00:00\n'
           'Collecting tzlocal\n'
           '  Downloading tzlocal-4.2-py3-none-any.whl (19 kB)\n'
           'Collecting six\n'
           '  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)\n'
           'Collecting pytz\n'
           '  Downloading pytz-2022.1-py2.py3-none-any.whl (503 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 503.5/503.5 KB 108.1 kB/s eta 0:00:00\n'
           'Collecting clickhouse-driver>=0.1.2\n'
           '  Downloading clickhouse_driver-0.2.3-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl '
           '(695 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 695.1/695.1 KB 92.1 kB/s eta 0:00:00\n'
           'Collecting colorama>=0.4.3\n'
           '  Downloading colorama-0.4.4-py2.py3-none-any.whl (16 kB)\n'
           'Collecting packaging\n'
           '  Downloading packaging-21.3-py3-none-any.whl (40 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.8/40.8 KB 44.7 kB/s eta 0:00:00\n'
           'Collecting pyparsing<3,>=2.4\n'
           '  Downloading pyparsing-2.4.7-py2.py3-none-any.whl (67 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 67.8/67.8 KB 90.7 kB/s eta 0:00:00\n'
           'Collecting scipy>=0.19.0\n'
           '  Downloading scipy-1.8.0-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (42.1 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━╸             29.2/42.1 MB 18.2 kB/s eta 0:11:53\n'
           'ERROR: Exception:\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line '
           '438, in _error_catcher\n'
           '    yield\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line '
           '519, in read\n'
           '    data = self._fp.read(amt) if not fp_closed else b""\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/cachecontrol/filewrapper.py", '
           'line 90, in read\n'
           '    data = self.__fp.read(amt)\n'
           '  File "/usr/local/lib/python3.9/http/client.py", line 463, in read\n'
           '    n = self.readinto(b)\n'
           '  File "/usr/local/lib/python3.9/http/client.py", line 507, in readinto\n'
           '    n = self.fp.readinto(b)\n'
           '  File "/usr/local/lib/python3.9/socket.py", line 704, in readinto\n'
           '    return self._sock.recv_into(b)\n'
           '  File "/usr/local/lib/python3.9/ssl.py", line 1241, in recv_into\n'
           '    return self.read(nbytes, buffer)\n'
           '  File "/usr/local/lib/python3.9/ssl.py", line 1099, in read\n'
           '    return self._sslobj.read(len, buffer)\n'
           'socket.timeout: The read operation timed out\n'
           '\n'
           'During handling of the above exception, another exception occurred:\n'
           '\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/cli/base_command.py", '
           'line 167, in exc_logging_wrapper\n'
           '    status = run_func(*args)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/cli/req_command.py", '
           'line 205, in wrapper\n'
           '    return func(self, options, args)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/commands/install.py", '
           'line 339, in run\n'
           '    requirement_set = resolver.resolve(\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/resolver.py", '
           'line 94, in resolve\n'
           '    result = self._result = resolver.resolve(\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", '
           'line 481, in resolve\n'
           '    state = resolution.resolve(requirements, max_rounds=max_rounds)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", '
           'line 373, in resolve\n'
           '    failure_causes = self._attempt_to_pin_criterion(name)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", '
           'line 213, in _attempt_to_pin_criterion\n'
           '    criteria = self._get_updated_criteria(candidate)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", '
           'line 204, in _get_updated_criteria\n'
           '    self._add_to_criteria(criteria, requirement, parent=candidate)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/resolvelib/resolvers.py", '
           'line 172, in _add_to_criteria\n'
           '    if not criterion.candidates:\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/resolvelib/structs.py", '
           'line 151, in __bool__\n'
           '    return bool(self._sequence)\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", '
           'line 155, in __bool__\n'
           '    return any(self)\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", '
           'line 143, in <genexpr>\n'
           '    return (c for c in iterator if id(c) not in self._incompatible_ids)\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", '
           'line 47, in _iter_built\n'
           '    candidate = func()\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/factory.py", '
           'line 215, in _make_candidate_from_link\n'
           '    self._link_candidate_cache[link] = LinkCandidate(\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", '
           'line 288, in __init__\n'
           '    super().__init__(\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", '
           'line 158, in __init__\n'
           '    self.dist = self._prepare()\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", '
           'line 227, in _prepare\n'
           '    dist = self._prepare_distribution()\n'
           '  File '
           '"/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/resolution/resolvelib/candidates.py", '
           'line 299, in _prepare_distribution\n'
           '    return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", '
           'line 487, in prepare_linked_requirement\n'
           '    return self._prepare_linked_requirement(req, parallel_builds)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", '
           'line 532, in _prepare_linked_requirement\n'
           '    local_file = unpack_url(\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", '
           'line 214, in unpack_url\n'
           '    file = get_http_url(\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/operations/prepare.py", '
           'line 94, in get_http_url\n'
           '    from_path, content_type = download(link, temp_dir.path)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/network/download.py", '
           'line 146, in __call__\n'
           '    for chunk in chunks:\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/cli/progress_bars.py", '
           'line 304, in _rich_progress_bar\n'
           '    for chunk in iterable:\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_internal/network/utils.py", line '
           '63, in response_chunks\n'
           '    for chunk in response.raw.stream(\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line '
           '576, in stream\n'
           '    data = self.read(amt=amt, decode_content=decode_content)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line '
           '541, in read\n'
           '    raise IncompleteRead(self._fp_bytes_read, self.length_remaining)\n'
           '  File "/usr/local/lib/python3.9/contextlib.py", line 137, in __exit__\n'
           '    self.gen.throw(typ, value, traceback)\n'
           '  File "/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/lib/python3.9/site-packages/pip/_vendor/urllib3/response.py", line '
           '443, in _error_catcher\n'
           '    raise ReadTimeoutError(self._pool, None, "Read timed out.")\n'
           "pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.\n"
           '/tmp/datahub/ingest/venv-4b1c149b-e0be-499e-a18f-b6d8d0a42f93/bin/python3: No module named datahub\n',
           "2022-04-29 03:28:38.779883 [exec_id=4b1c149b-e0be-499e-a18f-b6d8d0a42f93] INFO: Failed to execute 'datahub ingest'",
           '2022-04-29 03:28:38.780237 [exec_id=4b1c149b-e0be-499e-a18f-b6d8d0a42f93] INFO: Caught exception EXECUTING '
           'task_id=4b1c149b-e0be-499e-a18f-b6d8d0a42f93, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/default_executor.py", line 119, in execute_task\n'
           '    self.event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete\n'
           '    return f.result()\n'
           '  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result\n'
           '    raise self._exception\n'
           '  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step\n'
           '    result = coro.send(None)\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 115, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"]}
Execution finished with errors. 
```

However, I tried using CLI to ingest with the same recipe, everything worked as expected.
My Recipe:
```yaml source:
    type: clickhouse
    config:
        host_port: '10.80.111.159:8123'
        username: myusername
        password: mypassword
        platform_instance: DatabaseNameToBeIngested
        include_views: true
        include_tables: true
sink:
    type: datahub-rest
    config:
        server: 'http://10.80.111.159:8080'/
```

Since the log says something like "read time out", I tried replace the pip repo url with "https://pypi.tuna.tsinghua.edu.cn/simple" (faster than the official repo) but the error remains

Any hints or suggestions are appreciated !

**Comment by 710700** [comment]
update:
Atfer replacing the pip url in docker container datahub_datahub-actions_1, ingestion succeeded.

shell command
```shell
docker exec -it datahub_datahub-actions_1 /bin/bash

pip config set global.index-url <pip source>
```

**Comment by chenzuoli** [comment]
how to write the recipe.yml if clickhouse doesn't have a password.
I found that acryl_datahub-0.8.33.2 version, there is a option `sqlalchemy_uri` can replace `username` and `password` and `host_port`, but the ingestion install acryl_datahub==0.8.32.1
so how can I change the specified acryl_datahub version?
do you know that?
thanks.
