### ISSUE TITLE
gms is running but not healthy (quick start datahub)

### ISSUE THREAD

**Issue by looperEit** [datahub-project/datahub#4848]
I have tried two method to start datahub, but there always had the problem

`Unable to run quickstart - the following issues were detected:
- datahub-gms is running but not healthy
- `

or
`[root@localhost etc]# docker ps
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                     PORTS                                              NAMES
166a2a279629        acryldata/acryl-datahub-actions:head    "/bin/sh -c 'docke..."   13 hours ago        Up 3 minutes                                                                  datahub_datahub-actions_1
adda466a62e3        linkedin/datahub-gms:head               "/bin/sh -c /datah..."   13 hours ago        Up 3 minutes (unhealthy)   0.0.0.0:8080->8080/tcp                             datahub-gms
`

i can see it's a "gms mem limit" problem but i can't find any way to solve it.

**Comment by looperEit** [comment]
![image](https://user-images.githubusercontent.com/46367388/167087390-d98b83d2-d637-475b-a547-6ef19965b367.png)
![image](https://user-images.githubusercontent.com/46367388/167087471-bd4de57f-e7e8-4758-8809-52a949dd7695.png)

**Comment by xiphl** [comment]
to help troubleshooting efforts, 
what does running ```docker logs datahub-gms``` say?

**Comment by looperEit** [comment]
> to help troubleshooting efforts, what does running `docker logs datahub-gms` say?
thank you and say this：
![image](https://user-images.githubusercontent.com/46367388/167094260-2cbfaeec-4a44-415e-9796-b0a835b64668.png)



> 
+ echo
+ grep -q ://
+ NEO4J_HOST=http://
+ [[ ! -z '' ]]
+ [[ -z '' ]]
+ ELASTICSEARCH_AUTH_HEADER='Accept: */*'
+ [[ '' == true ]]
+ ELASTICSEARCH_PROTOCOL=http
+ WAIT_FOR_EBEAN=
+ [[ '' != true ]]
+ [[ '' == ebean ]]
+ [[ -z '' ]]
+ WAIT_FOR_EBEAN=' -wait tcp://mysql:3306 '
+ WAIT_FOR_CASSANDRA=
+ [[ '' == cassandra ]]
+ WAIT_FOR_KAFKA=
+ [[ '' != true ]]
++ echo broker:29092
++ sed 's/,/ -wait tcp:\/\//g'
+ WAIT_FOR_KAFKA=' -wait tcp://broker:29092 '
+ WAIT_FOR_NEO4J=
+ [[ elasticsearch != elasticsearch ]]
+ OTEL_AGENT=
+ [[ '' == true ]]
+ PROMETHEUS_AGENT=
+ [[ '' == true ]]
+ COMMON='
     -wait tcp://mysql:3306            -wait tcp://broker:29092           -timeout 240s     java -Xms1g -Xmx1g                -jar /jetty-runner.jar     --jar jetty-util.jar     --jar jetty-jmx.jar     --config /datahub/datahub-gms/scripts/jetty.xml     /datahub/datahub-gms/bin/war.war'
+ [[ '' != true ]]
+ exec dockerize -wait http://elasticsearch:9200 -wait-http-header 'Accept: */*' -wait tcp://mysql:3306 -wait tcp://broker:29092 -timeout 240s java -Xms1g -Xmx1g -jar /jetty-runner.jar --jar jetty-util.jar --jar jetty-jmx.jar --config /datahub/datahub-gms/scripts/jetty.xml /datahub/datahub-gms/bin/war.war
2022/05/06 06:40:45 Waiting for: http://elasticsearch:9200
2022/05/06 06:40:45 Waiting for: tcp://mysql:3306
2022/05/06 06:40:45 Waiting for: tcp://broker:29092
2022/05/06 06:40:45 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:45 Connected to tcp://mysql:3306
2022/05/06 06:40:45 Received 200 from http://elasticsearch:9200
2022/05/06 06:40:46 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:47 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:48 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:49 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:50 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:51 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:52 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:53 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:54 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:55 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:56 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:57 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:58 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:59 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:00 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:01 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:02 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:03 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:04 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:05 Connected to tcp://broker:29092
2022-05-06 06:41:06.261:INFO::main: Logging initialized @742ms to org.eclipse.jetty.util.log.StdErrLog
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
2022-05-06 06:41:06.305:INFO:oejr.Runner:main: Runner
2022-05-06 06:41:06.564:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2022-05-06 06:41:06.702:INFO:oejs.Server:main: jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_302-b08
2022-05-06 06:41:07.545:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@50cbc42f{/,null,UNAVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
java.util.zip.ZipException: invalid entry CRC (expected 0x784cbf6c but got 0x87b34093)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at org.eclipse.jetty.util.IO.copy(IO.java:172)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:218)
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:636)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:140)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
2022-05-06 06:41:07.603:INFO:oejs.AbstractConnector:main: Started ServerConnector@39a054a5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2022-05-06 06:41:07.604:INFO:oejs.Server:main: Started @2089ms

**Comment by looperEit** [comment]
> to help troubleshooting efforts, what does running `docker logs datahub-gms` say?
thank you and say this:
![image](https://user-images.githubusercontent.com/46367388/167094574-f360a4f9-465e-472e-b1eb-0da13f23fe2e.png)


`+ echo
+ grep -q ://
+ NEO4J_HOST=http://
+ [[ ! -z '' ]]
+ [[ -z '' ]]
+ ELASTICSEARCH_AUTH_HEADER='Accept: */*'
+ [[ '' == true ]]
+ ELASTICSEARCH_PROTOCOL=http
+ WAIT_FOR_EBEAN=
+ [[ '' != true ]]
+ [[ '' == ebean ]]
+ [[ -z '' ]]
+ WAIT_FOR_EBEAN=' -wait tcp://mysql:3306 '
+ WAIT_FOR_CASSANDRA=
+ [[ '' == cassandra ]]
+ WAIT_FOR_KAFKA=
+ [[ '' != true ]]
++ echo broker:29092
++ sed 's/,/ -wait tcp:\/\//g'
+ WAIT_FOR_KAFKA=' -wait tcp://broker:29092 '
+ WAIT_FOR_NEO4J=
+ [[ elasticsearch != elasticsearch ]]
+ OTEL_AGENT=
+ [[ '' == true ]]
+ PROMETHEUS_AGENT=
+ [[ '' == true ]]
+ COMMON='
     -wait tcp://mysql:3306            -wait tcp://broker:29092           -timeout 240s     java -Xms1g -Xmx1g                -jar /jetty-runner.jar     --jar jetty-util.jar     --jar jetty-jmx.jar     --config /datahub/datahub-gms/scripts/jetty.xml     /datahub/datahub-gms/bin/war.war'
+ [[ '' != true ]]
+ exec dockerize -wait http://elasticsearch:9200 -wait-http-header 'Accept: */*' -wait tcp://mysql:3306 -wait tcp://broker:29092 -timeout 240s java -Xms1g -Xmx1g -jar /jetty-runner.jar --jar jetty-util.jar --jar jetty-jmx.jar --config /datahub/datahub-gms/scripts/jetty.xml /datahub/datahub-gms/bin/war.war
2022/05/06 06:40:45 Waiting for: http://elasticsearch:9200
2022/05/06 06:40:45 Waiting for: tcp://mysql:3306
2022/05/06 06:40:45 Waiting for: tcp://broker:29092
2022/05/06 06:40:45 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:45 Connected to tcp://mysql:3306
2022/05/06 06:40:45 Received 200 from http://elasticsearch:9200
2022/05/06 06:40:46 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:47 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:48 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:49 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:50 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:51 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:52 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:53 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:54 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:55 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:56 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:57 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:58 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:40:59 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:00 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:01 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:02 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:03 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:04 Problem with dial: dial tcp 172.18.0.5:29092: connect: connection refused. Sleeping 1s
2022/05/06 06:41:05 Connected to tcp://broker:29092
2022-05-06 06:41:06.261:INFO::main: Logging initialized @742ms to org.eclipse.jetty.util.log.StdErrLog
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
2022-05-06 06:41:06.305:INFO:oejr.Runner:main: Runner
2022-05-06 06:41:06.564:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2022-05-06 06:41:06.702:INFO:oejs.Server:main: jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_302-b08
2022-05-06 06:41:07.545:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@50cbc42f{/,null,UNAVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
java.util.zip.ZipException: invalid entry CRC (expected 0x784cbf6c but got 0x87b34093)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at org.eclipse.jetty.util.IO.copy(IO.java:172)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:218)
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:636)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:140)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
2022-05-06 06:41:07.603:INFO:oejs.AbstractConnector:main: Started ServerConnector@39a054a5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2022-05-06 06:41:07.604:INFO:oejs.Server:main: Started @2089ms
`

**Comment by xiphl** [comment]
gms will attempt to connect to all the data stores. If it does not connect successfully, it will keep waiting for it to come up. so the next qn is whether ```docker logs broker``` show any issue?

**Comment by looperEit** [comment]
> gms will attempt to connect to all the data stores. If it does not connect successfully, it will keep waiting for it to come up (and will not become healthy). so the next qn is whether `docker logs broker` show any issue?
Thanks a lot, but I tried this one command and got so many messages that I couldn't solve the problem.

**Comment by looperEit** [comment]
> gms will attempt to connect to all the data stores. If it does not connect successfully, it will keep waiting for it to come up (and will not become healthy). so the next qn is whether `docker logs broker` show any issue?

![image](https://user-images.githubusercontent.com/46367388/167151048-27b2c474-3f86-4925-a2b7-46b42c1c0115.png)

**Comment by looperEit** [comment]
> gms will attempt to connect to all the data stores. If it does not connect successfully, it will keep waiting for it to come up (and will not become healthy). so the next qn is whether `docker logs broker` show any issue?

thanks a lot for your replying，i got a information that waiting for a while will solve it. And I don't know if the GMS you said will connect to all the databases, if you have to wait for a while and wait for it to connect, then this problem will be solved.

**Comment by pedro93** [comment]
Hello @looperEit,

What operating system are you using? We have seen the crc entry exception happening in CentOS-based systems but haven’t had success in identifying the root cause nor in replicating the issue.

**Comment by looperEit** [comment]
> Hello @looperEit,
> 
> What operating system are you using? We have seen the crc entry exception happening in CentOS-based systems but haven’t had success in identifying the root cause nor in replicating the issue.

thanks for your replying, i use the Cent-OS and the version of the datahub is v0.8.33. and it shows that the gms is unhealthy. But when i using the datahub--version 0.8.34 and it work!. so i don't know if it is a version issue？
