### ISSUE TITLE
gms is running but not healthy

### ISSUE THREAD

**Issue by looperEit** [datahub-project/datahub#4856]
i used the `datahub docker quickstart --version v0.8.33` to start the datahub，but it showed：`- datahub-gms is running but not healthy
` like this：
![image](https://user-images.githubusercontent.com/46367388/167156459-f678be0e-f721-480c-8287-bd1cfc416d60.png)
and also i couldn't login the datahub and it showed:
![image](https://user-images.githubusercontent.com/46367388/167156799-04e91d71-2079-48a0-8de4-43d2e9fe9420.png)

then i tried to solve it:
and M.r[xiphl](https://github.com/xiphl) said：
![image](https://user-images.githubusercontent.com/46367388/167157023-0e1350c2-3f60-446c-ae93-2e6c08bd1ddc.png)

but I waited for a while and it still couldn't login；

then I used the `docker logs datahub-gms` to see the gms-log:

> b/datahub-gms/scripts/jetty.xml /datahub/datahub-gms/bin/war.war
2022/05/06 14:31:20 Waiting for: http://elasticsearch:9200
2022/05/06 14:31:20 Waiting for: tcp://mysql:3306
2022/05/06 14:31:20 Waiting for: tcp://broker:29092
2022/05/06 14:31:20 Connected to tcp://mysql:3306
2022/05/06 14:31:20 Problem with dial: dial tcp 172.18.0.6:29092: connect: connection refused. Sleeping 1s
2022/05/06 14:31:20 Received 200 from http://elasticsearch:9200
2022/05/06 14:31:21 Problem with dial: dial tcp 172.18.0.6:29092: connect: connection refused. Sleeping 1s
2022/05/06 14:31:22 Problem with dial: dial tcp 172.18.0.6:29092: connect: connection refused. Sleeping 1s
2022/05/06 14:31:23 Connected to tcp://broker:29092
2022-05-06 14:31:24.165:INFO::main: Logging initialized @597ms to org.eclipse.jetty.util.log.StdErrLog
WARNING: jetty-runner is deprecated.
         See Jetty Documentation for startup options
         https://www.eclipse.org/jetty/documentation/
2022-05-06 14:31:24.228:INFO:oejr.Runner:main: Runner
2022-05-06 14:31:24.448:INFO:oeju.TypeUtil:main: JVM Runtime does not support Modules
2022-05-06 14:31:24.599:INFO:oejs.Server:main: jetty-9.4.20.v20190813; built: 2019-08-13T21:28:18.144Z; git: 84700530e645e812b336747464d6fbbf370c9a20; jvm 1.8.0_302-b08
2022-05-06 14:31:25.181:WARN:oejw.WebAppContext:main: Failed startup of context o.e.j.w.WebAppContext@50cbc42f{/,null,UNAVAILABLE}{file:///datahub/datahub-gms/bin/war.war}
java.util.zip.ZipException: invalid entry CRC (expected 0xe78b2198 but got 0xde56297a)
	at java.util.zip.ZipInputStream.readEnd(ZipInputStream.java:394)
	at java.util.zip.ZipInputStream.read(ZipInputStream.java:196)
	at java.util.jar.JarInputStream.read(JarInputStream.java:207)
	at org.eclipse.jetty.util.IO.copy(IO.java:172)
	at org.eclipse.jetty.util.IO.copy(IO.java:122)
	at org.eclipse.jetty.util.resource.JarResource.copyTo(JarResource.java:218)
	at org.eclipse.jetty.webapp.WebInfConfiguration.unpack(WebInfConfiguration.java:636)
	at org.eclipse.jetty.webapp.WebInfConfiguration.preConfigure(WebInfConfiguration.java:140)
	at org.eclipse.jetty.webapp.WebAppContext.preConfigure(WebAppContext.java:488)
	at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:523)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:117)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:169)
	at org.eclipse.jetty.server.Server.start(Server.java:407)
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:110)
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:106)
	at org.eclipse.jetty.server.Server.doStart(Server.java:371)
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:72)
	at org.eclipse.jetty.runner.Runner.run(Runner.java:520)
	at org.eclipse.jetty.runner.Runner.main(Runner.java:565)
2022-05-06 14:31:25.219:INFO:oejs.AbstractConnector:main: Started ServerConnector@39a054a5{HTTP/1.1,[http/1.1]}{0.0.0.0:8080}
2022-05-06 14:31:25.220:INFO:oejs.Server:main: Started @1659ms

could you please tell me how to solve it？
thank you very much.

**Comment by looperEit** [comment]
now i used the `datahub docker quickstart --version v0.8.24` instead of the "0.8.23" , the issue was solved. And i don't know if it is a version issue.

By the way, i used CentOS.

**Comment by looperEit** [comment]
i solved it by myself, but i don't know why. There are my two guesses：
1、enviromental problem.
    when i first faced this problem, i hava had three version of python in the vm. 3.6 、3.7 and 2.7. i change them again and again. And my pip3 installing is also failure. And when i start it with lower version of datahub(0.8.24). i get another issue
![316167a0ea804eccfba570dbf29c077](https://user-images.githubusercontent.com/46367388/167297427-74244308-97f9-471e-bac6-6adeab7b0290.png)
and i get the method to the isuue is updating the Python version to 3.8.
So i think it is a enviromental problem;
2、the datahub version 
I find that start datahub with lower version(0.8.24) at first, and then use command to update it to 0.8.34, which can avoid this issue.
Please correct me if there is a problem. thanks.

**Comment by RyanHolstien** [comment]
Hi @looperEit ! Glad you were able to get around this issue, what version of CentOS are you running? We have tried to reproduce this on CentOS 8, but were not able to.

**Comment by looperEit** [comment]
> Hi @looperEit ! Glad you were able to get around this issue, what version of CentOS are you running? We have tried to reproduce this on CentOS 8, but were not able to.

thanks for your replying, i run it on Centos7 on the server;

**Comment by maggiehays** [comment]
Hi @looperEit! Please take a look at [this issue](https://github.com/datahub-project/datahub/issues/4690#issuecomment-1104012823) for ongoing conversations; will close this one out for now!
