### ISSUE TITLE
quickstart sueccess,acryl-datahub install success

### ISSUE THREAD

**Issue by redgreat** [datahub-project/datahub#4930]
**Describe the bug**
OS :Linux iZbp1e4qug6kl2vcvhr5f2Z 4.18.0-348.7.1.el8_5.x86_64 #1 SMP Wed Dec 22 13:25:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
py: Python 3.6.8
gcc:gcc version 8.5.0 20210514 (Red Hat 8.5.0-4) (GCC)
jr:jq-1.6
docker-compose:Docker Compose version v2.5.0
docker:Docker version 20.10.16, build aa7e414

when i install with sh
datahub docker quickstart --quickstart-compose-file ./quickstart/docker-compose-without-neo4j.quickstart.yml

`
...........
✔ DataHub is now running
Ingest some demo data using `datahub docker ingest-sample-data`,
or head to http://localhost:9002 (username: datahub, password: datahub) to play around with the frontend.
Need support? Get in touch on Slack: https://slack.datahubproject.io/
`

datahub version

`
DataHub CLI version: 0.8.34.2
Python version: 3.6.8 (default, Sep 10 2021, 09:13:53) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)]
`

and then i install acryl-datahub
with thes:
`
python3 -m pip install --upgrade pip wheel setuptools
python3 -m pip uninstall datahub acryl-datahub || true  # sanity check - ok if it fails
python3 -m pip install --upgrade acryl-datahub
`

when i use   datahub check plugins first
显示是正常的

then i install 
python3 -m pip install 'acryl-datahub[mysql]'
after
run  datahub check plugins first agaig

prints:
`
Sources:
[2022-05-17 17:36:00,753] ERROR    {datahub.entrypoints:173} - Stackprinter failed while formatting <FrameInfo /usr/local/lib/python3.6/site-packages/datahub/ingestion/source/sql/sql_common.py, line 265, scope SQLAlchemyConfig>:
  File "/usr/local/lib/python3.6/site-packages/stackprinter/frame_formatting.py", line 225, in select_scope
    raise Exception("Picked an invalid source context: %s" % info)
Exception: Picked an invalid source context: [265], [214], dict_keys([214, 215])

So here is your original traceback at least:

Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/datahub/entrypoints.py", line 149, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/datahub/cli/check_cli.py", line 38, in plugins
    click.echo(source_registry.summary(verbose=verbose))
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/api/registry.py", line 145, in summary
    self._ensure_not_lazy(key)
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/api/registry.py", line 84, in _ensure_not_lazy
    plugin_class = import_path(path)
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/api/registry.py", line 32, in import_path
    item = importlib.import_module(module_name)
  File "/usr/lib64/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/source/sql/mariadb.py", line 9, in <module>
    from datahub.ingestion.source.sql.mysql import MySQLConfig, MySQLSource
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/source/sql/mysql.py", line 15, in <module>
    from datahub.ingestion.source.sql.sql_common import (
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/source/sql/sql_common.py", line 231, in <module>
    class SQLAlchemyConfig(StatefulIngestionConfigBase):
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/source/sql/sql_common.py", line 265, in SQLAlchemyConfig
    from datahub.ingestion.source.ge_data_profiler import GEProfilingConfig
  File "/usr/local/lib/python3.6/site-packages/datahub/ingestion/source/ge_data_profiler.py", line 27, in <module>
    from great_expectations.core.util import convert_to_json_serializable
  File "/usr/local/lib/python3.6/site-packages/great_expectations/__init__.py", line 7, in <module>
    from great_expectations.data_context import DataContext
  File "/usr/local/lib/python3.6/site-packages/great_expectations/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context import (
  File "/usr/local/lib/python3.6/site-packages/great_expectations/data_context/data_context/__init__.py", line 1, in <module>
    from great_expectations.data_context.data_context.base_data_context import (
  File "/usr/local/lib/python3.6/site-packages/great_expectations/data_context/data_context/base_data_context.py", line 20, in <module>
    from great_expectations.core.config_peer import ConfigPeer
  File "/usr/local/lib/python3.6/site-packages/great_expectations/core/__init__.py", line 3, in <module>
    from .expectation_suite import (
  File "/usr/local/lib/python3.6/site-packages/great_expectations/core/expectation_suite.py", line 18, in <module>
    from great_expectations.core.usage_statistics.events import UsageStatsEvents
  File "/usr/local/lib/python3.6/site-packages/great_expectations/core/usage_statistics/events.py", line 33
    from __future__ import annotations
                                     ^
SyntaxError: future feature annotations is not defined

[2022-05-17 17:36:00,753] INFO     {datahub.entrypoints:177} - DataHub CLI version: 0.8.34.2 at /usr/local/lib/python3.6/site-packages/datahub/__init__.py
[2022-05-17 17:36:00,753] INFO     {datahub.entrypoints:180} - Python version: 3.6.8 (default, Sep 10 2021, 09:13:53) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] at /usr/bin/python3 on Linux-4.18.0-348.7.1.el8_5.x86_64-x86_64-with-centos-8.5.2111
[2022-05-17 17:36:00,753] INFO     {datahub.entrypoints:182} - GMS config {}
`
and same log run
datahub ingest -c /opt/datahub/docker/ingestion/mysql_datahub.yml

**Comment by xiphl** [comment]
check your installed version of Great Expectations. think there is a new version of GE recently that causes this error msg.

**Comment by redgreat** [comment]
thanks i resove it with run
`pip install --upgrade great-expectations==0.14.0`

> check your installed version of Great Expectations. think there is a new version of GE recently that causes this error msg.
