### ISSUE TITLE
Error 500 when browsing Kafka datasets - from GraphQLController

### ISSUE THREAD

**Issue by tullis** [datahub-project/datahub#4956]
We have ingested some Kafka topics using the [Kafka source plugin](https://datahubproject.io/docs/generated/ingestion/sources/kafka)

* Showing search results of Kafka datasets works.
* Viewing an individual Kafka dataset is works.
* Attempting to browse Kafaka datasets results in an **error 500** in the browser.

No schema information was ingested with the topics, so the only metadata associated with these Kafka datasets are their topic names.

**To Reproduce**
Steps to reproduce the behaviour.
1. Select Kafka datasets from the home page of DataHub - (no error) [link for reference](https://datahub.wikimedia.org/search?filter_platform=urn:li:dataPlatform:kafka)
2. View an individual Kafka dataset - (no error) [link for reference](https://datahub.wikimedia.org/dataset/urn:li:dataset:(urn:li:dataPlatform:kafka,EditorJourney,PROD)/Schema?is_lineage_mode=false)
3. Click on the Datasets->PROD->**kafka** link from the breadcrumbs to go to https://datahub.wikimedia.org/browse/dataset/prod/kafka
4. See error 500 bar across the top of the screen

**Expected behavior**
No error and a list of Kafka datasets again

**Screenshots**
![slack_ntlL1cVGr5](https://user-images.githubusercontent.com/2117946/169297126-cc5e6f13-ca31-43dd-9d05-b7f85faf0749.gif)

**Server environment**
 - DataHub version: 0.8.34
 - Graph database: Opensearch 1.2.4
 - Schema registry: **Karapace** (for licensing reasons)
 - RBDMS: MariaDB 10.4
 
**Additional context**
The following error messages are displayed in the GMS log at the time:
```
09:11:44.373 [Thread-2769] ERROR c.l.datahub.graphql.GmsGraphQLEngine:1127 - Failed to load Entities of type: Dataset, keys: [urn:li:dataset:(urn:li:dataPlatform:kafka,-L,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,-l,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,04,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,ContentTranslationAbuseFilter,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,DataHubUsageEvent_v1,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,EditorJourney,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,FailedMetadataChangeEvent_v4,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,FailedMetadataChangeProposal_v1,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,KaiOSAppFeedback,PROD), urn:li:dataset:(urn:li:dataPlatform:kafka,MetadataAuditEvent_v4,PROD)] Failed to batch load Datasets
09:11:44.374 [Thread-2769] ERROR c.l.d.g.e.DataHubDataFetcherExceptionHandler:21 - Failed to execute DataFetcher
java.util.concurrent.CompletionException: java.lang.RuntimeException: Failed to retrieve entities of type Dataset
        at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
        at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.RuntimeException: Failed to retrieve entities of type Dataset
        at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$136(GmsGraphQLEngine.java:1128)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
        ... 1 common frames omitted
Caused by: java.lang.RuntimeException: Failed to batch load Datasets
        at com.linkedin.datahub.graphql.types.dataset.DatasetType.batchLoad(DatasetType.java:135)
        at com.linkedin.datahub.graphql.GmsGraphQLEngine.lambda$null$136(GmsGraphQLEngine.java:1125)
        ... 2 common frames omitted
Caused by: java.lang.IllegalStateException: Duplicate key com.linkedin.metadata.entity.ebean.EbeanAspectV2@d416e85f
        at java.util.stream.Collectors.lambda$throwingMerger$0(Collectors.java:133)
        at java.util.HashMap.merge(HashMap.java:1255)
        at java.util.stream.Collectors.lambda$toMap$58(Collectors.java:1320)
        at java.util.stream.ReduceOps$3ReducingSink.accept(ReduceOps.java:169)
        at java.util.ArrayList$Itr.forEachRemaining(ArrayList.java:901)
        at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
        at com.linkedin.metadata.entity.ebean.EbeanAspectDao.batchGet(EbeanAspectDao.java:228)
        at com.linkedin.metadata.entity.ebean.EbeanEntityService.getEnvelopedAspects(EbeanEntityService.java:715)
        at com.linkedin.metadata.entity.ebean.EbeanEntityService.getCorrespondingAspects(EbeanEntityService.java:247)
        at com.linkedin.metadata.entity.ebean.EbeanEntityService.getLatestEnvelopedAspects(EbeanEntityService.java:207)
        at com.linkedin.metadata.entity.EntityService.getEntitiesV2(EntityService.java:180)
        at com.linkedin.entity.client.JavaEntityClient.batchGetV2(JavaEntityClient.java:99)
        at com.linkedin.datahub.graphql.types.dataset.DatasetType.batchLoad(DatasetType.java:119)
```
Apologies, this error is a single long line.
```
09:11:44.375 [Thread-2765] ERROR c.datahub.graphql.GraphQLController:93 - Errors while executing graphQL query: "query getBrowseResults($input: BrowseInput!) {\n  browse(input: $input) {\n    entities {\n      urn\n      type\n      ... on Dataset {\n        name\n        origin\n        properties {\n          name\n          description\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        subTypes {\n          typeNames\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on Dashboard {\n        urn\n        type\n        tool\n        dashboardId\n        properties {\n          name\n          description\n          externalUrl\n          access\n          lastModified {\n            time\n            __typename\n          }\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on GlossaryTerm {\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        properties {\n          name\n          description\n          definition\n          termSource\n          sourceRef\n          sourceUrl\n          customProperties {\n            key\n            value\n            __typename\n          }\n          __typename\n        }\n        __typename\n      }\n      ... on Chart {\n        urn\n        type\n        tool\n        chartId\n        properties {\n          name\n          description\n          externalUrl\n          type\n          access\n          lastModified {\n            time\n            __typename\n          }\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on DataFlow {\n        urn\n        type\n        orchestrator\n        flowId\n        cluster\n        properties {\n          name\n          description\n          project\n          __typename\n        }\n        editableProperties {\n          description\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        glossaryTerms {\n          ...glossaryTerms\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        domain {\n          ...entityDomain\n          __typename\n        }\n        __typename\n      }\n      ... on MLFeatureTable {\n        urn\n        type\n        name\n        description\n        featureTableProperties {\n
description\n          mlFeatures {\n            urn\n            __typename\n          }\n          mlPrimaryKeys {\n            urn\n            __typename\n          }\n          __typename\n        }\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        __typename\n      }\n      ... on MLModel {\n        name\n        origin\n        description\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        globalTags {\n          ...globalTagsFields\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        __typename\n      }\n      ... on MLModelGroup {\n        name\n        origin\n        description\n        ownership {\n          ...ownershipFields\n          __typename\n        }\n        platform {\n          ...platformFields\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    groups {\n      name\n      count\n      __typename\n    }\n    start\n    count\n    total\n    metadata {\n      path\n      totalNumEntities\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment platformFields on DataPlatform {\n  urn\n  type\n  name\n  properties {\n    type\n    displayName\n    datasetNameDelimiter\n    logoUrl\n    __typename\n  }\n  displayName\n  info {\n    type\n    displayName\n    datasetNameDelimiter\n    logoUrl\n    __typename\n  }\n  __typename\n}\n\nfragment ownershipFields on Ownership {\n  owners {\n    owner {\n      ... on CorpUser {\n        urn\n        type\n        username\n        info {\n          active\n          displayName\n          title\n          email\n          firstName\n          lastName\n          fullName\n          __typename\n        }\n        properties {\n          active\n          displayName\n          title\n          email\n          firstName\n          lastName\n          fullName\n          __typename\n        }\n        editableProperties {\n          displayName\n          title\n          pictureLink\n          email\n          __typename\n        }\n        __typename\n      }\n      ... on CorpGroup {\n        urn\n        type\n        name\n        properties {\n          displayName\n          email\n          __typename\n        }\n        info {\n          displayName\n          email\n          admins {\n            urn\n            username\n            info {\n              active\n              displayName\n              title\n              email\n              firstName\n              lastName\n              fullName\n              __typename\n            }\n            editableInfo {\n              pictureLink\n              teams\n              skills\n              __typename\n            }\n            __typename\n          }\n          members {\n            urn\n            username\n            info {\n              active\n              displayName\n              title\n              email\n              firstName\n              lastName\n              fullName\n              __typename\n            }\n            editableInfo {\n              pictureLink\n              teams\n              skills\n              __typename\n            }\n            __typename\n          }\n          groups\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    type\n    __typename\n  }\n  lastModified {\n    time\n    __typename\n  }\n  __typename\n}\n\nfragment globalTagsFields on GlobalTags {\n  tags {\n    tag {\n      urn\n      name\n      description\n      properties {\n        colorHex\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment glossaryTerms on GlossaryTerms {\n  terms {\n    term {\n      urn\n      name\n      properties {\n        name\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n  __typename\n}\n\nfragment entityDomain on Domain {\n  urn\n  properties {\n    name\n    __typename\n  }\n  __typename\n}\n", result: {errors=[{message=An unknown error occurred., locations=[{line=3, column=5}], path=[browse, entities], extensions={code=500, type=SERVER_ERROR, classification=DataFetchingException}}], data={browse=null}}, errors: [DataHubGraphQLError{path=[browse, entities], code=SERVER_ERROR, locations=[SourceLocation{line=3, column=5}]}]
```

**Comment by xiphl** [comment]
I encountered error 500 previously, what i did was to rollback and ingest one by one to see which dataset was causing the fetching error. The last time it was failing was because one of the dataset tags was not a valid tag in the system (something about capitalcase letters in the tag) but it was resolved in newer versions.

**Comment by tullis** [comment]
Thanks @xiphl - that's a great suggestion. We haven't got any tags for any of these datasets, but it's possible that the names is invalid. The only one which seems unusual at the moment is a topic named `-l` which might be causing the error. I'll try deleting that one.

I've already tried deleting them in bulk and redoing the ingestion, but I'll try it again, perhaps in smaller batches.

**Comment by tullis** [comment]
Well that's interesting. It looks like it might be a case sensitivty issue, and or an issue regarding duplication:

When listing topics I can see that we have a few oddly named topics, including the following two.

* `-l`
* `-L`

![image](https://user-images.githubusercontent.com/2117946/169305380-68d3eb9b-52c6-49a6-95a3-f1e8f7790b0c.png)

I tried deleting these specific urns by hand, but got a 500 error for both of these:
```
datahub delete --urn 'urn:li:dataPlatform:kafka,-L' --env PROD
datahub delete --urn 'urn:li:dataPlatform:kafka,-l' --env PROD
```
I then did a bulk delete of everything using the kafka platform:
`datahub delete --env PROD --entity_type dataset --platform kafka --hard`
...followed by a new ingestion with a filter applied. The source in the recipe is as follows:
```
source:
  type: "kafka"
  config:
    connection:
      bootstrap: "kafka-jumbo1001.eqiad.wmnet:9092"
      schema_registry_url: http://karapace1001.eqiad.wmnet:8081
    topic_patterns:
      deny:
        - "^-.*"
  ```
This was intended to filter out anything starting with a hyphen. Indeed the ingestion run claims to have filtered out these two topics:
![image](https://user-images.githubusercontent.com/2117946/169306810-d0a61b11-b181-417d-9355-49961f40fe3f.png)

Now the filter_platform view correctly omits the dataset:
![image](https://user-images.githubusercontent.com/2117946/169307602-b5a7ceff-61e7-474f-9454-54205e2ed7d9.png)

The browse view returns a 200 now (instead of a 500) but it still shows an entry for the `-L` dataset.

![image](https://user-images.githubusercontent.com/2117946/169307949-cfe108cd-0762-4746-b63b-6cd0045fad1a.png)

**Comment by tullis** [comment]
I think that we can close this now as it's no longer affectng us. It was definitely something related to case sensitivity and duplicates though.
