### ISSUE TITLE
Fail to ingest views from vertica

### ISSUE THREAD

**Issue by njalan** [datahub-project/datahub#5093]
Below is my config:
source:
  type: sqlalchemy
  config:
    schema_pattern:
      allow:
        - xxxx
    platform: vertica
    connect_uri: 'vertica+vertica_python://xxx:xxxx@xxxx:5433/vertica'
    domain:
          "urn:li:domain:test":
            allow:
              - ".*"

sink:
    type: datahub-rest
    config:
        server: 'http://xxxx:8080'

error message is :
[2022-06-06 15:24:07,976] WARNING  {datahub.ingestion.source.sql.sql_common:1141} - Unable to ingest view xxxxxx due to an exception.
 Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/python3/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/python3/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 235, in execute
    self._execute_simple_query(operation)
  File "/usr/local/python3/lib/python3.8/site-packages/vertica_python/vertica/cursor.py", line 632, in _execute_simple_query
    raise errors.QueryError.from_error_response(self._message, query)
vertica_python.errors.MissingRelation: Severity: ERROR, Message: Relation "pg_class" does not exist

**Comment by njalan** [comment]
I am able to ingest views from the latest datahub
