### ISSUE TITLE
Great Expectations SqlAlchemyExecutionEngine won't work with sqlalchemy==1.3.24

### ISSUE THREAD

**Issue by ramonprieto** [datahub-project/datahub#5126]
**Describe the bug**
The current (0.8.36) datahub[great-expectations] package requires sqlalchemy==1.3.24 which won't work with great expectations when using redshift as a datasource.

**To Reproduce**
1. `run poetry install` with the following toml file
```
[tool.poetry.dependencies]
python = ">=3.7.1,<3.8"
great-expectations = "0.15.1"
mistune = "0.8.4"
black = "^22.3.0"
pyathena = "^2.9.1"
psycopg2-binary = "^2.9.3"
sqlalchemy-redshift = "^0.8.9"
psycopg2 = "^2.9.3"
acryl-datahub = {extras = ["great-expectations"], version = "^0.8.36"}
```
2. Setup GE using `poetry run great_expectations init`
3.  Connect to a Redshift datasource and build an expectation for it
4. Try to run a checkpoint
```python
import great_expectations as ge
from great_expectations.core.batch import RuntimeBatchRequest
from great_expectations.checkpoint import SimpleCheckpoint
from ruamel.yaml import YAML

yaml = YAML()

context = ge.get_context()

batch_request = RuntimeBatchRequest(
    datasource_name="redshift",
    data_connector_name="default_runtime_data_connector_name",
    data_asset_name="public.daily_data",
    runtime_parameters={
        "query": "select * from public.daily_data",
    },
    batch_identifiers={"default_identifier_name": "default_identifier_name"},
    batch_spec_passthrough={"create_temp_table": False, "table_name": "daily_data", "schema_name": "public"},
)

checkpoint_config = {
    "class_name": "SimpleCheckpoint",
    "run_name_template": "data-daily",
    "validations": [
        {
            "batch_request": batch_request,
            "expectation_suite_name": expectation_suite_name
        },
    ],
    "action_list": [
        {
            "name": "store_validation_result",
            "action": {
                "class_name": "StoreValidationResultAction"
            },
        },
        {
            "name": "store_evaluation_params",
            "action": {
                "class_name": "StoreEvaluationParametersAction"
            },
        },
        {
            "name": "update_data_docs",
            "action": {
                "class_name": "UpdateDataDocsAction",
                "site_names": []
            },
        },
        {
            "name": "datahub_action",
            "action": {
                "module_name": "datahub.integrations.great_expectations.action",
                "class_name": "DataHubValidationAction",
                "server_url": "https://datahub.data.zapier-staging.com/"
            },
        },
    ],
}
checkpoint = SimpleCheckpoint(
    "daily_data.warning",
    context,
    **checkpoint_config
)
checkpoint_result = checkpoint.run()
```
6. Most expectations fail with `'TextAsFrom' object has no attribute 'subquery'`
7. Delete `acryl-datahub[great-expectations]` and `run poetry update`
8. rerun the checkpoint. All expectations pass

**Expected behavior**
All expectations pass

**Desktop (please complete the following information):**
 - OS: MacOS Catalina

**Comment by maggiehays** [comment]
Hi @mayurinehate! Can you take a look at this issue, please?

**Comment by mayurinehate** [comment]
Hey @ramonprieto There is an open issue with same error on Great Expectations, when using BigQuery with sqlalchemy 1.3.24 - https://github.com/great-expectations/great_expectations/issues/3571 

I believe this issue (support for sqlalchemy 1.3.24) needs to be addressed in Great Expectations code. Can you please share the full error stack trace here ? It will help confirm the cause. Meanwhile let me check if I can figure out something to relax the sqlalchemy version restriction, when using `DatahubValidationAction`.

**Comment by ramonprieto** [comment]
Thanks for looking into this @mayurinehate . Here's the stack trace
```
Traceback (most recent call last):
File "/Users/ramonprieto/src/zapier/great-expectations-zapier/venv/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 398, in resolve_metrics
new_resolved = self.resolve_metric_bundle(metric_fn_bundle)
File "/Users/ramonprieto/src/zapier/great-expectations-zapier/venv/lib/python3.8/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 860, in resolve_metric_bundle
selectable = self.get_domain_records(
File "/Users/ramonprieto/src/zapier/great-expectations-zapier/venv/lib/python3.8/site-packages/great_expectations/execution_engine/sqlalchemy_execution_engine.py", line 507, in get_domain_records
selectable = selectable.columns().subquery()
AttributeError: 'TextAsFrom' object has no attribute 'subquery'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/Users/ramonprieto/src/zapier/great-expectations-zapier/venv/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 1265, in resolve_validation_graph
self._resolve_metrics(
File "/Users/ramonprieto/src/zapier/great-expectations-zapier/venv/lib/python3.8/site-packages/great_expectations/validator/validator.py", line 2173, in _resolve_metrics
return execution_engine.resolve_metrics(
File "/Users/ramonprieto/src/zapier/great-expectations-zapier/venv/lib/python3.8/site-packages/great_expectations/execution_engine/execution_engine.py", line 401, in resolve_metrics
raise ge_exceptions.MetricResolutionError(
great_expectations.exceptions.exceptions.MetricResolutionError: 'TextAsFrom' object has no attribute 'subquery'
```

**Comment by rslanka** [comment]
We have now moved to GE version [>=0.5.12](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/setup.py#L114). Closing.
