### ISSUE TITLE
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number

### ISSUE THREAD

**Issue by sachinwadhwa** [datahub-project/datahub#5286]
**Describe the bug**
Since upgrade to 0.8.39 we are getting following error while ingesting data from Hive (profiling enabled):

[2022-06-29 14:48:29,531] ERROR    {datahub.ingestion.source.ge_data_profiler:327} - Failed to get unique count for column bronze_kambi.rewards.ReceivedTime
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/datahub/ingestion/source/ge_data_profiler.py", line 323, in _get_column_cardinality
    unique_count = self.dataset.get_column_unique_count(column)
  File "/usr/local/lib/python3.10/site-packages/datahub/ingestion/source/ge_data_profiler.py", line 133, in get_column_unique_count_patch
    self.engine.execute(
  File "/usr/local/lib/python3.10/site-packages/datahub/utilities/sqlalchemy_query_combiner.py", line 265, in _sa_execute_fake
    return _sa_execute_underlying_method(conn, query, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1514, in _handle_dbapi_exception
    util.raise_(exc_info[1], with_traceback=exc_info[2])
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1296, in _execute_context
    result = context.get_result_proxy()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1244, in get_result_proxy
    return result.ResultProxy(self)
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 775, in __init__
    self._init_metadata()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 794, in _init_metadata
    cursor_description = self._cursor_description()
  File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 924, in _cursor_description
    return self._saved_cursor.description
  File "/usr/local/lib/python3.10/site-packages/pyhive/hive.py", line 422, in description
    response = self._connection.client.GetResultSetMetadata(req)
  File "/usr/local/lib/python3.10/site-packages/TCLIService/TCLIService.py", line 682, in GetResultSetMetadata
    self.send_GetResultSetMetadata(req)
  File "/usr/local/lib/python3.10/site-packages/TCLIService/TCLIService.py", line 691, in send_GetResultSetMetadata
    self._oprot.trans.flush()
  File "/usr/local/lib/python3.10/site-packages/thrift/transport/THttpClient.py", line 178, in flush
    self.__http.endheaders()
  File "/usr/local/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/local/lib/python3.10/http/client.py", line 1454, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)

**To Reproduce**
as above

**Expected behavior**
There was no error with previous version.

**Comment by treff7es** [comment]
Is this only happen with Profiling?

**Comment by sachinwadhwa** [comment]
Not it happens without profiling too.
