### ISSUE TITLE
Ingestion from MongoDB replica set fails

### ISSUE THREAD

**Issue by DSamuylov** [datahub-project/datahub#5319]
**Describe the bug**
When I use the UI to create a new replica set MongoDB source, the connection fails with the error: `The "dnspython" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv`.

**To Reproduce**
1. Go to UI
2. Click on 'Create new source'
3. Add the following recipe:
```
source:
    type: mongodb
    config:
        connect_uri: 'mongodb+srv://USERNAME:PASSWORD@URL/admin?authSource=admin&replicaSet=REPLICA_SET&tls=true'
        username: None
        password: None
        enableSchemaInference: true
        useRandomSampling: true
        maxSchemaSize: 300
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms:8080'
```

4. See error:

```
~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': 'ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7',
 'infos': ['2022-07-01 21:21:11.845997 [exec_id=ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7] INFO: Starting execution for task with name=RUN_INGEST',
           '2022-07-01 21:21:34.735839 [exec_id=ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7] INFO: stdout=Requirement already satisfied: pip in '
           '/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages (21.2.4)\n'
           'Collecting pip\n'
           '  Using cached pip-22.1.2-py3-none-any.whl (2.1 MB)\n'
           'Collecting wheel\n'
           '  Using cached wheel-0.37.1-py2.py3-none-any.whl (35 kB)\n'
           'Requirement already satisfied: setuptools in /tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages '
           '(58.1.0)\n'
           'Collecting setuptools\n'
           '  Using cached setuptools-62.6.0-py3-none-any.whl (1.2 MB)\n'
           'Installing collected packages: wheel, setuptools, pip\n'
           '  Attempting uninstall: setuptools\n'
           '    Found existing installation: setuptools 58.1.0\n'
           '    Uninstalling setuptools-58.1.0:\n'
           '      Successfully uninstalled setuptools-58.1.0\n'
           '  Attempting uninstall: pip\n'
           '    Found existing installation: pip 21.2.4\n'
           '    Uninstalling pip-21.2.4:\n'
           '      Successfully uninstalled pip-21.2.4\n'
           'Successfully installed pip-22.1.2 setuptools-62.6.0 wheel-0.37.1\n'
           'Collecting acryl-datahub[datahub-rest,mongodb]==0.8.40\n'
           '  Using cached acryl_datahub-0.8.40-py3-none-any.whl (903 kB)\n'
           'Collecting expandvars>=0.6.5\n'
           '  Using cached expandvars-0.9.0-py3-none-any.whl (6.6 kB)\n'
           'Collecting psutil>=5.8.0\n'
           '  Using cached psutil-5.9.1-cp39-cp39-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (281 '
           'kB)\n'
           'Collecting termcolor>=1.0.0\n'
           '  Using cached termcolor-1.1.0-py3-none-any.whl\n'
           'Collecting types-termcolor>=1.0.0\n'
           '  Using cached types_termcolor-1.1.5-py3-none-any.whl (2.2 kB)\n'
           'Collecting stackprinter\n'
           '  Using cached stackprinter-0.2.6-py3-none-any.whl (28 kB)\n'
           'Collecting types-Deprecated\n'
           '  Using cached types_Deprecated-1.2.9-py3-none-any.whl (3.2 kB)\n'
           'Collecting click-default-group\n'
           '  Using cached click_default_group-1.2.2-py3-none-any.whl\n'
           'Collecting typing-inspect\n'
           '  Using cached typing_inspect-0.7.1-py3-none-any.whl (8.4 kB)\n'
           'Collecting markupsafe<=2.0.1,>=1.1.1\n'
           '  Using cached MarkupSafe-2.0.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (30 kB)\n'
           'Collecting python-dateutil>=2.8.0\n'
           '  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)\n'
           'Collecting mixpanel>=4.9.0\n'
           '  Using cached mixpanel-4.9.0-py2.py3-none-any.whl (8.9 kB)\n'
           'Collecting mypy-extensions>=0.4.3\n'
           '  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)\n'
           'Collecting tabulate\n'
           '  Using cached tabulate-0.8.10-py3-none-any.whl (29 kB)\n'
           'Collecting entrypoints\n'
           '  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)\n'
           'Collecting typing-extensions>=3.10.0.2\n'
           '  Using cached typing_extensions-4.3.0-py3-none-any.whl (25 kB)\n'
           'Collecting progressbar2\n'
           '  Using cached progressbar2-4.0.0-py2.py3-none-any.whl (26 kB)\n'
           'Collecting avro<1.11,>=1.10.2\n'
           '  Using cached avro-1.10.2-py3-none-any.whl\n'
           'Collecting Deprecated\n'
           '  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)\n'
           'Collecting humanfriendly\n'
           '  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)\n'
           'Collecting PyYAML\n'
           '  Using cached PyYAML-6.0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (661 kB)\n'
           'Collecting pydantic>=1.5.1\n'
           '  Using cached pydantic-1.9.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.4 MB)\n'
           'Collecting ratelimiter\n'
           '  Using cached ratelimiter-1.2.0.post0-py3-none-any.whl (6.6 kB)\n'
           'Collecting click>=6.0.0\n'
           '  Using cached click-8.1.3-py3-none-any.whl (96 kB)\n'
           'Collecting toml>=0.10.0\n'
           '  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)\n'
           'Collecting docker\n'
           '  Using cached docker-5.0.3-py2.py3-none-any.whl (146 kB)\n'
           'Collecting avro-gen3==0.7.4\n'
           '  Using cached avro_gen3-0.7.4-py3-none-any.whl (26 kB)\n'
           'Collecting packaging\n'
           '  Using cached packaging-21.3-py3-none-any.whl (40 kB)\n'
           'Collecting pymongo>=3.11\n'
           '  Using cached pymongo-4.1.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (471 kB)\n'
           'Collecting requests\n'
           '  Using cached requests-2.28.1-py3-none-any.whl (62 kB)\n'
           'Collecting six\n'
           '  Using cached six-1.16.0-py2.py3-none-any.whl (11 kB)\n'
           'Collecting pytz\n'
           '  Using cached pytz-2022.1-py2.py3-none-any.whl (503 kB)\n'
           'Collecting tzlocal\n'
           '  Using cached tzlocal-4.2-py3-none-any.whl (19 kB)\n'
           'Collecting urllib3\n'
           '  Using cached urllib3-1.26.9-py2.py3-none-any.whl (138 kB)\n'
           'Collecting charset-normalizer<3,>=2\n'
           '  Using cached charset_normalizer-2.1.0-py3-none-any.whl (39 kB)\n'
           'Collecting idna<4,>=2.5\n'
           '  Using cached idna-3.3-py3-none-any.whl (61 kB)\n'
           'Collecting certifi>=2017.4.17\n'
           '  Using cached certifi-2022.6.15-py3-none-any.whl (160 kB)\n'
           'Collecting wrapt<2,>=1.10\n'
           '  Using cached wrapt-1.14.1-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (77 kB)\n'
           'Collecting websocket-client>=0.32.0\n'
           '  Using cached websocket_client-1.3.3-py3-none-any.whl (54 kB)\n'
           'Collecting pyparsing!=3.0.5,>=2.0.2\n'
           '  Using cached pyparsing-3.0.9-py3-none-any.whl (98 kB)\n'
           'Collecting python-utils>=3.0.0\n'
           '  Using cached python_utils-3.3.3-py2.py3-none-any.whl (23 kB)\n'
           'Collecting pytz-deprecation-shim\n'
           '  Using cached pytz_deprecation_shim-0.1.0.post0-py2.py3-none-any.whl (15 kB)\n'
           'Collecting tzdata\n'
           '  Using cached tzdata-2022.1-py2.py3-none-any.whl (339 kB)\n'
           'Installing collected packages: types-termcolor, types-Deprecated, termcolor, ratelimiter, pytz, mypy-extensions, wrapt, '
           'websocket-client, urllib3, tzdata, typing-extensions, toml, tabulate, stackprinter, six, PyYAML, python-utils, pyparsing, pymongo, '
           'psutil, markupsafe, idna, humanfriendly, expandvars, entrypoints, click, charset-normalizer, certifi, avro, typing-inspect, requests, '
           'pytz-deprecation-shim, python-dateutil, pydantic, progressbar2, packaging, Deprecated, click-default-group, tzlocal, mixpanel, docker, '
           'avro-gen3, acryl-datahub\n'
           'Successfully installed Deprecated-1.2.13 PyYAML-6.0 acryl-datahub-0.8.40 avro-1.10.2 avro-gen3-0.7.4 certifi-2022.6.15 '
           'charset-normalizer-2.1.0 click-8.1.3 click-default-group-1.2.2 docker-5.0.3 entrypoints-0.4 expandvars-0.9.0 humanfriendly-10.0 idna-3.3 '
           'markupsafe-2.0.1 mixpanel-4.9.0 mypy-extensions-0.4.3 packaging-21.3 progressbar2-4.0.0 psutil-5.9.1 pydantic-1.9.1 pymongo-4.1.1 '
           'pyparsing-3.0.9 python-dateutil-2.8.2 python-utils-3.3.3 pytz-2022.1 pytz-deprecation-shim-0.1.0.post0 ratelimiter-1.2.0.post0 '
           'requests-2.28.1 six-1.16.0 stackprinter-0.2.6 tabulate-0.8.10 termcolor-1.1.0 toml-0.10.2 types-Deprecated-1.2.9 types-termcolor-1.1.5 '
           'typing-extensions-4.3.0 typing-inspect-0.7.1 tzdata-2022.1 tzlocal-4.2 urllib3-1.26.9 websocket-client-1.3.3 wrapt-1.14.1\n'
           '[2022-07-01 21:21:34,203] INFO     {datahub.cli.ingest_cli:99} - DataHub CLI version: 0.8.40\n'
           '[2022-07-01 21:21:34,586] ERROR    {datahub.entrypoints:167} - File '
           '"/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 106, in run\n'
           '    88   def run(\n'
           '    89       ctx: click.Context,\n'
           '    90       config: str,\n'
           '    91       dry_run: bool,\n'
           '    92       preview: bool,\n'
           '    93       strict_warnings: bool,\n'
           '    94       preview_workunits: int,\n'
           '    95       suppress_error_logs: bool,\n'
           '    96   ) -> None:\n'
           ' (...)\n'
           '    102      pipeline_config = load_config_file(config_file)\n'
           '    103  \n'
           '    104      try:\n'
           '    105          logger.debug(f"Using config: {pipeline_config}")\n'
           '--> 106          pipeline = Pipeline.create(pipeline_config, dry_run, preview, preview_workunits)\n'
           '    107      except ValidationError as e:\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line '
           '204, in create\n'
           '    196  def create(\n'
           '    197      cls,\n'
           '    198      config_dict: dict,\n'
           '    199      dry_run: bool = False,\n'
           '    200      preview_mode: bool = False,\n'
           '    201      preview_workunits: int = 10,\n'
           '    202  ) -> "Pipeline":\n'
           '    203      config = PipelineConfig.parse_obj(config_dict)\n'
           '--> 204      return cls(\n'
           '    205          config,\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line '
           '152, in __init__\n'
           '    125  def __init__(\n'
           '    126      self,\n'
           '    127      config: PipelineConfig,\n'
           '    128      dry_run: bool = False,\n'
           '    129      preview_mode: bool = False,\n'
           '    130      preview_workunits: int = 10,\n'
           '    131  ):\n'
           ' (...)\n'
           '    148      logger.debug(f"Sink type:{self.config.sink.type},{sink_class} configured")\n'
           '    149  \n'
           '    150      source_type = self.config.source.type\n'
           '    151      source_class = source_registry.get(source_type)\n'
           '--> 152      self.source: Source = source_class.create(\n'
           '    153          self.config.source.dict().get("config", {}), self.ctx\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/source/mongodb.py", '
           'line 249, in create\n'
           '    246  @classmethod\n'
           '    247  def create(cls, config_dict: dict, ctx: PipelineContext) -> "MongoDBSource":\n'
           '    248      config = MongoDBConfig.parse_obj(config_dict)\n'
           '--> 249      return cls(ctx, config)\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/source/mongodb.py", '
           'line 240, in __init__\n'
           '    223  def __init__(self, ctx: PipelineContext, config: MongoDBConfig):\n'
           ' (...)\n'
           '    236          **options,\n'
           '    237          **self.config.options,\n'
           '    238      }\n'
           '    239  \n'
           '--> 240      self.mongo_client = pymongo.MongoClient(self.config.connect_uri, **options)  # type: ignore\n'
           '    241  \n'
           '\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/pymongo/mongo_client.py", line 704, in '
           '__init__\n'
           '    120  def __init__(\n'
           '    121      self,\n'
           '    122      host: Optional[Union[str, Sequence[str]]] = None,\n'
           '    123      port: Optional[int] = None,\n'
           '    124      document_class: Optional[Type[_DocumentType]] = None,\n'
           '    125      tz_aware: Optional[bool] = None,\n'
           '    126      connect: Optional[bool] = None,\n'
           '    127      type_registry: Optional[TypeRegistry] = None,\n'
           '    128      **kwargs: Any,\n'
           '    129  ) -> None:\n'
           ' (...)\n'
           '    700              if timeout is not None:\n'
           '    701                  timeout = common.validate_timeout_or_none_or_zero(\n'
           '    702                      keyword_opts.cased_key("connecttimeoutms"), timeout\n'
           '    703                  )\n'
           '--> 704              res = uri_parser.parse_uri(\n'
           '    705                  entity,\n'
           '\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/pymongo/uri_parser.py", line 469, in '
           'parse_uri\n'
           '    403  def parse_uri(\n'
           '    404      uri: str,\n'
           '    405      default_port: Optional[int] = DEFAULT_PORT,\n'
           '    406      validate: bool = True,\n'
           '    407      warn: bool = False,\n'
           '    408      normalize: bool = True,\n'
           '    409      connect_timeout: Optional[float] = None,\n'
           '    410      srv_service_name: Optional[str] = None,\n'
           '    411      srv_max_hosts: Optional[int] = None,\n'
           '    412  ) -> Dict[str, Any]:\n'
           ' (...)\n'
           '    465          scheme_free = uri[SCHEME_LEN:]\n'
           '    466      elif uri.startswith(SRV_SCHEME):\n'
           '    467          if not _HAVE_DNSPYTHON:\n'
           '    468              python_path = sys.executable or "python"\n'
           '--> 469              raise ConfigurationError(\n'
           '    470                  \'The "dnspython" module must be \'\n'
           '\n'
           '---- (full traceback above) ----\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 106, in '
           'run\n'
           '    pipeline = Pipeline.create(pipeline_config, dry_run, preview, preview_workunits)\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line '
           '204, in create\n'
           '    return cls(\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line '
           '152, in __init__\n'
           '    self.source: Source = source_class.create(\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/source/mongodb.py", '
           'line 249, in create\n'
           '    return cls(ctx, config)\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/ingestion/source/mongodb.py", '
           'line 240, in __init__\n'
           '    self.mongo_client = pymongo.MongoClient(self.config.connect_uri, **options)  # type: ignore\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/pymongo/mongo_client.py", line 704, in '
           '__init__\n'
           '    res = uri_parser.parse_uri(\n'
           'File "/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/pymongo/uri_parser.py", line 469, in '
           'parse_uri\n'
           '    raise ConfigurationError(\n'
           '\n'
           'ConfigurationError: The "dnspython" module must be installed to use mongodb+srv:// URIs. To fix this error install pymongo with the srv '
           'extra:\n'
           ' /tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/bin/python3 -m pip install "pymongo[srv]"\n'
           '[2022-07-01 21:21:34,586] INFO     {datahub.entrypoints:176} - DataHub CLI version: 0.8.40 at '
           '/tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/lib/python3.9/site-packages/datahub/__init__.py\n'
           '[2022-07-01 21:21:34,586] INFO     {datahub.entrypoints:179} - Python version: 3.9.9 (main, Dec 21 2021, 10:03:34) \n'
           '[GCC 10.2.1 20210110] at /tmp/datahub/ingest/venv-ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7/bin/python3 on '
           'Linux-5.4.0-120-generic-x86_64-with-glibc2.31\n'
           "[2022-07-01 21:21:34,586] INFO     {datahub.entrypoints:182} - GMS config {'models': {}, 'versions': {'linkedin/datahub': {'version': "
           "'v0.8.40', 'commit': 'b02c7f595246312ecf7cdfd6bd113e48c72b67b4'}}, 'managedIngestion': {'defaultCliVersion': '0.8.40', 'enabled': True}, "
           "'statefulIngestionCapable': True, 'supportsImpactAnalysis': True, 'telemetry': {'enabledCli': True, 'enabledIngestion': False}, "
           "'datasetUrnNameCasing': False, 'retention': 'true', 'datahub': {'serverType': 'quickstart'}, 'noCode': 'true'}\n",
           "2022-07-01 21:21:34.735998 [exec_id=ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7] INFO: Failed to execute 'datahub ingest'",
           '2022-07-01 21:21:34.736358 [exec_id=ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7] INFO: Caught exception EXECUTING '
           'task_id=ae0c8d82-a160-4e21-bf87-c2f41b6cb3e7, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/default_executor.py", line 121, in execute_task\n'
           '    self.event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete\n'
           '    return f.result()\n'
           '  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result\n'
           '    raise self._exception\n'
           '  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step\n'
           '    result = coro.send(None)\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 115, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"]}
Execution finished with errors.
```

**Expected behavior**
The data source is successfully connected. It seems that the problem could be solved by installing MongoDB using`python -m pip install pymongo[srv]`.

**Desktop (please complete the following information):**
 - Version 0.8.40 (started using `datahub docker quickstart`)

**Additional context**
NA

**Comment by DSamuylov** [comment]
It is still an open issue.
