### ISSUE TITLE
yarnTest error  - v.0.8.38

### ISSUE THREAD

**Issue by muyable** [datahub-project/datahub#5323]
```
          at MockedProvider (/datahub/datahub-web-react/node_modules/@apollo/client/utilities/testing/mocking/MockedProvider.js:10:28)

      44 |     const recommendationModules = data?.listRecommendations?.modules;
      45 |     return (
    > 46 |         <RecommendationsContainer>
         |         ^
      47 |             {recommendationModules &&
      48 |                 recommendationModules.map((module) => (
      49 |                     <RecommendationContainer>

      at printWarning (node_modules/react/cjs/react-jsx-dev-runtime.development.js:117:30)
      at error (node_modules/react/cjs/react-jsx-dev-runtime.development.js:93:5)
      at validateExplicitKey (node_modules/react/cjs/react-jsx-dev-runtime.development.js:986:5)
      at validateChildKeys (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1013:11)
      at jsxWithValidation (node_modules/react/cjs/react-jsx-dev-runtime.development.js:1184:11)
      at SidebarEntityRecommendations (src/app/entity/shared/containers/profile/sidebar/Recommendations/SidebarEntityRecommendations.tsx:46:9)
      at renderWithHooks (node_modules/react-dom/cjs/react-dom.development.js:14985:18)
      at updateFunctionComponent (node_modules/react-dom/cjs/react-dom.development.js:17356:20)

    console.error
      Warning: Each child in a list should have a unique "key" prop.
      
      Check the render method of `CompactEntityNameList`. See https://reactjs.org/link/warning-keys for more information.
```

**Comment by anshbansal** [comment]
Request you to please share 
- the exact command that you are running
- environment details of where you are running the command
- from what branch at what commit number you ran this
- whether you have made any changes in the code or not
- whether you are able to reproduce this on latest release or not

**Comment by jjoyce0510** [comment]
Don't worry - this is just a warning log.. It is not an error you need to be concerned with.

Closing the ticket!
John
