### ISSUE TITLE
after creating datahub locally through docker ,I am having issue with login .I am putting correct username and password for same 

### ISSUE THREAD

**Issue by kirantodekar123** [datahub-project/datahub#5512]
.........
Unable to run quickstart - the following issues were detected:
- elasticsearch-setup is still running
- kafka-setup is still running
- mysql-setup is still running
- datahub-gms is still starting
- elasticsearch is still starting

**Comment by xiphl** [comment]
the key issue seems to be that ES is not ready, hence causing your browsing experience to be glitched as backend is not ready. look at output of `docker logs elasticsearch`

**Comment by kirantodekar123** [comment]
uncaught exception in thread [main]
ElasticsearchException[Failure running machine learning native code. This could be due to running on an unsupported OS or distribution, missing OS libraries, or a problem with the temp directory. To bypass this problem by running Elasticsearch without machine learning functionality set [xpack.ml.enabled: false].]
	at org.elasticsearch.xpack.ml.MachineLearning.createComponents(MachineLearning.java:645)
	at org.elasticsearch.node.Node.lambda$new$14(Node.java:522)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:271)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
	at org.elasticsearch.node.Node.<init>(Node.java:526)
	at org.elasticsearch.node.Node.<init>(Node.java:277)
	at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:227)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:393)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:170)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:161)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:127)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:126)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:92)
For complete error details, refer to the log at /usr/share/elasticsearch/logs/docker-cluster.log

**Comment by xiphl** [comment]
are you using the default image or have some special settings

**Comment by kirantodekar123** [comment]
I think its default image

**Comment by xiphl** [comment]
you will need to resolve the elasticsearch problem before the rest of the containers can work properly.
perhaps https://stackoverflow.com/questions/56126244/unable-to-start-elasticsearch-in-my-machine-startupexception-is-occuring-while is relevant to you

if you're using `datahub docker quickstart`, you will probably need to download one of the quickstart yml like https://github.com/datahub-project/datahub/blob/master/docker/quickstart/docker-compose-without-neo4j.quickstart.yml, make changes to disable xpack.ml module 
then rerun `datahub docker quickstart --quickstart-compose-file ./your-compose-file.yml`

**Comment by kirantodekar123** [comment]
ERROR: The Compose file './elasticsrc.yaml' is invalid because:
services.elasticsearch.environment contains {"xpack.ml.enabled": false}, which is an invalid type, it should be a string

**Comment by xiphl** [comment]
is it not written as 
elasticsearch:   
    container_name: elasticsearch  
    environment:  
    - discovery.type=single-node  
    - xpack.security.enabled=false  
    - xpack.ml.enabled=false
    - ES_JAVA_OPTS=-Xms256m -Xmx256m -Dlog4j2.formatMsgNoLookups=true
 ?

**Comment by kirantodekar123** [comment]
Thanks .One issue got resolved I can able to logon now but still  Have some issue .getting some issue with UI after login 

Unable to run quickstart - the following issues were detected:
- datahub-gms is running but not healthy
- kafka-setup is still running

please help

**Comment by kirantodekar123** [comment]
[2022-07-29 19:42:36,023] INFO     {datahub.cli.ingest_cli:170} - DataHub CLI version: 0.8.41.2
[2022-07-29 19:42:36,346] INFO     {datahub.ingestion.run.pipeline:163} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://localhost:8080
Illegal instruction (core dumped)


data ingestion also not succesfull

**Comment by xiphl** [comment]
Outputs for 
docker logs kafka-setup
docker logs broker
GMS needs to be healthy to do anything properly.

**Comment by kirantodekar123** [comment]
[2022-07-29 19:42:36,023] INFO     {datahub.cli.ingest_cli:170} - DataHub CLI version: 0.8.41.2
[2022-07-29 19:42:36,346] INFO     {datahub.ingestion.run.pipeline:163} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://localhost:8080
Illegal instruction (core dumped)


data ingestion also not succesfullffsets-45 -> Vector(1), __consumer_offsets-1 -> Vector(1), __consumer_offsets-5 -> Vector(1), __consumer_offsets-26 -> Vector(1), __consumer_offsets-29 -> Vector(1), __consumer_offsets-34 -> Vector(1), __consumer_offsets-10 -> Vector(1), __consumer_offsets-32 -> Vector(1), __consumer_offsets-40 -> Vector(1))) (kafka.controller.KafkaController)
[2022-08-01 05:25:27,278] DEBUG [Controller id=1] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
[2022-08-01 05:25:27,279] TRACE [Controller id=1] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)
[2022-08-01 05:30:15,066] INFO [GroupMetadataManager brokerId=1] Removed 0 expired offsets in 0 milliseconds. (kafka.coordinator.group.GroupMetadataManager)
[2022-08-01 05:30:27,279] INFO [Controller id=1] Processing automatic preferred replica leader election (kafka.controller.KafkaController)
[2022-08-01 05:30:27,280] TRACE [Controller id=1] Checking need to trigger auto leader balancing (kafka.controller.KafkaController)
[2022-08-01 05:30:27,281] DEBUG [Controller id=1] Preferred replicas by broker Map(1 -> Map(__consumer_offsets-22 -> Vector(1), __consumer_offsets-30 -> Vector(1), __consumer_offsets-8 -> Vector(1), __consumer_offsets-21 -> Vector(1), __consumer_offsets-4 -> Vector(1), __consumer_offsets-27 -> Vector(1), __consumer_offsets-7 -> Vector(1), PlatformEvent_v1-0 -> Vector(1), __consumer_offsets-9 -> Vector(1), __consumer_offsets-46 -> Vector(1), __consumer_offsets-25 -> Vector(1), __consumer_offsets-35 -> Vector(1), __consumer_offsets-41 -> Vector(1), __consumer_offsets-33 -> Vector(1), __consumer_offsets-23 -> Vector(1), __consumer_offsets-49 -> Vector(1), _schemas-0 -> Vector(1), MetadataChangeEvent_v4-0 -> Vector(1), __consumer_offsets-47 -> Vector(1), MetadataChangeLog_Timeseries_v1-0 -> Vector(1), __consumer_offsets-16 -> Vector(1), __consumer_offsets-28 -> Vector(1), __consumer_offsets-31 -> Vector(1), __consumer_offsets-36 -> Vector(1), __consumer_offsets-42 -> Vector(1), __consumer_offsets-3 -> Vector(1), __consumer_offsets-18 -> Vector(1), __consumer_offsets-37 -> Vector(1), __consumer_offsets-15 -> Vector(1), __consumer_offsets-24 -> Vector(1), MetadataChangeProposal_v1-0 -> Vector(1), DataHubUsageEvent_v1-0 -> Vector(1), __consumer_offsets-38 -> Vector(1), __consumer_offsets-17 -> Vector(1), __consumer_offsets-48 -> Vector(1), __confluent.support.metrics-0 -> Vector(1), __consumer_offsets-19 -> Vector(1), __consumer_offsets-11 -> Vector(1), FailedMetadataChangeEvent_v4-0 -> Vector(1), __consumer_offsets-13 -> Vector(1), __consumer_offsets-2 -> Vector(1), __consumer_offsets-43 -> Vector(1), __consumer_offsets-6 -> Vector(1), __consumer_offsets-14 -> Vector(1), MetadataAuditEvent_v4-0 -> Vector(1), FailedMetadataChangeProposal_v1-0 -> Vector(1), MetadataChangeLog_Versioned_v1-0 -> Vector(1), __consumer_offsets-20 -> Vector(1), __consumer_offsets-0 -> Vector(1), __consumer_offsets-44 -> Vector(1), __consumer_offsets-39 -> Vector(1), __consumer_offsets-12 -> Vector(1), __consumer_offsets-45 -> Vector(1), __consumer_offsets-1 -> Vector(1), __consumer_offsets-5 -> Vector(1), __consumer_offsets-26 -> Vector(1), __consumer_offsets-29 -> Vector(1), __consumer_offsets-34 -> Vector(1), __consumer_offsets-10 -> Vector(1), __consumer_offsets-32 -> Vector(1), __consumer_offsets-40 -> Vector(1))) (kafka.controller.KafkaController)
[2022-08-01 05:30:27,281] DEBUG [Controller id=1] Topics not in preferred replica for broker 1 Map() (kafka.controller.KafkaController)
[2022-08-01 05:30:27,281] TRACE [Controller id=1] Leader imbalance ratio for broker 1 is 0.0 (kafka.controller.KafkaController)

**Comment by xiphl** [comment]
The logs probably look normal. Does docker logs datahub-gms say why it is not healthy?

**Comment by kirantodekar123** [comment]
is it possible for you to connect with me and solve the issue ?

**Comment by xiphl** [comment]
if you need consultation i suggest you look for the #office-hours channel in Slack, Github issues is a slow channel for troubleshooting

**Comment by pedro93** [comment]
Helli @kirantodekar123 

What operating system are you running?
What is your version of Docker and how much disk and memory is it configured with?

**Comment by kirantodekar123** [comment]
I am running with ubuntu os and Docker version 20.10.17, build 100c701.Memory is 8GB of RAM

**Comment by pedro93** [comment]
DataHub deployment requires more than 8GB to run because of the prerequisite software (elastic search, Kafka & a relational DB). A minimum would be 12GB at least, 16GB to be safe.

**Comment by denisov-vlad** [comment]
Having the same issue on Mac (12 GB RAM for docker), Windows (64GB) and Linux (64GB). A week ago everything worked fine on 8GB ram linux machine.

**Comment by kirantodekar123** [comment]
I request please close this issue . It has been rectified . Thank You team for your support

**Comment by kirantodekar123** [comment]
resolved
