### ISSUE TITLE
Error when trying to ingest Vertica Views. 

### ISSUE THREAD

**Issue by hemanth-marukala** [datahub-project/datahub#5674]
When trying to ingest data from Vertica using the latest vertica plugin in Datahub version 0.8.43 i get the below error. Followed instruction to ingest based on the below link https://datahubproject.io/docs/generated/ingestion/sources/vertica/

Looks like datahub looks for pg_class tables instead of v_catalog.views table. 

**Below are the logs when trying to run the ingest for Vertica DB.** 

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/datahub/ingestion/source/sql/sql_common.py", line 1175, in loop_views
    yield from self._process_view(
  File "/usr/local/lib/python3.8/dist-packages/datahub/ingestion/source/sql/sql_common.py", line 1219, in _process_view
    view_definition = inspector.get_view_definition(view, schema)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 337, in get_view_definition
    return self.dialect.get_view_definition(
  File "<string>", line 2, in get_view_definition
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/reflection.py", line 52, in cache
    ret = fn(self, con, *args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/dialects/postgresql/base.py", line 3022, in get_view_definition
    view_def = connection.scalar(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 941, in scalar
    return self.execute(object_, *multiparams, **params).scalar()
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1011, in execute
    return meth(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/sql/elements.py", line 298, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1124, in _execute_clauseelement
    ret = self._execute_context(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.8/dist-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
  File "/usr/local/lib/python3.8/dist-packages/vertica_python/vertica/cursor.py", line 222, in execute
    self._execute_simple_query(operation)
  File "/usr/local/lib/python3.8/dist-packages/vertica_python/vertica/cursor.py", line 606, in _execute_simple_query
    raise errors.QueryError.from_error_response(self._message, query)
sqlalchemy.exc.ProgrammingError: (vertica_python.errors.MissingRelation) Severity: ERROR, Message: Relation "pg_class" does not exist, Sqlstate: 42V01, Routine: throwRelationDoesNotExist, File: /data/jenkins/workspace/RE-ReleaseBuilds/RE-Knuckleboom/server/vertica/Catalog/CatalogLookup.cpp, Line: 4118, Error Code: 4566, SQL: "SELECT pg_get_viewdef(c.oid) view_def FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = 'dominodatalab_schema' AND c.relname = 'csv_telco_view' AND c.relkind IN ('v', 'm')"
[SQL: SELECT pg_get_viewdef(c.oid) view_def FROM pg_class c JOIN pg_namespace n ON n.oid = c.relnamespace WHERE n.nspname = :schema AND c.relname = :view_name AND c.relkind IN ('v', 'm')]
[parameters: {'schema': 'dominodatalab_schema', 'view_name': 'csv_telco_view'}]
(Background on this error at: http://sqlalche.me/e/13/f405)

**Comment by hemanth-marukala** [comment]
It worked with a clean install of Datahub 0.8.43
