### ISSUE TITLE
Ingestion from Oracle databases has started to fail from v0.8.43.4

### ISSUE THREAD

**Issue by daha** [datahub-project/datahub#5905]
**Describe the bug**

Ingesting metadata from our Oracle databases has started to fail since docker image acryldata/datahub-ingestion:v0.8.43.4 (actually already from acryldata/datahub-ingestion:v0.8.43.4rc1) with the PR #5592.

**To Reproduce**

1. Run ingest with the oracle source. 

I get the stack trace below:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00942: tabell eller vy finns inte

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/datahub/entrypoints.py", line 149, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line 343, in wrapper
    raise e
  File "/usr/local/lib/python3.9/site-packages/datahub/telemetry/telemetry.py", line 295, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datahub/utilities/memory_leak_detector.py", line 102, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 205, in run
    loop.run_until_complete(run_func_check_upgrade(pipeline))
  File "/usr/local/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 161, in run_func_check_upgrade
    ret = await the_one_future
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 152, in run_pipeline_async
    return await loop.run_in_executor(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 143, in run_pipeline_to_completion
    raise e
  File "/usr/local/lib/python3.9/site-packages/datahub/cli/ingest_cli.py", line 129, in run_pipeline_to_completion
    pipeline.run()
  File "/usr/local/lib/python3.9/site-packages/datahub/ingestion/run/pipeline.py", line 334, in run
    for wu in itertools.islice(
  File "/usr/local/lib/python3.9/site-packages/datahub/ingestion/source/sql/sql_common.py", line 737, in get_workunits
    for schema in self.get_schema_names(inspector):
  File "/usr/local/lib/python3.9/site-packages/datahub/ingestion/source/sql/sql_common.py", line 591, in get_schema_names
    return inspector.get_schema_names()
  File "/usr/local/lib/python3.9/site-packages/datahub/ingestion/source/sql/oracle.py", line 95, in get_schema_names
    cursor = self._inspector_instance.bind.execute(s)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
    return self._execute_text(object_, multiparams, params)
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
    ret = self._execute_context(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
    self._handle_dbapi_exception(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
    util.raise_(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
    raise exception
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/usr/local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00942: tabell eller vy finns inte
[SQL: SELECT username FROM dba_users ORDER BY username]
(Background on this error at: http://sqlalche.me/e/13/4xp6)
[2022-09-12 10:09:18,299] ERROR    {datahub.entrypoints:195} - Command failed: 
	(cx_Oracle.DatabaseError) ORA-00942: tabell eller vy finns inte
[SQL: SELECT username FROM dba_users ORDER BY username]
(Background on this error at: http://sqlalche.me/e/13/4xp6) due to 
		'ORA-00942: tabell eller vy finns inte'.
```

**Expected behavior**
The ingestion should run without crashes like before v0.8.43.4.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**
Datahub version v0.8.43.4

With oracle drivers from this docker image ghcr.io/oracle/oraclelinux8-instantclient:21 (installed to a docker image based on acryldata/datahub-ingestion:v0.8.43.4)

Commands which addes the Oracle driver in the datahub-ingestion docker image:
``` Dockerfile
USER 0

# Installs oracle libs and make them available
COPY --from=ghcr.io/oracle/oraclelinux8-instantclient:21 /usr/lib/oracle /usr/lib/oracle
COPY --from=ghcr.io/oracle/oraclelinux8-instantclient:21 /etc/ld.so.conf.d/oracle-instantclient.conf /etc/ld.so.conf.d/oracle-instantclient.conf
# Run ldconfig to make the new libs available
RUN ldconfig

USER datahub
```

Oracle server version:
Oracle Database 19c Enterprise Edition Release 19.0.0.0.0 - Production

**Comment by mohdsiddique** [comment]
Hi @daha 
Could you please check if the user has the permission on dba_users table.

**Comment by daha** [comment]
It does not look like the database user I'm using has permissions on dba_users table as I get an error message like above "ORA-00942: table or view does not exist". 

There is one other Oracle database where the ingestion works even with version 0.8.43.4, where my user has permissions to the dba_users table as "select * from dba_users;" works.

**Comment by daha** [comment]
Have you clearly documented that permission to dba_users table is required for the Oracle source?
