### ISSUE TITLE
UI ingestion Failed 

### ISSUE THREAD

**Issue by MahmoudElhalwany** [datahub-project/datahub#6003]
**Describe the bug**
When I am trying to make ingestion through UI it fails but it's worked through CLI

**To Reproduce**
1. Fronted
2. Ingestion
3. Create Custom Ingestion
4. 
```
source:
    type: clickhouse
    config:
        host_port: '**.**.**.**:8123'
        username: User
        password: Password
        database: DB
        include_views: true
        include_tables: true
        stateful_ingestion:
            enabled: true
            remove_stale_metadata: true
pipeline_name: clickhouse-reporting_pipeline_1
datahub_api:
    server: 'datahub-datahub-gms'
sink:
    type: datahub-kafka
    config:
        connection:
            bootstrap: 'prerequisites-kafka'
            schema_registry_url: 'prerequisites-cp-schema-registry
```

it gives me this error 
```
~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': 'fca7f6ab-805a-4ffb-bcaf-91f25f7773a0',
 'infos': ['2022-09-20 16:27:03.624167 [exec_id=fca7f6ab-805a-4ffb-bcaf-91f25f7773a0] INFO: Starting execution for task with name=RUN_INGEST',
           '2022-09-20 16:27:03.624620 [exec_id=fca7f6ab-805a-4ffb-bcaf-91f25f7773a0] INFO: Caught exception EXECUTING '
           'task_id=fca7f6ab-805a-4ffb-bcaf-91f25f7773a0, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/default_executor.py", line 121, in execute_task\n'
           '    self.event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.9/site-packages/nest_asyncio.py", line 89, in run_until_complete\n'
           '    return f.result()\n'
           '  File "/usr/local/lib/python3.9/asyncio/futures.py", line 201, in result\n'
           '    raise self._exception\n'
           '  File "/usr/local/lib/python3.9/asyncio/tasks.py", line 256, in __step\n'
           '    result = coro.send(None)\n'
           '  File "/usr/local/lib/python3.9/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 71, in execute\n'
           '    validated_args = SubProcessIngestionTaskArgs.parse_obj(args)\n'
           '  File "pydantic/main.py", line 521, in pydantic.main.BaseModel.parse_obj\n'
           '  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__\n'
           'pydantic.error_wrappers.ValidationError: 1 validation error for SubProcessIngestionTaskArgs\n'
           'debug_mode\n'
           '  extra fields not permitted (type=value_error.extra)\n']}
Execution finished with errors.
```

**Comment by jjoyce0510** [comment]
Please upgrade to the latest version of datahub-actions `v0.0.7`. This is addressed there!

**Comment by jjoyce0510** [comment]
Closing the issue. Let us know if upgrading does not work for you!

John

**Comment by MahmoudElhalwany** [comment]
> Please upgrade to the latest version of datahub-actions `v0.0.7`. This is addressed there!

my datahub version is `v0.8.44` !

**Comment by MahmoudElhalwany** [comment]
> Closing the issue. Let us know if upgrading does not work for you!
> 
> John

my datahub version is v0.8.44 !
