### ISSUE TITLE
[S3|JSON] Schema is not infered if domain is set through "simple_add_dataset_domain"

### ISSUE THREAD

**Issue by livelace** [datahub-project/datahub#6233]
**version**: 0.9.0

schema will be infered:

```yaml
source:
  type: "s3"
  config:
    aws_config:
      aws_access_key_id: ${MINIO_ACCESS_KEY}
      aws_secret_access_key: ${MINIO_SECRET_KEY}
      aws_region: "us-east-2"
      aws_endpoint_url: "https://minio.example.com"

    profiling:
      enabled: false

    path_specs:
      - include: "s3://bucket/file.json"

transformers:
  - type: "simple_add_dataset_tags"
    config:
      tag_urns:
        - "urn:li:tag:solr"
```

schema will **NOT** be infered (schema will be blanked in the UI):

```yaml
source:
  type: "s3"
  config:
    aws_config:
      aws_access_key_id: ${MINIO_ACCESS_KEY}
      aws_secret_access_key: ${MINIO_SECRET_KEY}
      aws_region: "us-east-2"
      aws_endpoint_url: "https://minio.example.com"

    profiling:
      enabled: false

    path_specs:
      - include: "s3://bucket/file.json"

transformers:
  - type: "simple_add_dataset_tags"
    config:
      tag_urns:
        - "urn:li:tag:solr"
  
  - type: "simple_add_dataset_domain"
    config:
      replace_existing: true
      domains:
        - "domain1"

```

some errors in output:

```bash
23:17:54 
 ⏳ Pipeline running successfully so far; produced 181 events in 25 minutes and 5.27 seconds.
23:17:54 
 --- Logging error ---
23:17:54 
 Traceback (most recent call last):
23:17:54 
   File "/usr/local/lib/python3.10/dist-packages/datahub/ingestion/run/pipeline.py", line 362, in run
23:17:54 
     for record_envelope in self.transform(record_envelopes):
23:17:54 
   File "/usr/local/lib/python3.10/dist-packages/datahub/ingestion/transformer/base_transformer.py", line 195, in transform
23:17:54 
     envelope = self._transform_or_record_mce(envelope)
23:17:54 
   File "/usr/local/lib/python3.10/dist-packages/datahub/ingestion/transformer/base_transformer.py", line 130, in _transform_or_record_mce
23:17:54 
     old_aspect = datahub.emitter.mce_builder.get_aspect_if_available(
23:17:54 
   File "/usr/local/lib/python3.10/dist-packages/datahub/emitter/mce_builder.py", line 340, in get_aspect_if_available
23:17:54 
     assert can_add_aspect(mce, AspectType)
23:17:54 
 AssertionError
23:17:54 
 
23:17:54 
 During handling of the above exception, another exception occurred:
23:17:54 
 
23:17:54 
 Traceback (most recent call last):
23:17:54 
   File "/usr/lib/python3.10/logging/__init__.py", line 1100, in emit
23:17:54 
     msg = self.format(record)
23:17:54 
   File "/usr/lib/python3.10/logging/__init__.py", line 943, in format
23:17:54 
     return fmt.format(record)
23:17:54 
   File "/usr/lib/python3.10/logging/__init__.py", line 678, in format
23:17:54 
     record.message = record.getMessage()
23:17:54 
   File "/usr/lib/python3.10/logging/__init__.py", line 368, in getMessage
23:17:54 
     msg = msg % self.args
23:17:54 
 TypeError: not all arguments converted during string formatting
23:17:54 
 Call stack:
23:17:54 
   File "/usr/lib/python3.10/threading.py", line 973, in _bootstrap
23:17:54 
     self._bootstrap_inner()
23:17:54 
   File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
23:17:54 
     self.run()
23:17:54 
   File "/usr/lib/python3.10/threading.py", line 953, in run
23:17:54 
     self._target(*self._args, **self._kwargs)
23:17:54 
   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 83, in _worker
23:17:54 
     work_item.run()
23:17:54 
   File "/usr/lib/python3.10/concurrent/futures/thread.py", line 58, in run
23:17:54 
     result = self.fn(*self.args, **self.kwargs)
23:17:54 
   File "/usr/local/lib/python3.10/dist-packages/datahub/cli/ingest_cli.py", line 134, in run_pipeline_to_completion
23:17:54 
     pipeline.run()
23:17:54 
   File "/usr/local/lib/python3.10/dist-packages/datahub/ingestion/run/pipeline.py", line 371, in run
23:17:54 
     logger.error("Failed to process some records. Continuing.", e)
23:17:54 
 Message: 'Failed to process some records. Continuing.'
23:17:54 
 Arguments: (AssertionError(),)

```

**Comment by hsheth2** [comment]
@livelace I believe this issue was fixed by some transformers fixes we deployed in November

I'm closing this for now, but feel free to re-open if it remains an issue
