### ISSUE TITLE
Trino Data Profiling is not working throwing exception

### ISSUE THREAD

**Issue by lokeish** [datahub-project/datahub#6316]
I am trying to ingest metadata from Trino to datahub. I am able to do this successfully without profiling.

When I enable profiling in the ingestion, it's throwing the below exception.

```
'[2022-10-30 11:58:57,814] INFO     {datahub.ingestion.run.pipeline:175} - Sink configured successfully. DataHubRestEmitter: configured '
           'to talk to http://datahub-gms:8080\n'
           '[2022-10-30 11:58:58,680] INFO     {datahub.ingestion.run.pipeline:200} - Source configured successfully.\n'
           '[2022-10-30 11:58:58,682] INFO     {datahub.cli.ingest_cli:129} - Starting metadata ingestion\n'
           '[2022-10-30 11:59:02,154] ERROR    {sqlalchemy.pool.impl.QueuePool:1371} - Error closing cursor\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-trino-0.9.0/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1294, in _execute_context\n'
           '    result = context._setup_crud_result_proxy()\n'
           '  File "/tmp/datahub/ingest/venv-trino-0.9.0/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1269, in '
           '_setup_crud_result_proxy\n'
           '    result = self.get_result_proxy()\n'
           '  File "/tmp/datahub/ingest/venv-trino-0.9.0/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 1244, in get_result_proxy\n'
           '    return result.ResultProxy(self)\n'
           '  File "/tmp/datahub/ingest/venv-trino-0.9.0/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 775, in __init__\n'
           '    self._init_metadata()\n'
           '  File "/tmp/datahub/ingest/venv-trino-0.9.0/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 794, in _init_metadata\n'
           '    cursor_description = self._cursor_description()\n'
           '  File "/tmp/datahub/ingest/venv-trino-0.9.0/lib/python3.10/site-packages/sqlalchemy/engine/result.py", line 924, in '
```

Full error traceback is attached.
[exec-urn_li_dataHubExecutionRequest_837cbfef-f009-4a06-8710-ba1df70632b6.log](https://github.com/datahub-project/datahub/files/9895769/exec-urn_li_dataHubExecutionRequest_837cbfef-f009-4a06-8710-ba1df70632b6.log)

Below is the ingestion script I'm using:

```
sink:
    type: datahub-rest
    config:
        server: 'http://datahub-gms:8080'
source:
    type: trino
    config:
        database: minio
        host_port: 'trino:8080'
        username: genius
        profiling:
            enabled: true
pipeline_name: 'urn:li:dataHubIngestionSource:5765b489-8ec8-4e0a-be00-b7bb6133d7a4'

```

**Comment by mayurinehate** [comment]
@lokeish can you please add below in the recipe and try again ? Ideally information_schema need not be ingested by datahub and ignored by default. In your case, the recipe fails for profiling only because it tries to run profiling queries against information_schema and it is not supported. 

```
    schema_pattern:
      deny:
        - ^information_schema$
```

**Comment by laulpogan** [comment]
Hi @yangjiandan  this seems like a troubleshooting issue, rather than a bug. We're happy to provide community support on our Slack channel, but currently reserve git issues for bugs.

If you're still having trouble, please join us at [[slack.datahubproject.io](https://slack.datahubproject.io/)](https://slack.datahubproject.io) and we can troubleshoot there. For now, I'm going to close this issue.
