### ISSUE TITLE
Ingestion hive bug

### ISSUE THREAD

**Issue by lanzhoujiaoya** [datahub-project/datahub#6597]
**Describe the bug**
k8s部署datahub之后，在Ingestion hive过程中导入数据失败

**To Reproduce**
报错如下
![image](https://user-images.githubusercontent.com/31941244/205032371-91378b56-1537-4e45-9e48-1d8e54d5a795.png)
hive配置如下
![image](https://user-images.githubusercontent.com/31941244/205033299-61dd11dd-7bd9-4871-b69e-73daf6ef2aea.png)

log如下：
~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': '6352932c-85da-425f-8a5b-c5360788b87f',
 'infos': ['2022-12-01 10:40:52.166890 [exec_id=6352932c-85da-425f-8a5b-c5360788b87f] INFO: Starting execution for task with name=RUN_INGEST',
           '2022-12-01 10:40:58.254270 [exec_id=6352932c-85da-425f-8a5b-c5360788b87f] INFO: stdout=venv setup time = 0\n'
           'This version of datahub supports report-to functionality\n'
           'datahub  ingest run -c /tmp/datahub/ingest/6352932c-85da-425f-8a5b-c5360788b87f/recipe.yml --report-to '
           '/tmp/datahub/ingest/6352932c-85da-425f-8a5b-c5360788b87f/ingestion_report.json\n'
           '[2022-12-01 10:40:55,385] INFO     {datahub.cli.ingest_cli:182} - DataHub CLI version: 0.9.1\n'
           '[2022-12-01 10:40:55,417] INFO     {datahub.ingestion.run.pipeline:175} - Sink configured successfully. DataHubRestEmitter: configured '
           'to talk to http://datahub-datahub-gms:8080\n'
           '[2022-12-01 10:40:56,089] INFO     {datahub.ingestion.run.pipeline:200} - Source configured successfully.\n'
           '[2022-12-01 10:40:56,092] INFO     {datahub.cli.ingest_cli:129} - Starting metadata ingestion\n'
           '[2022-12-01 10:40:56,285] INFO     {datahub.ingestion.reporting.file_reporter:54} - Wrote UNKNOWN report successfully to '
           "<_io.TextIOWrapper name='/tmp/datahub/ingest/6352932c-85da-425f-8a5b-c5360788b87f/ingestion_report.json' mode='w' encoding='UTF-8'>\n"
           '[2022-12-01 10:40:56,286] INFO     {datahub.cli.ingest_cli:136} - Source (hive) report:\n'
           "{'events_produced': '0',\n"
           " 'events_produced_per_sec': '0',\n"
           " 'event_ids': [],\n"
           " 'warnings': {},\n"
           " 'failures': {},\n"
           " 'soft_deleted_stale_entities': [],\n"
           " 'tables_scanned': '0',\n"
           " 'views_scanned': '0',\n"
           " 'entities_profiled': '0',\n"
           " 'filtered': [],\n"
           " 'start_time': '2022-12-01 10:40:55.801359 (now).',\n"
           " 'running_time': '0.48 seconds'}\n"
           '[2022-12-01 10:40:56,286] INFO     {datahub.cli.ingest_cli:139} - Sink (datahub-rest) report:\n'
           "{'total_records_written': '0',\n"
           " 'records_written_per_second': '0',\n"
           " 'warnings': [],\n"
           " 'failures': [],\n"
           " 'start_time': '2022-12-01 10:40:55.411800 (now).',\n"
           " 'current_time': '2022-12-01 10:40:56.286366 (now).',\n"
           " 'total_duration_in_seconds': '0.87',\n"
           " 'gms_version': 'v0.9.2',\n"
           " 'pending_requests': '0'}\n"
           '[2022-12-01 10:40:56,813] ERROR    {datahub.entrypoints:192} - \n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/entrypoints.py", line 149, in main\n'
           '    sys.exit(datahub(standalone_mode=False, **kwargs))\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/core.py", line 1130, in __call__\n'
           '    return self.main(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/core.py", line 1055, in main\n'
           '    rv = self.invoke(ctx)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/core.py", line 1404, in invoke\n'
           '    return ctx.invoke(self.callback, **ctx.params)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/core.py", line 760, in invoke\n'
           '    return __callback(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func\n'
           '    return f(get_current_context(), *args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 347, in wrapper\n'
           '    raise e\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 299, in wrapper\n'
           '    res = func(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/utilities/memory_leak_detector.py", line 95, in '
           'wrapper\n'
           '    return func(ctx, *args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 212, in run\n'
           '    loop.run_until_complete(run_func_check_upgrade(pipeline))\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 166, in '
           'run_func_check_upgrade\n'
           '    ret = await the_one_future\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 157, in run_pipeline_async\n'
           '    return await loop.run_in_executor(\n'
           '  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run\n'
           '    result = self.fn(*self.args, **self.kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 148, in '
           'run_pipeline_to_completion\n'
           '    raise e\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 134, in '
           'run_pipeline_to_completion\n'
           '    pipeline.run()\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 348, in run\n'
           '    for wu in itertools.islice(\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/ingestion/source/sql/sql_common.py", line 640, in '
           'get_workunits\n'
           '    for inspector in self.get_inspectors():\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/datahub/ingestion/source/sql/sql_common.py", line 539, in '
           'get_inspectors\n'
           '    with engine.connect() as conn:\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2263, in connect\n'
           '    return self._connection_cls(self, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 104, in __init__\n'
           '    else engine.raw_connection()\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2369, in raw_connection\n'
           '    return self._wrap_pool_connect(\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2336, in _wrap_pool_connect\n'
           '    return fn()\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 304, in unique_connection\n'
           '    return _ConnectionFairy._checkout(self)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 778, in _checkout\n'
           '    fairy = _ConnectionRecord.checkout(pool)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 495, in checkout\n'
           '    rec = pool._do_get()\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 139, in _do_get\n'
           '    with util.safe_reraise():\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__\n'
           '    compat.raise_(\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_\n'
           '    raise exception\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 137, in _do_get\n'
           '    return self._create_connection()\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 309, in _create_connection\n'
           '    return _ConnectionRecord(self)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 440, in __init__\n'
           '    self.__connect(first_connect_check=True)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 660, in __connect\n'
           '    with util.safe_reraise():\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__\n'
           '    compat.raise_(\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 182, in raise_\n'
           '    raise exception\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 656, in __connect\n'
           '    connection = pool._invoke_creator(self)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/engine/strategies.py", line 114, in connect\n'
           '    return dialect.connect(*cargs, **cparams)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 508, in connect\n'
           '    return self.dbapi.connect(*cargs, **cparams)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/pyhive/hive.py", line 126, in connect\n'
           '    return Connection(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-hive-0.9.1/lib/python3.10/site-packages/pyhive/hive.py", line 198, in __init__\n'
           '    raise ValueError("Password should be set if and only if in LDAP or CUSTOM mode; "\n'
           'ValueError: Password should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes\n'
           '[2022-12-01 10:40:56,814] ERROR    {datahub.entrypoints:195} - Command failed: \n'
           '\tPassword should be set if and only if in LDAP or CUSTOM mode; Remove password or use one of those modes.\n'
           '\tRun with --debug to get full stacktrace.\n'
           "\te.g. 'datahub --debug ingest run -c /tmp/datahub/ingest/6352932c-85da-425f-8a5b-c5360788b87f/recipe.yml --report-to "
           "/tmp/datahub/ingest/6352932c-85da-425f-8a5b-c5360788b87f/ingestion_report.json'\n",
           "2022-12-01 10:40:58.254743 [exec_id=6352932c-85da-425f-8a5b-c5360788b87f] INFO: Failed to execute 'datahub ingest'",
           '2022-12-01 10:40:58.255065 [exec_id=6352932c-85da-425f-8a5b-c5360788b87f] INFO: Caught exception EXECUTING '
           'task_id=6352932c-85da-425f-8a5b-c5360788b87f, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 168, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'structured_report': '{"source": {"type": "hive", "report": {"events_produced": "0", "events_produced_per_sec": "0", "event_ids": [], "warnings": '
                      '{}, "failures": {}, "soft_deleted_stale_entities": [], "tables_scanned": "0", "views_scanned": "0", "entities_profiled": "0", '
                      '"filtered": [], "start_time": "2022-12-01 10:40:55.801359 (now).", "running_time": "0.48 seconds"}}, "sink": {"type": '
                      '"datahub-rest", "report": {"total_records_written": "0", "records_written_per_second": "0", "warnings": [], "failures": [], '
                      '"start_time": "2022-12-01 10:40:55.411800 (now).", "current_time": "2022-12-01 10:40:56.285261 (now).", '
                      '"total_duration_in_seconds": "0.87", "gms_version": "v0.9.2", "pending_requests": "0"}}}'}
Execution finished with errors.

datahub helm安装方式如下：
![image](https://user-images.githubusercontent.com/31941244/205033064-924b5bc5-0623-4596-9a7f-9d18f9d140a1.png)

**Comment by fire-king-coder123** [comment]
you may  need add config
![image](https://user-images.githubusercontent.com/74519170/205795423-0179c62f-5708-4d7d-a958-e10a57d28d82.png)
