### ISSUE TITLE
S3 Datalake UI Ingest w/profiling enabled fails

### ISSUE THREAD

**Issue by charliemenke** [datahub-project/datahub#6793]
**Describe the bug**
I have a brand new datahub install running on k8s. Everything is working normally, but I cant seem to get the profiler to work with a S3 Datalake ingest recipe. Without profiling enabled, everything works fine. But the ingest will fail if it is set to true.

Seems like an issue regaurding the `acryl` executor trying to install deps. Below is the error output:

```bash
022-12-16 22:27:53.732183 [exec_id=e6a2e23d-76e8-41ee-bc85-2e535a088208] INFO: Failed to execute 'datahub ingest'
2022-12-16 22:27:53.733013 [exec_id=e6a2e23d-76e8-41ee-bc85-2e535a088208] INFO: Caught exception EXECUTING task_id=e6a2e23d-76e8-41ee-bc85-2e535a088208, name=RUN_INGEST, stacktrace=Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task
    task_event_loop.run_until_complete(task_future)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 168, in execute
    raise TaskError("Failed to execute 'datahub ingest'")
acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'

~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': 'e6a2e23d-76e8-41ee-bc85-2e535a088208',
 'infos': ['2022-12-16 22:27:35.389963 [exec_id=e6a2e23d-76e8-41ee-bc85-2e535a088208] INFO: Starting execution for task with name=RUN_INGEST',
           "2022-12-16 22:27:53.731915 [exec_id=e6a2e23d-76e8-41ee-bc85-2e535a088208] INFO: stdout=venv doesn't exist.. minting..\n"
           'Requirement already satisfied: pip in /tmp/datahub/ingest/venv-s3-0.9.1/lib/python3.10/site-packages (22.2.2)\n'
           'Collecting pip\n'
           '  Downloading pip-22.3.1-py3-none-any.whl (2.1 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.1/2.1 MB 66.5 MB/s eta 0:00:00\n'
           'Collecting wheel\n'
           '  Downloading wheel-0.38.4-py3-none-any.whl (36 kB)\n'
           'Requirement already satisfied: setuptools in /tmp/datahub/ingest/venv-s3-0.9.1/lib/python3.10/site-packages (63.2.0)\n'
           'Collecting setuptools\n'
           '  Downloading setuptools-65.6.3-py3-none-any.whl (1.2 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.2/1.2 MB 76.6 MB/s eta 0:00:00\n'
           'Installing collected packages: wheel, setuptools, pip\n'
           '  Attempting uninstall: setuptools\n'
           '    Found existing installation: setuptools 63.2.0\n'
           '    Uninstalling setuptools-63.2.0:\n'
           '      Successfully uninstalled setuptools-63.2.0\n'
           '  Attempting uninstall: pip\n'
           '    Found existing installation: pip 22.2.2\n'
           '    Uninstalling pip-22.2.2:\n'
           '      Successfully uninstalled pip-22.2.2\n'
           'Successfully installed pip-22.3.1 setuptools-65.6.3 wheel-0.38.4\n'
           'Collecting acryl-datahub[datahub-kafka,datahub-rest,s3]==0.9.1\n'
           '  Downloading acryl_datahub-0.9.1-py3-none-any.whl (1.1 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 61.6 MB/s eta 0:00:00\n'
           'Collecting stackprinter>=0.2.6\n'
           '  Downloading stackprinter-0.2.10-py3-none-any.whl (29 kB)\n'
           'Collecting ratelimiter\n'
           '  Using cached ratelimiter-1.2.0.post0-py3-none-any.whl (6.6 kB)\n'
           'Collecting tabulate\n'
           '  Downloading tabulate-0.9.0-py3-none-any.whl (35 kB)\n'
           'Collecting mypy-extensions>=0.4.3\n'
           '  Using cached mypy_extensions-0.4.3-py2.py3-none-any.whl (4.5 kB)\n'
           'Collecting cached-property\n'
           '  Using cached cached_property-1.5.2-py2.py3-none-any.whl (7.6 kB)\n'
           'Collecting types-Deprecated\n'
           '  Downloading types_Deprecated-1.2.9-py3-none-any.whl (3.2 kB)\n'
           'Collecting click-default-group\n'
           '  Using cached click-default-group-1.2.2.tar.gz (3.3 kB)\n'
           '  Preparing metadata (setup.py): started\n'
           "  Preparing metadata (setup.py): finished with status 'done'\n"
           'Collecting avro<1.11,>=1.10.2\n'
           '  Using cached avro-1.10.2.tar.gz (68 kB)\n'
           '  Preparing metadata (setup.py): started\n'
           "  Preparing metadata (setup.py): finished with status 'done'\n"
           'Collecting typing-inspect\n'
           '  Downloading typing_inspect-0.8.0-py3-none-any.whl (8.7 kB)\n'
           'Collecting aiohttp<4\n'
           '  Downloading aiohttp-3.8.3-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.0 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.0/1.0 MB 71.9 MB/s eta 0:00:00\n'
           'Collecting toml>=0.10.0\n'
           '  Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)\n'
           'Collecting avro-gen3==0.7.6\n'
           '  Downloading avro_gen3-0.7.6-py3-none-any.whl (26 kB)\n'
           'Collecting expandvars>=0.6.5\n'
           '  Using cached expandvars-0.9.0-py3-none-any.whl (6.6 kB)\n'
           'Collecting packaging\n'
           '  Downloading packaging-22.0-py3-none-any.whl (42 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.6/42.6 kB 10.6 MB/s eta 0:00:00\n'
           'Collecting types-termcolor>=1.0.0\n'
           '  Downloading types_termcolor-1.1.6-py3-none-any.whl (2.3 kB)\n'
           'Collecting progressbar2\n'
           '  Downloading progressbar2-4.2.0-py2.py3-none-any.whl (27 kB)\n'
           'Collecting PyYAML\n'
           '  Using cached PyYAML-6.0-cp310-cp310-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_12_x86_64.manylinux2010_x86_64.whl (682 kB)\n'
           'Collecting python-dateutil>=2.8.0\n'
           '  Using cached python_dateutil-2.8.2-py2.py3-none-any.whl (247 kB)\n'
           'Collecting humanfriendly\n'
           '  Using cached humanfriendly-10.0-py2.py3-none-any.whl (86 kB)\n'
           'Collecting mixpanel>=4.9.0\n'
           '  Downloading mixpanel-4.10.0-py2.py3-none-any.whl (8.9 kB)\n'
           'Collecting psutil>=5.8.0\n'
           '  Downloading psutil-5.9.4-cp36-abi3-manylinux_2_12_x86_64.manylinux2010_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (280 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 280.2/280.2 kB 38.9 MB/s eta 0:00:00\n'
           'Collecting docker\n'
           '  Downloading docker-6.0.1-py3-none-any.whl (147 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 147.5/147.5 kB 26.5 MB/s eta 0:00:00\n'
           'Collecting pydantic>=1.5.1\n'
           '  Downloading pydantic-1.10.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (12.8 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 88.9 MB/s eta 0:00:00\n'
           'Collecting click>=6.0.0\n'
           '  Using cached click-8.1.3-py3-none-any.whl (96 kB)\n'
           'Collecting click-spinner\n'
           '  Using cached click_spinner-0.1.10-py2.py3-none-any.whl (4.0 kB)\n'
           'Collecting typing-extensions>=3.10.0.2\n'
           '  Downloading typing_extensions-4.4.0-py3-none-any.whl (26 kB)\n'
           'Collecting entrypoints\n'
           '  Using cached entrypoints-0.4-py3-none-any.whl (5.3 kB)\n'
           'Collecting Deprecated\n'
           '  Using cached Deprecated-1.2.13-py2.py3-none-any.whl (9.6 kB)\n'
           'Collecting ijson\n'
           '  Using cached ijson-3.1.4-cp310-cp310-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (133 kB)\n'
           'Collecting termcolor>=1.0.0\n'
           '  Downloading termcolor-2.1.1-py3-none-any.whl (6.2 kB)\n'
           'Collecting requests\n'
           '  Downloading requests-2.28.1-py3-none-any.whl (62 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 62.8/62.8 kB 14.1 MB/s eta 0:00:00\n'
           'Collecting confluent-kafka>=1.5.0\n'
           '  Downloading confluent_kafka-1.9.2-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 82.6 MB/s eta 0:00:00\n'
           'Collecting fastavro>=1.2.0\n'
           '  Downloading fastavro-1.7.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.6 MB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.6/2.6 MB 105.3 MB/s eta 0:00:00\n'
           'Collecting smart-open[s3]>=5.2.1\n'
           '  Downloading smart_open-6.3.0-py3-none-any.whl (56 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.8/56.8 kB 11.3 MB/s eta 0:00:00\n'
           'Collecting boto3\n'
           '  Downloading boto3-1.26.32-py3-none-any.whl (132 kB)\n'
           '     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 132.7/132.7 kB 32.8 MB/s eta 0:00:00\n'
           'Collecting tableschema>=1.20.2\n'
           '  Using cached tableschema-1.20.2-py2.py3-none-any.whl (68 kB)\n'
           'Collecting pyspark==3.0.3\n'
           '/usr/local/bin/ingestion_common.sh: line 3:    50 Killed                  pip install -r $req_file\n',
           "2022-12-16 22:27:53.732183 [exec_id=e6a2e23d-76e8-41ee-bc85-2e535a088208] INFO: Failed to execute 'datahub ingest'",
           '2022-12-16 22:27:53.733013 [exec_id=e6a2e23d-76e8-41ee-bc85-2e535a088208] INFO: Caught exception EXECUTING '
           'task_id=e6a2e23d-76e8-41ee-bc85-2e535a088208, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 168, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"]}
Execution finished with errors.
```

Again, obviously looks like a deps issue. I tried to exec into the pod and get the dependancy myself, but since its seems to run as another user, I couldnt get that to work.

**To Reproduce**
1. Spin up new datahub instance.
2. Create S3 Datalake ingest recipe with profiling enabled:

```yaml
source:
    type: s3
    config:
        profiling:
            enabled: true
        path_specs:
            -
                include: 's3://s3/path//{table}/{partition_key[0]}={partition[0]}/*.parquet'
        env: PROD
        aws_config:
            aws_access_key_id: <id>
            aws_region: <region>
            aws_secret_access_key: <secret_id>
```

Any help would be appreciated. Thanks!

**Comment by charliemenke** [comment]
This is the suspect line from the log
```bash
'/usr/local/bin/ingestion_common.sh: line 3:    50 Killed                  pip install -r $req_file
```
which is a local script within the container:
```sh
#!/bin/bash

function create_venv {
    task_id=$1
    datahub_version="$2"
    plugin="$3"
    tmp_dir="$4"
    # we always install datahub-rest and datahub-kafka in addition to the plugin
    all_plugins="datahub-rest,datahub-kafka,${plugin}"

    extra_deps=()
    if [ "$plugin" = "hive" ]; then
        # Add dependency
        extra_deps+=("databricks-dbapi")
    fi

    venv_dir="$tmp_dir/venv-$plugin-${datahub_version}"
    SECONDS=0
    # Create tmp file to store requirements using provided recipe id.
    req_file="$tmp_dir/requirements-${task_id}.txt"
    touch "$req_file"
    if [ "$datahub_version" == "latest" ]; then
        echo "Latest version will be installed"
        echo "acryl-datahub[${all_plugins}]" > "$req_file"
    else
        echo "acryl-datahub[${all_plugins}]==$datahub_version" > "$req_file"
    fi
    # Install extra deps
    if [ ${#extra_deps[@]} -ne 0 ]; then
        for extra_dep in ${extra_deps[@]}; do
            echo "$extra_dep" >> "$req_file"
        done
    fi
    if [ ! -d "$venv_dir" ]; then
        echo "venv doesn't exist.. minting.."
        python3 -m venv $venv_dir
        source "$venv_dir/bin/activate"
        pip install --upgrade pip wheel setuptools
        pip install -r $req_file
    else
        source "$venv_dir/bin/activate"
        if [ "$datahub_version" == "latest" ]; then
            # in case we are installing latest, we want to always re-install in case latest has changed
            pip install --upgrade -r $req_file
        fi
    fi
    rm $req_file
    echo "venv setup time = $SECONDS"
    }
```

**Comment by jjoyce0510** [comment]
Thanks for the report! We are looking into this.

**Comment by hsheth2** [comment]
@charliemenke In the past we've seen that `line x: Killed` message when the pod ran out of memory and hence killed the process. In the pod, do you see any messages like "killed process" in the output of `dmesg -T`?

That said, it does seem strange that it failed when running `pip install`, which suggests there's more stuff at play here.

**Comment by jjoyce0510** [comment]
Changing profiling should not impact what is installed as part of this process, so it's doubtful that it's related to that.

I'd agree that memory is probably the issue - profiling large datasets can be very expensive.
