### ISSUE TITLE
Bigquery - 400 No matching signature for operator BETWEEN

### ISSUE THREAD

**Issue by FelipeArruda** [datahub-project/datahub#6809]
**Describe the bug**
When I set the parameter `partition_profiling_enabled: true` to true (profilling), I'm facing the following error.

**To Reproduce**
Set `profiling.partition_profiling_enabled` to `true`, when is false no error occur.

```
profiling:
            enabled: true
            profile_table_level_only: false
            include_field_sample_values: true
            profile_if_updated_since_days: null
            profile_table_size_limit: null
            profile_table_row_limit: 50000
            partition_profiling_enabled: true
```

**Expected behavior**
None

**Screenshots**
Log error:

```
          " 'gms_version': 'v0.9.3',\n"
           " 'pending_requests': '0'}\n"
           '[2022-12-19 18:48:01,253] ERROR    {datahub.entrypoints:207} - Command failed: 400 No matching signature for operator BETWEEN for '
           'argument types: TIMESTAMP, DATE, DATE. Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [7:17]\n'
           '\n'
           'Location: US\n'
           'Job ID: 6c8bb3fe-91b0-479c-8aff-eea4da00cdc3\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/cloud/bigquery/dbapi/cursor.py", line 203, in '
           '_execute\n'
           '    self._query_job.result()\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1499, in '
           'result\n'
           '    do_get_result()\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/api_core/retry.py", line 349, in '
           'retry_wrapped_func\n'
           '    return retry_target(\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/api_core/retry.py", line 191, in retry_target\n'
           '    return target()\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/cloud/bigquery/job/query.py", line 1489, in '
           'do_get_result\n'
           '    super(QueryJob, self).result(retry=retry, timeout=timeout)\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/cloud/bigquery/job/base.py", line 728, in result\n'
           '    return super(_AsyncJob, self).result(timeout=timeout, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-bigquery-0.9.3.2/lib/python3.10/site-packages/google/api_core/future/polling.py", line 261, in result\n'
           '    raise self._exception\n'
           'google.api_core.exceptions.BadRequest: 400 No matching signature for operator BETWEEN for argument types: TIMESTAMP, DATE, DATE. '
           'Supported signature: (ANY) BETWEEN (ANY) AND (ANY) at [7:17]\n'
           '\n'
```

**Desktop (please complete the following information):**
 - OS: GCP
 - Datahub version: 0.9.3

**Additional context**
I tried with 0.9.3.2 but still getting error when running bigquery ingestion

**Comment by jjoyce0510** [comment]
This should have been addressed and merged 4 days ago as part of this: https://github.com/datahub-project/datahub/pull/6874 

It will be available in the next minor release. (v0.9.5.1)

Cheers
John
