### ISSUE TITLE
ConfigurationError: pipeline_name must be provided if stateful ingestion is enabled.

### ISSUE THREAD

**Issue by ActivateConsulting** [datahub-project/datahub#6950]
**Describe the bug**
I recently installed datahub (running v0.9.3). Did try to upgrade to 0.9.5 before i read it was broken, might have something to do with this error. Running the sync with snowflake causes this error (see logs below).

I'm running in K8s and installed using the helm charts.

**Desktop (please complete the following information):**
 - Version v0.9.3

~~~~ Execution Summary ~~~~

RUN_INGEST - {'errors': [],
 'exec_id': '907f9947-0ba6-4acd-955d-2210c2bbec51',
 'infos': ['2023-01-04 13:55:26.996503 [exec_id=907f9947-0ba6-4acd-955d-2210c2bbec51] INFO: Starting execution for task with name=RUN_INGEST',
           '2023-01-04 13:55:33.118663 [exec_id=907f9947-0ba6-4acd-955d-2210c2bbec51] INFO: stdout=venv setup time = 0\n'
           'This version of datahub supports report-to functionality\n'
           'datahub  ingest run -c /tmp/datahub/ingest/907f9947-0ba6-4acd-955d-2210c2bbec51/recipe.yml --report-to '
           '/tmp/datahub/ingest/907f9947-0ba6-4acd-955d-2210c2bbec51/ingestion_report.json\n'
           '[2023-01-04 13:55:29,050] INFO     {datahub.cli.ingest_cli:165} - DataHub CLI version: 0.9.3\n'
           '[2023-01-04 13:55:29,068] INFO     {datahub.ingestion.run.pipeline:174} - Sink configured successfully. DataHubRestEmitter: configured '
           'to talk to http://datahub-datahub-gms:8080\n'
           '[2023-01-04 13:55:30,892] INFO     {datahub.ingestion.source_config.sql.snowflake:231} - using authenticator type '
           "'DEFAULT_AUTHENTICATOR'\n"
           '[2023-01-04 13:55:31,150] ERROR    {datahub.entrypoints:207} - Command failed: Failed to configure source (snowflake): pipeline_name '
           'must be provided if stateful ingestion is enabled.\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 193, in __init__\n'
           '    self.source: Source = source_class.create(\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/source/snowflake/snowflake_v2.py", line '
           '247, in create\n'
           '    return cls(ctx, config)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/source/snowflake/snowflake_v2.py", line '
           '187, in __init__\n'
           '    super().__init__(config, ctx)\n'
           '  File '
           '"/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/source/state/stateful_ingestion_base.py", line '
           '124, in __init__\n'
           '    self._initialize_checkpointing_state_provider()\n'
           '  File '
           '"/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/source/state/stateful_ingestion_base.py", line '
           '149, in _initialize_checkpointing_state_provider\n'
           '    raise ConfigurationError(\n'
           'datahub.configuration.common.ConfigurationError: pipeline_name must be provided if stateful ingestion is enabled.\n'
           '\n'
           'The above exception was the direct cause of the following exception:\n'
           '\n'
           'Traceback (most recent call last):\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/entrypoints.py", line 165, in main\n'
           '    sys.exit(datahub(standalone_mode=False, **kwargs))\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/core.py", line 1130, in __call__\n'
           '    return self.main(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/core.py", line 1055, in main\n'
           '    rv = self.invoke(ctx)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/core.py", line 1657, in invoke\n'
           '    return _process_result(sub_ctx.command.invoke(sub_ctx))\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/core.py", line 1404, in invoke\n'
           '    return ctx.invoke(self.callback, **ctx.params)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/core.py", line 760, in invoke\n'
           '    return __callback(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func\n'
           '    return f(get_current_context(), *args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 347, in wrapper\n'
           '    raise e\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 299, in wrapper\n'
           '    res = func(*args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/utilities/memory_leak_detector.py", line 95, in '
           'wrapper\n'
           '    return func(ctx, *args, **kwargs)\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 179, in run\n'
           '    pipeline = Pipeline.create(\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 313, in create\n'
           '    return cls(\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 199, in __init__\n'
           '    self._raise_initialization_error(\n'
           '  File "/tmp/datahub/ingest/venv-snowflake-0.9.3/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 129, in '
           '_raise_initialization_error\n'
           '    raise PipelineInitError(f"{msg}: {e}") from e\n'
           'datahub.ingestion.run.pipeline.PipelineInitError: Failed to configure source (snowflake): pipeline_name must be provided if stateful '
           'ingestion is enabled.\n',
           "2023-01-04 13:55:33.118926 [exec_id=907f9947-0ba6-4acd-955d-2210c2bbec51] INFO: Failed to execute 'datahub ingest'",
           '2023-01-04 13:55:33.120275 [exec_id=907f9947-0ba6-4acd-955d-2210c2bbec51] INFO: Caught exception EXECUTING '
           'task_id=907f9947-0ba6-4acd-955d-2210c2bbec51, name=RUN_INGEST, stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 123, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 646, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 168, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"]}
Execution finished with errors.

**Comment by chriscollins3456** [comment]
hey @ActivateConsulting ! are you running ingestion through the UI with managed ingestion?

I believe I know the issue causing this, and it is indeed fixed in the most recent version, but like you said there is another issue with the current version we are currently in the process of fixing and rolling out a new update.

In order to fix this in the short term, you can do one of two things in order to get your snowflake source running again.

1. change your recipe so that:
```
        stateful_ingestion:
            enabled: false
```
be either directly editing the YAML or checking "Enable Stateful Ingestion" off from the advanced section of your UI form.

2. add a `pipeline_name` to your recipe if you truly do want stateful ingestion to be enabled. This must be unique across all ingestion sources, though, and remain constant for this ingestion source in order to have stateful_ingestion running properly. The safest bet would be to simply turn it off for now.

I'll leave this issue open for a few days or until I hear back from you to ensure things are alright!

**Comment by ActivateConsulting** [comment]
Hi Chris,

I did add the ingestion through the UI, and this happened after a day or so of running the environment. I did try running it without the stateful_ingestion enabled, with the same result. Unfortunately I'm unable to reproduce the error as I ended up re-intalling the whole solution and starting from scratch.

**Comment by chriscollins3456** [comment]
@ActivateConsulting gotcha. well I'm sorry for the difficulty but glad it's working as desired now! Since we pushed a fix for this some time ago and you aren't seeing the issue anymore, I think it's safe to close this issue.

If you see anything like this again please feel free to re-open and/or let us know.
