### ISSUE TITLE
Unable to ingest OpenAPI from endpoint with self-signed certificate

### ISSUE THREAD

**Issue by thomaschilton-viavi** [datahub-project/datahub#7153]
**Describe the bug**
Unable to ingest OpenAPI from endpoint with self-signed certificate

**To Reproduce**
1. Go to "Ingestion"
2. Click on 'Create a new source'
3. Add the following config which points to an OpenAPI specification
```
source:
    type: openapi
    config:
        name: some-api
        url: 'https://some-endpoint.net'
        swagger_file: api
```
5. See error
```
~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': 'e49d2717-ebf8-46f3-b377-7a1d5deb176f',
 'infos': ['2023-01-27 13:57:18.309420 INFO: Starting execution for task with name=RUN_INGEST',
           "2023-01-27 13:57:32.437402 INFO: Failed to execute 'datahub ingest'",
           '2023-01-27 13:57:32.437629 INFO: Caught exception EXECUTING task_id=e49d2717-ebf8-46f3-b377-7a1d5deb176f, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 122, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 231, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Report ~~~~
{
  "cli": {
    "cli_version": "0.9.6",
    "cli_entry_location": "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/__init__.py",
    "py_version": "3.10.9 (main, Jan 23 2023, 22:32:48) [GCC 10.2.1 20210110]",
    "py_exec_path": "/tmp/datahub/ingest/venv-openapi-0.9.6/bin/python3",
    "os_details": "Linux-5.10.16.3-microsoft-standard-WSL2-x86_64-with-glibc2.31",
    "mem_info": "60.1 MB"
  },
  "source": {
    "type": "openapi",
    "report": {
      "events_produced": "0",
      "events_produced_per_sec": "0",
      "event_ids": [],
      "warnings": {},
      "failures": {},
      "start_time": "2023-01-27 13:57:20.645585 (now).",
      "running_time": "0.14 seconds"
    }
  },
  "sink": {
    "type": "datahub-rest",
    "report": {
      "total_records_written": "0",
      "records_written_per_second": "0",
      "warnings": [],
      "failures": [],
      "start_time": "2023-01-27 13:57:20.641413 (now).",
      "current_time": "2023-01-27 13:57:20.785985 (now).",
      "total_duration_in_seconds": "0.14",
      "gms_version": "v0.9.6",
      "pending_requests": "0"
    }
  }
}

~~~~ Ingestion Logs ~~~~
Obtaining venv creation lock...
Acquired venv creation lock
venv setup time = 0
This version of datahub supports report-to functionality
datahub  ingest run -c /tmp/datahub/ingest/e49d2717-ebf8-46f3-b377-7a1d5deb176f/recipe.yml --report-to /tmp/datahub/ingest/e49d2717-ebf8-46f3-b377-7a1d5deb176f/ingestion_report.json
[2023-01-27 13:57:20,626] INFO     {datahub.cli.ingest_cli:165} - DataHub CLI version: 0.9.6
[2023-01-27 13:57:20,643] INFO     {datahub.ingestion.run.pipeline:179} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms:8080
[2023-01-27 13:57:20,645] INFO     {datahub.ingestion.run.pipeline:196} - Source configured successfully.
[2023-01-27 13:57:20,646] INFO     {datahub.cli.ingest_cli:120} - Starting metadata ingestion
[2023-01-27 13:57:20,786] INFO     {datahub.ingestion.reporting.file_reporter:52} - Wrote UNKNOWN report successfully to <_io.TextIOWrapper name='/tmp/datahub/ingest/e49d2717-ebf8-46f3-b377-7a1d5deb176f/ingestion_report.json' mode='w' encoding='UTF-8'>
[2023-01-27 13:57:20,786] INFO     {datahub.cli.ingest_cli:125} - Source (openapi) report:
{'events_produced': '0',
 'events_produced_per_sec': '0',
 'event_ids': [],
 'warnings': {},
 'failures': {},
 'start_time': '2023-01-27 13:57:20.645585 (now).',
 'running_time': '0.14 seconds'}
[2023-01-27 13:57:20,786] INFO     {datahub.cli.ingest_cli:128} - Sink (datahub-rest) report:
{'total_records_written': '0',
 'records_written_per_second': '0',
 'warnings': [],
 'failures': [],
 'start_time': '2023-01-27 13:57:20.641413 (now).',
 'current_time': '2023-01-27 13:57:20.786455 (now).',
 'total_duration_in_seconds': '0.15',
 'gms_version': 'v0.9.6',
 'pending_requests': '0'}
[2023-01-27 13:57:21,263] ERROR    {datahub.entrypoints:213} - Command failed: HTTPSConnectionPool(host='some-endpoint.net', port=443): Max retries exceeded with url: /some-api/api (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/connectionpool.py", line 1042, in _validate_conn
    conn.connect()
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/connection.py", line 414, in connect
    self.sock = ssl_wrap_socket(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.10/ssl.py", line 513, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.10/ssl.py", line 1071, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.10/ssl.py", line 1342, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='some-endpoint.net', port=443): Max retries exceeded with url: /some-api/api (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/entrypoints.py", line 171, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 350, in wrapper
    raise e
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/telemetry/telemetry.py", line 302, in wrapper
    res = func(*args, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/utilities/memory_leak_detector.py", line 95, in wrapper
    return func(ctx, *args, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 190, in run
    loop.run_until_complete(run_func_check_upgrade(pipeline))
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 149, in run_func_check_upgrade
    ret = await the_one_future
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 140, in run_pipeline_async
    return await loop.run_in_executor(
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 131, in run_pipeline_to_completion
    raise e
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/cli/ingest_cli.py", line 123, in run_pipeline_to_completion
    pipeline.run()
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 334, in run
    for wu in itertools.islice(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/ingestion/source/openapi.py", line 220, in get_workunits
    sw_dict = self.config.get_swagger()
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/ingestion/source/openapi.py", line 96, in get_swagger
    sw_dict = get_swag_json(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/ingestion/source/openapi_parser.py", line 78, in get_swag_json
    response = request_call(url=tot_url, username=username, password=password)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/datahub/ingestion/source/openapi_parser.py", line 56, in request_call
    return requests.get(
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/requests/api.py", line 73, in get
    return request("get", url, params=params, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='some-endpoint.net', port=443): Max retries exceeded with url: /some-api/api (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate (_ssl.c:997)')))
```

**Expected behavior**
I expect there should be a configuration option to allow SSL verification to be disabled for the case of self-signed certificates.

**Screenshots**
Not necessary

**Desktop (please complete the following information):**
 - Version v0.9.6

**Additional context**
None

**Comment by bonze** [comment]
You can add OpenAPI's self-signed certificate to the actions component. Here is an example:
1.  Copy self-signed certificate (base64 encode):
          docker cp <openapi>.crt datahub-actions-1:/tmp/<openapi>.crt
2. Import cert for python, managed by cerrifi module:
------ as root:
docker exec -u 0 -it datahub-actions-1 /bin/bash
------ run:
openssl x509 -in /tmp/<openapi>.crt -text >> /tmp/datahub/ingest/venv-openapi-0.9.6/lib/python3.10/site-packages/certifi/cacert.pem

**Comment by thomaschilton-viavi** [comment]
The workaround suggested above isn't a viable option for production deployment on kubernetes.
