### ISSUE TITLE
Lineage informations are not updated in the Graph

### ISSUE THREAD

**Issue by jakobhanna** [datahub-project/datahub#7247]
**Describe the bug**
When i update lineage informations with the python emitter, the entity informations are updated, but the graph data remains the same. I could also make a graphql query, but it seems to me, the grahph should be updated automatically.

**To Reproduce**
1. Create Lineage.
1. Update with a MetadataChangeEventProposalWrapper the upstream_lineage aspect
2. Emit the data to Datahub
3. See the Graph and Api difference

**Expected behavior**
The grahph should be updated automatically.

**Screenshots**

![Bildschirmfoto vom 2023-02-03 17-19-01](https://user-images.githubusercontent.com/55106217/216660742-c5624c40-86c8-4490-87d9-a3a60a44578a.png)

![Bildschirmfoto vom 2023-02-03 17-41-35](https://user-images.githubusercontent.com/55106217/216663045-d141e094-13f2-46da-9c42-fa3cf64ca348.png)

![Bildschirmfoto vom 2023-02-03 17-19-25](https://user-images.githubusercontent.com/55106217/216660814-f434ebde-45bf-4a79-9045-46d8eb10693b.png)
d8.png)

**Screenshots**

**Comment by jakobhanna** [comment]
if think neo4j has a Problem handling the request: i can see this error on the server
```
6:58:37.681 [qtp522764626-3260] INFO  c.l.m.r.entity.AspectResource:95 - GET ASPECT urn: urn:li:telemetry:clientId aspect: telemetryClientId version: 0
datahub-gms               | 16:58:37.683 [pool-10-thread-3] INFO  c.l.m.filter.RestliLoggingFilter:55 - GET /aspects/urn%3Ali%3Atelemetry%3AclientId?aspect=telemetryClientId&version=0 - get - 200 - 2ms
datahub-gms               | 16:58:37.721 [qtp522764626-18327] INFO  c.l.m.r.entity.AspectResource:145 - INGEST PROPOSAL proposal: {aspectName=upstreamLineage, entityUrn=urn:li:dataset:(urn:li:dataPlatform:hive,ate.job_proc,PROD), entityType=dataset, aspect={contentType=application/json, value=ByteString(length=202,bytes=7b227570...227d5d7d)}, changeType=UPSERT}
datahub-gms               | 16:58:37.736 [pool-10-thread-2] INFO  c.l.m.filter.RestliLoggingFilter:55 - POST /aspects?action=ingestProposal - ingestProposal - 200 - 15ms
datahub-gms               | 16:58:37.739 [ThreadPoolTaskExecutor-1] ERROR c.l.m.k.MetadataChangeLogProcessor:93 - Failed to execute MCL hook with name com.linkedin.metadata.kafka.hook.UpdateIndicesHook
datahub-gms               | java.lang.UnsupportedOperationException: Remove edge not supported by Neo4JGraphService at this time.
datahub-gms               |     at com.linkedin.metadata.graph.neo4j.Neo4jGraphService.removeEdge(Neo4jGraphService.java:112)
datahub-gms               |     at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
datahub-gms               |     at com.linkedin.metadata.kafka.hook.UpdateIndicesHook.updateGraphServiceDiff(UpdateIndicesHook.java:362)
datahub-gms               |     at com.linkedin.metadata.kafka.hook.UpdateIndicesHook.handleUpdateChangeEvent(UpdateIndicesHook.java:172)
datahub-gms               |     at com.linkedin.metadata.kafka.hook.UpdateIndicesHook.invoke(UpdateIndicesHook.java:112)
datahub-gms               |     at com.linkedin.metadata.kafka.MetadataChangeLogProcessor.consume(MetadataChangeLogProcessor.java:89)
datahub-gms               |     at jdk.internal.reflect.GeneratedMethodAccessor37.invoke(Unknown Source)
datahub-gms               |     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
datahub-gms               |     at java.base/java.lang.reflect.Method.invoke(Method.java:566)
datahub-gms               |     at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169)
datahub-gms               |     at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119)
datahub-gms               |     at org.springframework.kafka.listener.adapter.HandlerAdapter.invoke(HandlerAdapter.java:56)
datahub-gms               |     at org.springframework.kafka.listener.adapter.MessagingMessageListenerAdapter.invokeHandler(MessagingMessageListenerAdapter.java:347)
datahub-gms               |     at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:92)
datahub-gms               |     at org.springframework.kafka.listener.adapter.RecordMessagingMessageListenerAdapter.onMessage(RecordMessagingMessageListenerAdapter.java:53)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeOnMessage(KafkaMessageListenerContainer.java:2334)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeOnMessage(KafkaMessageListenerContainer.java:2315)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeRecordListener(KafkaMessageListenerContainer.java:2237)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.doInvokeWithRecords(KafkaMessageListenerContainer.java:2150)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeRecordListener(KafkaMessageListenerContainer.java:2032)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeListener(KafkaMessageListenerContainer.java:1705)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.invokeIfHaveRecords(KafkaMessageListenerContainer.java:1276)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.pollAndInvoke(KafkaMessageListenerContainer.java:1268)
datahub-gms               |     at org.springframework.kafka.listener.KafkaMessageListenerContainer$ListenerConsumer.run(KafkaMessageListenerContainer.java:1163)
datahub-gms               |     at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
datahub-gms               |     at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
datahub-gms               |     at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
datahub-gms               |     at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
datahub-gms               |     at java.base/java.lang.Thread.run(Thread.java:829)
datahub-gms               | 16:58:37.739 [ThreadPoolTaskExecutor-1] INFO  c.l.m.k.h.s.SiblingAssociationHook:103 - Urn urn:li:dataset:(urn:li:dataPlatform:hive,ate.job_proc,PROD) received by Sibling Hook.
datahub-gms               | 16:58:38.332 [I/O dispatcher 1] INFO  c.l.m.s.e.update.BulkListener:47 - Successfully fed bulk request. Number of events: 3 Took time ms: -1
```

**Comment by RyanHolstien** [comment]
This is already fixed in master and has been called out in all relevant release notes.
```
Important Release Notes
With this release, if you are using Neo4J as your graph implementation, you need to set:
GRAPH_SERVICE_DIFF_MODE_ENABLED=false

For GMS (or MAE Consumer for standalone mode).
```
