### ISSUE TITLE
EntityTypeMapper is missing types present in the GraphQL API

### ISSUE THREAD

**Issue by trietsch** [datahub-project/datahub#7379]
**Describe the bug**
The following GraphQL query on the GMS fails:
```graphql
query getSchemaFieldForPath {
  searchAcrossEntities(input: { types: [SCHEMA_FIELD], query: "shipment_info.geo_info.lat"}) {
    searchResults {
      entity {
        urn
      }
    }
  }
}
```

It fails with:
```json
{
  "errors": [
    {
      "message": "An unknown error occurred.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "searchAcrossEntities"
      ],
      "extensions": {
        "code": 500,
        "type": "SERVER_ERROR",
        "classification": "DataFetchingException"
      }
    }
  ],
  "data": {
    "searchAcrossEntities": null
  },
  "extensions": {}
}
```

Error logs of the GMS:
```
2023-02-20 13:52:49,724 [ForkJoinPool.commonPool-worker-11] ERROR c.l.d.g.e.DataHubDataFetcherExceptionHandler:21 - Failed to execute DataFetcher
java.lang.IllegalArgumentException: Unknown entity type: SCHEMA_FIELD
    at com.linkedin.datahub.graphql.resolvers.EntityTypeMapper.getName(EntityTypeMapper.java:59)
    at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
    at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)
    at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
    at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
    at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
    at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
    at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
    at com.linkedin.datahub.graphql.resolvers.search.SearchAcrossEntitiesResolver.get(SearchAcrossEntitiesResolver.java:51)
    at com.linkedin.datahub.graphql.resolvers.search.SearchAcrossEntitiesResolver.get(SearchAcrossEntitiesResolver.java:33)
    at graphql.execution.ExecutionStrategy.fetchField(ExecutionStrategy.java:282)
    at graphql.execution.ExecutionStrategy.resolveFieldWithInfo(ExecutionStrategy.java:211)
    at graphql.execution.AsyncExecutionStrategy.execute(AsyncExecutionStrategy.java:59)
    at graphql.execution.Execution.executeOperation(Execution.java:159)
    at graphql.execution.Execution.execute(Execution.java:105)
    at graphql.GraphQL.execute(GraphQL.java:645)
    at graphql.GraphQL.lambda$parseValidateAndExecute$11(GraphQL.java:564)
    at java.base/java.util.concurrent.CompletableFuture.uniComposeStage(CompletableFuture.java:1106)
    at java.base/java.util.concurrent.CompletableFuture.thenCompose(CompletableFuture.java:2235)
    at graphql.GraphQL.parseValidateAndExecute(GraphQL.java:559)
    at graphql.GraphQL.executeAsync(GraphQL.java:527)
    at graphql.GraphQL.execute(GraphQL.java:453)
    at com.linkedin.datahub.graphql.GraphQLEngine.execute(GraphQLEngine.java:90)
    at com.datahub.graphql.GraphQLController.lambda$postGraphQL$0(GraphQLController.java:97)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
    at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**To Reproduce**
1. Go to the GraphiQL interface
2. Paste this query
3. Execute

**Expected behavior**
Return results filtered on the requested entity type.

**Cause**
[`EntityTypeMapper`](https://github.com/datahub-project/datahub/blob/master/datahub-graphql-core/src/main/java/com/linkedin/datahub/graphql/resolvers/EntityTypeMapper.java#L16) misses entity types that are present in the [API Entity definitions](https://github.com/datahub-project/datahub/blob/master/datahub-graphql-core/src/main/resources/entity.graphql#L619).

**Desktop (please complete the following information):**
 - OS: n/a, Datahub is running on GKE
 - Browser: any
 - Version: n/a

**Comment by chriscollins3456** [comment]
hey @trietsch ! are you only noticing this with schema fields? right now schema fields don't truly act as their own entities, but instead are referenced by other entities for things like column-level lineage. Therefore, they won't show up in search results or have their own entity page or own aspects in the database (just relationship edges in the graph index).

What exactly are you trying to query for here and see results about?

Trying to determine if this is a true bug or a feature request to build out functionality for schema fields more.

**Comment by trietsch** [comment]
Hi @chriscollins3456, thanks for your reply. Well, in fact, when there's an enum value for `SCHEMA_FIELD`, which is a required field in the query `searchAcrossEntities.input`, I'd expect to be able to use that. What I get in response, is an internal error.
IMO, if it's unsupported, it shouldn't be included in the API, especially if they don't really act as their own entities. I also had the same error for a few other entity types. The finite list can be extracted by finding the missing entity types in the mapper, that are present in the API Entity definitions.

**Comment by moriabs88** [comment]
@trietsch did you manage to solve it?

**Comment by trietsch** [comment]
> @trietsch did you manage to solve it?

Nope, unfortunately not. Also see @chriscollins3456's comment, might give you some pointers. 
For me, I was just experimenting with the Datahub project, so I could abandon at any time, which is what I did 😅
