### ISSUE TITLE
Lineage:my downstream blood entities exceed 1000+,when I expand level 5, the error is reported as follows  RejectedExecutionExceptione bug

### ISSUE THREAD

**Issue by iosMental** [datahub-project/datahub#7522]
14:36:11.754 [ForkJoinPool.commonPool-worker-164] ERROR c.l.d.g.e.DataHubDataFetcherExceptionHandler:21 - Failed to execute DataFetcher
java.util.concurrent.CompletionException: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1606)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1596)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.util.concurrent.RejectedExecutionException: Thread limit exceeded replacing blocked worker
	at java.util.concurrent.ForkJoinPool.tryCompensate(ForkJoinPool.java:2011)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3310)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1742)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1908)
	at org.neo4j.driver.internal.util.Futures.blockingGet(Futures.java:128)
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:69)
	at org.neo4j.driver.internal.InternalSession.run(InternalSession.java:51)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:37)
	at org.neo4j.driver.internal.AbstractQueryRunner.run(AbstractQueryRunner.java:43)
	at com.linkedin.metadata.graph.neo4j.Neo4jGraphService.runQuery(Neo4jGraphService.java:329)
	at com.linkedin.metadata.graph.neo4j.Neo4jGraphService.findRelatedEntities(Neo4jGraphService.java:159)
	at com.linkedin.metadata.graph.GraphService.getLineage(GraphService.java:163)
	at com.linkedin.metadata.graph.GraphService.getLineage(GraphService.java:98)
	at com.linkedin.metadata.graph.SiblingGraphService.getLineage(SiblingGraphService.java:54)
	at com.linkedin.datahub.graphql.resolvers.load.EntityLineageResultResolver.lambda$get$0(EntityLineageResultResolver.java:54)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1604)
	... 5 common frames omitted
![image](https://user-images.githubusercontent.com/10148880/223907137-2059d343-c49b-4e8e-bce8-85b00da56f75.png)

**Comment by iosMental** [comment]
upstream: lineage(input: { direction: UPSTREAM, start: 0, count: 100, separateSiblings: $separateSiblings }) {
        ...leafLineageResults
    }
    downstream: lineage(input: { direction: DOWNSTREAM, start: 0, count: 100, separateSiblings: $separateSiblings }) {
        ...leafLineageResults
    }    ->We modified count 100 ->500
