### ISSUE TITLE
'Unable to emit metadata to DataHub GMS' Airflow to Datahub

### ISSUE THREAD

**Issue by theocnrds** [datahub-project/datahub#7529]
**Describe the bug**
We deployed datahub on a VM in GCP and have Airflow (_v2.3.4+composer_) running in the same VPC via GCP's Cloud Composer. I followed this [intro](https://datahubproject.io/docs/lineage/airflow/#using-datahubs-airflow-lineage-plugin) to install and set up the Airflow lineage plugin. When running a DAG I get the following Exception int the DAG's logs (replaced original datahub address with <dh_host>:<dh_port>):

```
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 256, in _emit_generic
    response.raise_for_status()
  File "/opt/python3.8/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://<dh_host>:<dh_port>/aspects?action=ingestProposal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 190, in emit
    self.emit_mcp(item)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 232, in emit_mcp
    self._emit_generic(url, payload)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 265, in _emit_generic
    raise OperationalError(
datahub.configuration.common.OperationalError: ('Unable to emit metadata to DataHub GMS', {'message': '404 Client Error: Not Found for url: [http://10.10.10.56:9002/aspects?action=ingestProposal'](http://<dh_host>:<dh_port>/aspects?action=ingestProposal%27)})
[2023-03-08, 12:56:29 UTC] {taskinstance.py:1754} ERROR - Error when executing on_success_callback
Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 256, in _emit_generic
    response.raise_for_status()
  File "/opt/python3.8/lib/python3.8/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://<dh_host>:<dh_port>/aspects?action=ingestProposal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/python3.8/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 1752, in _run_finished_callback
    task.on_success_callback(context)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub_provider/_plugin.py", line 287, in custom_on_success_callback
    raise e
  File "/opt/python3.8/lib/python3.8/site-packages/datahub_provider/_plugin.py", line 284, in custom_on_success_callback
    datahub_task_status_callback(context, status=InstanceRunResult.SUCCESS)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub_provider/_plugin.py", line 148, in datahub_task_status_callback
    dataflow.emit(emitter, callback=_make_emit_callback(task.log))
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/api/entities/datajob/dataflow.py", line 130, in emit
    emitter.emit(mcp, callback)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 190, in emit
    self.emit_mcp(item)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 232, in emit_mcp
    self._emit_generic(url, payload)
  File "/opt/python3.8/lib/python3.8/site-packages/datahub/emitter/rest_emitter.py", line 265, in _emit_generic
    raise OperationalError(
datahub.configuration.common.OperationalError: ('Unable to emit metadata to DataHub GMS', {'message': '404 Client Error: Not Found for url: [http://<dh_host>:<dh_port>/aspects?action=ingestProposal'](http://<dh_host>:<dh_port>/aspects?action=ingestProposal%27)})
```

**To Reproduce**
1. Have Airflow running via Cloud Composer in GCP
2. Have datahub v0.10.0 running on a VM
3. Have both in the same VPC
4. Use Airflow lineage plugin

**Expected behavior**
Lineage information being properly pushed from Airflow to datahub.

**Comment by aoelvp94** [comment]
Hey @theocnrds did you solve the problem? I have the same issue!

**Comment by ivica-k** [comment]
Having the same issue with self-hosted Datahub v1.1.0, Airflow 2.11.0 and 

```
acryl-datahub==1.2.0.3
acryl-datahub-airflow-plugin==1.2.0.3
```
