### ISSUE TITLE
[ingestion] Discrepancy between "dataProcessInstance" model (not supporting "status" aspect) and source_helpers.auto_status_aspect() leads to 500 error in GMS

### ISSUE THREAD

**Issue by gcernier-semarchy** [datahub-project/datahub#7748]
**Describe the bug:**
There is a discrepancy between [`DataProcessInstance` entity](https://datahubproject.io/docs/generated/metamodel/entities/dataprocessinstance/) that does not support `"status"` aspect, while, when created through Python-based ingestion source API layer, such aspect is automatically added by [`source_helpers.auto_status_aspect(...)` function](https://github.com/datahub-project/datahub/blob/master/metadata-ingestion/src/datahub/utilities/source_helpers.py#L33):
```python
def auto_status_aspect(stream: Iterable[MetadataWorkUnit]) -> Iterable[MetadataWorkUnit]:
    """
    For all entities that don't have a status aspect, add one with removed set to false.
    """
    ...
```

This leads to such `500` error on the triggered REST `POST` call to `datahub-gms`:
```
2023-04-04 10:08:21,068 [qtp2106620844-121] INFO  c.l.m.r.entity.AspectResource:145 - INGEST PROPOSAL proposal: {aspectName=status, systemMetadata={lastObserved=1680602901026, runId=postgres-2023_04_04-09_58_20}, entityUrn=urn:li:dataProcessInstance:f8be5e45f445824568745dbd12710c17, entityType=dataProcessInstance, aspect={contentType=application/json, value=ByteString(length=18,bytes=7b227265...6c73657d)}, changeType=UPSERT}
2023-04-04 10:08:21,069 [qtp2106620844-121] INFO  c.l.m.filter.RestliLoggingFilter:55 - POST /aspects?action=ingestProposal - ingestProposal - 500 - 1ms
2023-04-04 10:08:21,069 [qtp2106620844-121] ERROR c.l.m.filter.RestliLoggingFilter:38 - Rest.li error: 
com.linkedin.restli.server.RestLiServiceException: java.lang.RuntimeException: Unknown aspect status for entity dataProcessInstance
    at com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:42)
    at com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:50)
    at com.linkedin.metadata.resources.entity.AspectResource.ingestProposal(AspectResource.java:158)
...
Caused by: java.lang.RuntimeException: Unknown aspect status for entity dataProcessInstance
    at com.linkedin.metadata.entity.EntityService.validateAspect(EntityService.java:904)
    at com.linkedin.metadata.entity.EntityService.ingestProposal(EntityService.java:840)
```
with this exception thrown by this [`EntityService::validateAspect(...)` method](https://github.com/datahub-project/datahub/blob/master/metadata-io/src/main/java/com/linkedin/metadata/entity/EntityService.java#L908) unsurprisingly failing to validate this `DataProcessInstance` entity against its schema.

**Expected behavior:**
I don't know if this wrong behaviour is due to the fact that `DataProcessInstance` entity should support `status` aspect or if it's the Python-based ingestion source API layer that should not automatically add one while calling `datahub-gms` for this particular entity (other ones might be impacted), but for sure `DataProcessInstance` handling through this Python-based ingestion framework should work fine without such `500` error on `datahub-gms` due to such discrepancy in metadata-model assumptions.

**Additional context:**
Occurs on DataHub v0.10.0.

**Comment by sanromeo** [comment]
Please re-open an issue because error occurs on dbt-core ingestion
