### ISSUE TITLE
BigQuery ingestion failing for datasets with views in v0.10.1

### ISSUE THREAD

**Issue by gblazq** [datahub-project/datahub#7760]
**Describe the bug**
BigQuery ingestion is failing for datasets containing views since v0.10.1.

For each dataset having at least one view, the ingestion fails with the following error:

`Unable to get tables for dataset <dataset> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'`

Datasets without views do not result in any error.

Here's a more complete log from an actual run, with project and dataset replaced by placeholders:

```
~~~~ Execution Summary - RUN_INGEST ~~~~
Execution finished with errors.
{'exec_id': 'e554c0a9-d710-4423-8e3c-da71c30d3193',
 'infos': ['2023-04-05 05:00:00.095366 INFO: Starting execution for task with name=RUN_INGEST',
           "2023-04-05 05:06:22.922330 INFO: Failed to execute 'datahub ingest'",
           '2023-04-05 05:06:22.923063 INFO: Caught exception EXECUTING task_id=e554c0a9-d710-4423-8e3c-da71c30d3193, name=RUN_INGEST, '
           'stacktrace=Traceback (most recent call last):\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/default_executor.py", line 122, in execute_task\n'
           '    task_event_loop.run_until_complete(task_future)\n'
           '  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete\n'
           '    return future.result()\n'
           '  File "/usr/local/lib/python3.10/site-packages/acryl/executor/execution/sub_process_ingestion_task.py", line 231, in execute\n'
           '    raise TaskError("Failed to execute \'datahub ingest\'")\n'
           "acryl.executor.execution.task.TaskError: Failed to execute 'datahub ingest'\n"],
 'errors': []}

~~~~ Ingestion Report ~~~~
{
  "cli": {
    "cli_version": "0.10.1",
    "cli_entry_location": "/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/__init__.py",
    "py_version": "3.10.10 (main, Mar 14 2023, 02:37:11) [GCC 10.2.1 20210110]",
    "py_exec_path": "/tmp/datahub/ingest/venv-bigquery-0.10.1/bin/python3",
    "os_details": "Linux-5.10.161+-x86_64-with-glibc2.31",
    "peak_memory_usage": "573.55 MB",
    "mem_info": "372.72 MB"
  },
  "source": {
    "type": "bigquery",
    "report": {
      "events_produced": 1425,
      "events_produced_per_sec": 7,
      "entities": {
        "container": [
          "urn:li:container:487f3e526f054d3161f27c146eef016c",
          "urn:li:container:6159d5dffebad31ba50821284839a1ec",
          "urn:li:container:662d1297fae1499ad72a81de2dc70230",
          "urn:li:container:939e704164882abc2ba82eb22edfd72c",
          "urn:li:container:1b724e244229e6da67089c31fade0d3e",
          "urn:li:container:6033b3f99a6246cae6f0579fa60e5401",
          "urn:li:container:4435ecc4771455fd4542855326896851",
          "urn:li:container:94a9748fb580282c04570788b5d4dcf5",
          "urn:li:container:dec5b7c4ba4cf910e18b0fb16f9f06c4",
          "urn:li:container:8e1e11d47d9f09b6004ed5418e247208",
          "... sampled of 32 total elements"
        ],
        "dataset": [...]
      },
      "aspects": {
        "container": {
          "containerProperties": 64,
          "status": 64,
          "dataPlatformInstance": 64,
          "subTypes": 64,
          "container": 62
        },
        "dataset": {
          "status": 260,
          "schemaMetadata": 164,
          "datasetProperties": 154,
          "container": 308,
          "subTypes": 154,
          "upstreamLineage": 67
        }
      },
      "warnings": {
        "usage-extraction": [
          "Skip this run as there was a run later than the current start time: 2023-04-04 00:00:00+00:00"
        ]
      },
      "failures": {
        "metadata-extraction": [
          "<project-id>.<dataset1> - Unable to get tables for dataset <dataset1> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset2> - Unable to get tables for dataset <dataset2> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset3> - Unable to get tables for dataset <dataset3> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset4> - Unable to get tables for dataset <dataset4> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset5> - Unable to get tables for dataset <dataset5> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset6> - Unable to get tables for dataset <dataset6> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset7> - Unable to get tables for dataset <dataset7> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset8> - Unable to get tables for dataset <dataset8> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset9> - Unable to get tables for dataset <dataset9> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n",
          "<project-id>.<dataset10> - Unable to get tables for dataset <dataset10> in project <project-id>, skipping. Does your service account has bigquery.tables.list, bigquery.routines.get, bigquery.routines.list permission, bigquery.tables.getData permission? The error was: 'int' object has no attribute 'timestamp' - Traceback (most recent call last):\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 626, in _process_project\n    yield from self._process_schema(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 782, in _process_schema\n    yield from self._process_view(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 882, in _process_view\n    yield from self.gen_view_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 951, in gen_view_dataset_workunits\n    yield from self.gen_dataset_workunits(\n  File \"/tmp/datahub/ingest/venv-bigquery-0.10.1/lib/python3.10/site-packages/datahub/ingestion/source/bigquery_v2/bigquery.py\", line 1007, in gen_dataset_workunits\n    lastModified=TimeStamp(time=int(table.last_altered.timestamp() * 1000))\nAttributeError: 'int' object has no attribute 'timestamp'\n"
        ]
      }
    ...
  }
}
```

**To Reproduce**
1. Have a BigQuery dataset with a view.
2. Run the ingestion with CLI v0.10.1.

**Expected behavior**
The ingestion should run successfully.

**Additional context**
Downgrading to CLI v0.10.0 solves the issue. Given that v0.10.1 has commit 95f99198, it looks like it introduced some bug regarding `table.last_altered`.

**Comment by mayurinehate** [comment]
This is fixed via https://github.com/datahub-project/datahub/pull/7762 and it available in latest release [0.10.1.1](https://pypi.org/project/acryl-datahub/0.10.1.1/) . Please update your datahub cli version.
