### ISSUE TITLE
datahub-kafka-setup-job with MSK (amazone kafka) error

### ISSUE THREAD

**Issue by tieungao88** [datahub-project/datahub#7766]
**Describe the bug**
I have error when run Datahub with MSK:
**MSK version:**` 2.8.0`
```
WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
--
Thu, Apr 6 2023 6:33:48 am | WARNING: Due to limitations in metric names, topics with a period ('.') or underscore ('_') could collide. To avoid issues it is best to use either, but not both.
Thu, Apr 6 2023 6:33:51 am | 1 done working
Thu, Apr 6 2023 6:33:51 am | 2 done working
Thu, Apr 6 2023 6:33:51 am | Topic Creation Complete.
Error while executing config command with args '--command-config /tmp/connection.properties --bootstrap-server b-2.devdwhdatahubmsk.....c5.kafka.ap-southeast-1.amazonaws.com:9092,b-1.devdwhdatahubmsk.....c5.kafka.ap-southeast-1.amazonaws.com:9092 --entity-type topics --entity-name _schemas --alter --add-config cleanup.policy=compact'
--
Thu, Apr 6 2023 6:34:01 am | java.util.concurrent.ExecutionException: org.apache.kafka.common.errors.UnknownTopicOrPartitionException:
Thu, Apr 6 2023 6:34:01 am | at java.base/java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:395)
Thu, Apr 6 2023 6:34:01 am | at java.base/java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2022)
Thu, Apr 6 2023 6:34:01 am | at org.apache.kafka.common.internals.KafkaFutureImpl.get(KafkaFutureImpl.java:180)
Thu, Apr 6 2023 6:34:01 am | at kafka.admin.ConfigCommand$.getResourceConfig(ConfigCommand.scala:576)
Thu, Apr 6 2023 6:34:01 am | at kafka.admin.ConfigCommand$.alterConfig(ConfigCommand.scala:346)
Thu, Apr 6 2023 6:34:01 am | at kafka.admin.ConfigCommand$.processCommand(ConfigCommand.scala:326)
Thu, Apr 6 2023 6:34:01 am | at kafka.admin.ConfigCommand$.main(ConfigCommand.scala:97)
Thu, Apr 6 2023 6:34:01 am | at kafka.admin.ConfigCommand.main(ConfigCommand.scala)
Thu, Apr 6 2023 6:34:01 am | Caused by: org.apache.kafka.common.errors.UnknownTopicOrPartitionException:
```
Please help me!

Thanks.

**Comment by tieungao88** [comment]
Hi,
I resolved this problem. I must manual create topic _schemas in MSK fisrt.

Thanks.

**Comment by bossenti** [comment]
Hi @gathineou,

maybe this still helps you:
We've created a topic for the schema management by ourselves (default is `_schema` but you can name it according to your convention)
Make sure to pass the name of the topic via the `kafkastore.topic` to the schema registry

**Comment by gathineou** [comment]
Hi 👋🏽 and thanks for the reply here @bossenti! So in our case ti came out that the prerequisites schema-registry was disabled after an automatic upgrade in the latest version (issue was that we were missing a lock on the prerequisites version). Once configured properly the schema-registry run before (through a helmfile) and all schemas and setup was in place.
