### ISSUE TITLE
A short description of the bug

### ISSUE THREAD

**Issue by sinna3710** [datahub-project/datahub#7877]
GMS pod not Running...

2023-04-21 08:37:22,255 [pool-16-thread-1] ERROR c.d.m.ingestion.IngestionScheduler:244 - Failed to retrieve ingestion sources! Skipping updating schedule cache until next refresh. start: 0, count: 30
com.linkedin.r2.RemoteInvocationException: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://localhost:8080/entities
        at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:135)
        at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
        at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponse(ResponseFutureImpl.java:94)
        at com.linkedin.common.client.BaseClient.sendClientRequest(BaseClient.java:54)
        at com.linkedin.entity.client.RestliEntityClient.list(RestliEntityClient.java:374)
        at com.datahub.metadata.ingestion.IngestionScheduler$BatchRefreshSchedulesRunnable.run(IngestionScheduler.java:220)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://localhost:8080/entities
        at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:67)
        at com.linkedin.r2.transport.http.client.rest.ExecutionCallback.lambda$onResponse$0(ExecutionCallback.java:64)
        ... 3 common frames omitted
Caused by: com.linkedin.r2.RetriableRequestException: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
        at com.linkedin.r2.transport.http.client.common.ChannelPoolLifecycle.onError(ChannelPoolLifecycle.java:142)
        at com.linkedin.r2.transport.http.client.common.ChannelPoolLifecycle.lambda$create$0(ChannelPoolLifecycle.java:97)
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:590)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:583)
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:559)
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:492)
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:636)
        at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:629)
        at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:118)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.fulfillConnectPromise(AbstractNioChannel.java:321)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:337)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        ... 1 common frames omitted
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: localhost/127.0.0.1:8080
Caused by: java.net.ConnectException: Connection refused
        at java.base/sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at java.base/sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:777)
        at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:776)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by shixiutao** [comment]
I have encountered the same problem. May I know how it was resolved in the end

**Comment by miguelbirdie** [comment]
I have a similar issue:
```
ERROR c.d.m.ingestion.IngestionScheduler:244 - Failed to retrieve ingestion sources! Skipping updating schedule cache until next refresh. start: 0, count: 30
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms com.linkedin.r2.RemoteInvocationException: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://localhost:8080/entities
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:135)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponse(ResponseFutureImpl.java:94)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.common.client.BaseClient.sendClientRequest(BaseClient.java:55)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.entity.client.RestliEntityClient.list(RestliEntityClient.java:393)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.datahub.metadata.ingestion.IngestionScheduler$BatchRefreshSchedulesRunnable.run(IngestionScheduler.java:220)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.lang.Thread.run(Thread.java:829)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms Caused by: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://localhost:8080/entities
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:67)
datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.r2.transport.http.client.rest.ExecutionCallback.lambda$onResponse$0(ExecutionCallback.java:64)
``` 
@shixiutao @hsheth2 @sinna3710 Any clue about this?

Thanks!

**Comment by shixiutao** [comment]
> I have a similar issue:
> 
> ```
> ERROR c.d.m.ingestion.IngestionScheduler:244 - Failed to retrieve ingestion sources! Skipping updating schedule cache until next refresh. start: 0, count: 30
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms com.linkedin.r2.RemoteInvocationException: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://localhost:8080/entities
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.restli.internal.client.ExceptionUtil.wrapThrowable(ExceptionUtil.java:135)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponseImpl(ResponseFutureImpl.java:130)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.restli.internal.client.ResponseFutureImpl.getResponse(ResponseFutureImpl.java:94)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.common.client.BaseClient.sendClientRequest(BaseClient.java:55)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.entity.client.RestliEntityClient.list(RestliEntityClient.java:393)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.datahub.metadata.ingestion.IngestionScheduler$BatchRefreshSchedulesRunnable.run(IngestionScheduler.java:220)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at java.base/java.lang.Thread.run(Thread.java:829)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms Caused by: com.linkedin.r2.RemoteInvocationException: Failed to get response from server for URI http://localhost:8080/entities
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.r2.transport.http.common.HttpBridge$1.onResponse(HttpBridge.java:67)
> datahub-datahub-gms-5f6cf9db66-6bld2 datahub-gms 	at com.linkedin.r2.transport.http.client.rest.ExecutionCallback.lambda$onResponse$0(ExecutionCallback.java:64)
> ```
> 
> @shixiutao @hsheth2 @sinna3710 Any clue about this?
> 
> Thanks!

I tried using version 0.9.6.1 of GMS and it started normally, but when I switched to versions 0.11.0 and 0.12.0, I reported the above error. We haven't found a solution yet

**Comment by miguelbirdie** [comment]
> I tried using version 0.9.6.1 of GMS and it started normally, but when I switched to versions 0.11.0 and 0.12.0, I reported the above error. We haven't found a solution yet


I'll try to use that version. I was using `0.10.4` and I got the same issue

**Comment by miguelbirdie** [comment]
Thanks @shixiutao You are right. I've downgraded Datahub to `v0.9.6.1` and it's working now!

**Comment by hsheth2** [comment]
@miguelbirdie I believe that error message is unnecessarily scary - it just means that not all components were up and running yet, so it delays a few startup tasks.

If you're having issues running GMS or quickstart, could you attach the full logs here?

**Comment by miguelbirdie** [comment]
@hsheth2 I'm not sure if it's scary but it's a blocker as gms is not working 🙂. Please, find the log attached to this message

[datahub-gms.log](https://github.com/datahub-project/datahub/files/13441627/datahub-gms.log)

**Comment by hsheth2** [comment]
@miguelbirdie it looks like this is only a partial log - can you paste the full, non-truncated logs, as well as logs for the datahub-upgrade container?

**Comment by miguelbirdie** [comment]
I've fixed the issue. The problem was the GMS was not completely upgraded. GMS was stuck because there was a not-finished job. I'm using helm chart to deploy DataHub and I missed one property `global.datahub.version` 
```
global:
   ...
    datahub:
      version: v0.12.0
      ...
```

I triggered a deployment (`helm upgrade`) after the change, and gms worked!
