### ISSUE TITLE
Frontend service couldn't start when set PAC4J_SESSIONSTORE_PROVIDER

### ISSUE THREAD

**Issue by tinolyu** [datahub-project/datahub#7998]
**Describe the bug**
Frontend service couldn't start when set PAC4J_SESSIONSTORE_PROVIDER, error log:
```
Oops, cannot start the server.
com.google.inject.CreationException: Unable to create injector, see the following errors:

1) No implementation for play.cache.SyncCacheApi was bound.
  at auth.AuthModule.configure(AuthModule.java:81) (via modules: com.google.inject.util.Modules$OverrideModule -> auth.AuthModule)

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:554)
        at com.google.inject.internal.InternalInjectorCreator.initializeStatically(InternalInjectorCreator.java:161)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:108)
        at com.google.inject.Guice.createInjector(Guice.java:87)
        at com.google.inject.Guice.createInjector(Guice.java:78)
        at play.api.inject.guice.GuiceBuilder.injector(GuiceInjectorBuilder.scala:200)
        at play.inject.guice.GuiceBuilder.injector(GuiceBuilder.java:211)
        at play.inject.guice.GuiceApplicationBuilder.build(GuiceApplicationBuilder.java:121)
        at play.inject.guice.GuiceApplicationLoader.load(GuiceApplicationLoader.java:32)
        at play.api.ApplicationLoader$JavaApplicationLoaderAdapter$1.load(ApplicationLoader.scala:181)
        at play.core.server.ProdServerStart$.start(ProdServerStart.scala:53)
        at play.core.server.ProdServerStart$.main(ProdServerStart.scala:29)
        at play.core.server.ProdServerStart.main(ProdServerStart.scala)
```

**To Reproduce**
1. Add `PAC4J_SESSIONSTORE_PROVIDER=PlayCacheSessionStore` to `docker-compose.yaml`
2. Run Datahub customized quickstart `datahub docker quickstart --quickstart-compose-file docker-compose.yaml`

**Expected behavior**
Frontend up and running.

**Screenshots**
-

**Desktop (please complete the following information):**
 - OS: macOS
 - Version v0.10.2

**Additional context**
-

**Comment by jakobhanna** [comment]
have the same Issue, now even without `PAC4J_SESSIONSTORE_PROVIDER=PlayCacheSessionStore`. See https://github.com/datahub-project/datahub/issues/7733.

**Comment by tinolyu** [comment]
> have the same Issue, now even without `PAC4J_SESSIONSTORE_PROVIDER=PlayCacheSessionStore`. See #7733.

hmm were you able to figure it out? I'm thinking of downgrading to v0.10.0😞

**Comment by jakobhanna** [comment]
we had to downgrade

**Comment by tinolyu** [comment]
> we had to downgrade

Hey I was able to fix this issue.
https://github.com/datahub-project/datahub/issues/7221#issuecomment-1531398686
