### ISSUE TITLE
datahub cli error:"ERROR    {datahub.entrypoints:199} - Command failed: Expecting value: line 1 column 1 (char 0)"

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#8486]
**Describe the bug**
A lot of time spent to solve ssl certivicate error but got another one with cli. I am trying to test with test command like "datahub exists --urn "urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)"" but reciving this:

`datahub exists --urn "urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)"
[2023-07-22 19:21:29,789] ERROR    {datahub.entrypoints:199} - Command failed: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/requests/models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
  File "/usr/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/entrypoints.py", line 186, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/upgrade/upgrade.py", line 398, in async_wrapper
    loop.run_until_complete(run_func_check_upgrade())
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/upgrade/upgrade.py", line 385, in run_func_check_upgrade
    ret = await the_one_future
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/upgrade/upgrade.py", line 379, in run_inner_func
    None, functools.partial(func, *args, **kwargs)
  File "/usr/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/telemetry/telemetry.py", line 448, in wrapper
    raise e
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/telemetry/telemetry.py", line 397, in wrapper
    res = func(*args, **kwargs)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/cli/exists_cli.py", line 39, in urn
    click.echo(json.dumps(get_default_graph().exists(urn)))
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/ingestion/graph/client.py", line 961, in get_default_graph
    return DataHubGraph(DatahubClientConfig(server=url, token=token))
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/ingestion/graph/client.py", line 124, in __init__
    self.test_connection()
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/datahub/emitter/rest_emitter.py", line 150, in test_connection
    config: dict = response.json()
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.7/site-packages/requests/models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
`

**To Reproduce**

**Expected behavior**

the command: datahub exists --urn "urn:li:dataset:(urn:li:dataPlatform:hive,SampleHiveDataset,PROD)"
should return true or false.

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by YuriyGavrilov** [comment]
This issue is solved by reconfiguring cli:
`datahub init
Enter your DataHub host [http://localhost:8080]: https://myhost/api/gms
Enter your DataHub access token (Supports env vars via `{VAR_NAME}` syntax) []: mykey
`
so i was a bit disapointed about fact that I need to supplement this "/api/gms" to the host input line.
