### ISSUE TITLE
BigQuery Column Lineage can not use

### ISSUE THREAD

**Issue by JJJzheng** [datahub-project/datahub#8550]
**Describe the bug**
Can not work with `extract_column_lineage` field

**To Reproduce**
Steps to reproduce the behavior: use under yaml to reproduce

```yaml
source:
    type: bigquery
    config:
        env: TEST
        rate_limit: true
        requests_per_min: 60
        include_table_lineage: true
        include_usage_statistics: true
        include_tables: true
        include_views: true
        extract_column_lineage: true
        lineage_use_sql_parser: true
        incremental_lineage: false
        max_query_duration: 1800
        profiling:
            enabled: true
            profile_table_level_only: false
        stateful_ingestion:
            enabled: true
        credential:
            xxxx
        dataset_pattern:
            allow:
                - hods_utc
                - ods_utc
```

With error log
```code
[2023-08-01 09:08:54,093] DEBUG    {datahub.telemetry.telemetry:219} - Sending init Telemetry
[2023-08-01 09:08:54,380] DEBUG    {datahub.telemetry.telemetry:248} - Sending telemetry for function-call
[2023-08-01 09:08:54,534] INFO     {datahub.cli.ingest_cli:173} - DataHub CLI version: 0.10.4
[2023-08-01 09:08:54,645] DEBUG    {datahub.ingestion.sink.datahub_rest:116} - Setting env variables to override config
[2023-08-01 09:08:54,645] DEBUG    {datahub.ingestion.sink.datahub_rest:118} - Setting gms config
[2023-08-01 09:08:54,645] DEBUG    {datahub.ingestion.run.pipeline:203} - Sink type datahub-rest (<class 'datahub.ingestion.sink.datahub_rest.DatahubRestSink'>) configured
[2023-08-01 09:08:54,645] INFO     {datahub.ingestion.run.pipeline:204} - Sink configured successfully. DataHubRestEmitter: configured to talk to http://datahub-gms.as-in.com with token: eyJh**********SOTI
[2023-08-01 09:08:54,674] DEBUG    {datahub.ingestion.sink.datahub_rest:116} - Setting env variables to override config
[2023-08-01 09:08:54,674] DEBUG    {datahub.ingestion.sink.datahub_rest:118} - Setting gms config
[2023-08-01 09:08:54,674] DEBUG    {datahub.ingestion.reporting.datahub_ingestion_run_summary_provider:125} - Ingestion source urn = urn:li:dataHubIngestionSource:cli-05a5746e49c4efc8a3d2044d1a297d76
[2023-08-01 09:08:54,675] DEBUG    {datahub.emitter.rest_emitter:252} - Attempting to emit to DataHub GMS; using curl equivalent to:
curl -X POST -H 'User-Agent: python-requests/2.30.0' -H 'Accept-Encoding: gzip, deflate' -H 'Accept: */*' -H 'Connection: keep-alive' -H 'X-RestLi-Protocol-Version: 2.0.0' -H 'Content-Type: application/json' -H 'Authorization: <redacted>' --data '{"proposal": {"entityType": "dataHubIngestionSource", "entityUrn": "urn:li:dataHubIngestionSource:cli-05a5746e49c4efc8a3d2044d1a297d76", "changeType": "UPSERT", "aspectName": "dataHubIngestionSourceInfo", "aspect": {"value": "{\"name\": \"[CLI] bigquery [urn:li:dataHubIngestionSource:72dc6fb3-7573-4991-91b9-068969132b08]\", \"type\": \"bigquery\", \"platform\": \"urn:li:dataPlatform:unknown\", \"config\": {\"recipe\": \"{\\\"source\\\": {\\\"type\\\": \\\"bigquery\\\", \\\"config\\\": {\\\"rate_limit\\\": true, \\\"requests_per_min\\\": 60, \\\"include_table_lineage\\\": true, \\\"include_usage_statistics\\\": true, \\\"include_tables\\\": true, \\\"include_views\\\": true, \\\"max_query_duration\\\": 1800, \\\"extract_column_lineage\\\": true, \\\"incremental_lineage\\\": false, \\\"profiling\\\": {\\\"enabled\\\": true, \\\"profile_table_level_only\\\": false}, \\\"stateful_ingestion\\\": {\\\"enabled\\\": true}, \\\"credential\\\": {\\\"project_id\\\": \\\"automizely-data-warehouse\\\", \\\"private_key\\\": \\\"********\\\", \\\"private_key_id\\\": \\\"********\\\", \\\"client_email\\\": \\\"tssd-1014@automizely-data-warehouse.iam.gserviceaccount.com\\\", \\\"client_id\\\": \\\"118436690652925668654\\\"}, \\\"dataset_pattern\\\": {\\\"allow\\\": [\\\"dw_utc_00\\\", \\\"dwb_utc_00\\\", \\\"dwd_utc_00\\\", \\\"dws_utc_00\\\", \\\"fdm_utc_00\\\", \\\"hdb_utc_00\\\", \\\"hds_utc_00\\\", \\\"app_utc_00\\\"]}}}, \\\"pipeline_name\\\": \\\"urn:li:dataHubIngestionSource:72dc6fb3-7573-4991-91b9-068969132b08\\\"}\", \"version\": \"0.10.2.2\", \"executorId\": \"__datahub_cli_\"}}", "contentType": "application/json"}}}' 'http://datahub-gms.as-in.com/aspects?action=ingestProposal'
[2023-08-01 09:08:54,697] DEBUG    {datahub.ingestion.run.pipeline:279} - Reporter type:datahub,<class 'datahub.ingestion.reporting.datahub_ingestion_run_summary_provider.DatahubIngestionRunSummaryProvider'> configured.
[2023-08-01 09:08:59,924] WARNING  {datahub.ingestion.source.bigquery_v2.bigquery_config:260} - Please update `dataset_pattern` to match against fully qualified schema name `<project_id>.<dataset_name>` and set config `match_fully_qualified_names : True`.Current default `match_fully_qualified_names: False` is only to maintain backward compatibility. The config option `match_fully_qualified_names` will be deprecated in future and the default behavior will assume `match_fully_qualified_names: True`.
[2023-08-01 09:08:59,924] DEBUG    {datahub.telemetry.telemetry:248} - Sending telemetry for function-call
[2023-08-01 09:09:00,083] DEBUG    {datahub.entrypoints:192} - Error: Failed to configure the source (bigquery): 1 validation error for BigQueryV2Config
extract_column_lineage
  extra fields not permitted (type=value_error.extra)
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/run/pipeline.py", line 119, in _add_init_error_context
    yield
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/run/pipeline.py", line 218, in __init__
    self.config.source.dict().get("config", {}), self.ctx
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/source/bigquery_v2/bigquery.py", line 274, in create
    config = BigQueryV2Config.parse_obj(config_dict)
  File "pydantic/main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/source/bigquery_v2/bigquery_config.py", line 201, in __init__
    super().__init__(**data)
  File "pydantic/main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for BigQueryV2Config
extract_column_lineage
  extra fields not permitted (type=value_error.extra)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/datahub/entrypoints.py", line 182, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/datahub/telemetry/telemetry.py", line 379, in wrapper
    raise e
  File "/usr/local/lib/python3.7/dist-packages/datahub/telemetry/telemetry.py", line 334, in wrapper
    res = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/datahub/utilities/memory_leak_detector.py", line 95, in wrapper
    return func(ctx, *args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/datahub/cli/ingest_cli.py", line 194, in run
    raw_pipeline_config,
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/run/pipeline.py", line 334, in create
    no_default_report=no_default_report,
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/run/pipeline.py", line 221, in __init__
    logger.info("Source configured successfully.")
  File "/usr/lib/python3.7/contextlib.py", line 130, in __exit__
    self.gen.throw(type, value, traceback)
  File "/usr/local/lib/python3.7/dist-packages/datahub/ingestion/run/pipeline.py", line 121, in _add_init_error_context
    raise PipelineInitError(f"Failed to {step}: {e}") from e
datahub.ingestion.run.pipeline.PipelineInitError: Failed to configure the source (bigquery): 1 validation error for BigQueryV2Config
extract_column_lineage
  extra fields not permitted (type=value_error.extra)
Failed to configure the source (bigquery): 1 validation error for BigQueryV2Config
extract_column_lineage
  extra fields not permitted (type=value_error.extra)
[2023-08-01 09:09:00,095] DEBUG    {datahub.entrypoints:198} - DataHub CLI version: 0.10.2.2 at /usr/local/lib/python3.7/dist-packages/datahub/__init__.py
[2023-08-01 09:09:00,095] DEBUG    {datahub.entrypoints:201} - Python version: 3.7.5 (default, Dec  9 2021, 17:04:37) 
[GCC 8.4.0] at /usr/bin/python3.7 on Linux-5.4.0-1096-gcp-x86_64-with-Ubuntu-18.04-bionic
[2023-08-01 09:09:00,095] DEBUG    {datahub.entrypoints:205} - GMS config {'models': {}, 'patchCapable': True, 'versions': {'linkedin/datahub': {'version': 'v0.10.4', 'commit': 'b77b4e2ba9a946709acf18af9fe03d6fdfc1ed62'}}, 'managedIngestion': {'defaultCliVersion': '@cliMajorVersion@', 'enabled': True}, 'statefulIngestionCapable': True, 'supportsImpactAnalysis': True, 'timeZone': 'GMT', 'telemetry': {'enabledCli': True, 'enabledIngestion': False}, 'datasetUrnNameCasing': False, 'retention': 'true', 'datahub': {'serverType': 'quickstart'}, 'noCode': 'true'}

```

Plz help me to check whats the problem

**Desktop (please complete the following information):**
 - OS: Linux
 - Version v0.10.4

**Comment by JJJzheng** [comment]
If I remove the extract_column_lineage parameter, the program works fine.

**Comment by DSchmidtDev** [comment]
It's not a bug.  `extract_column_lineage` is a feature added in `0.10.5`

**Comment by JJJzheng** [comment]
Thanks @DSchmidtDev  I will try in `0.10.5`

**Comment by JJJzheng** [comment]
have been resolved. Close issue.
