### ISSUE TITLE
NPE in creating/updating datasets configured with custom aspects

### ISSUE THREAD

**Issue by luciofarinosi** [datahub-project/datahub#8904]
**Describe the bug**
The REST API applying CRUD operation in dataset entity is not working anymore when a custom aspect is linked to the model of a dataset due to NullPointerException.
2023-09-25 16:14:15,094 [qtp2006034581-20] ERROR i.d.openapi.util.OpenApiEntitiesUtil:101 - Error reflecting entity: dataset aspect: customDataQualityRules

**To Reproduce**
Steps to reproduce the behaviour:
1. Create a custom aspect and associate it to the dataset entity as described in https://github.com/datahub-project/datahub/tree/master/metadata-models-custom.
2. Create a new dataset or update an existing one through REST API (POST {{datahub_url}}/openapi/v2/entity/dataset). The body can either contain or not the custom entity. The error happens in all the cases.
3. REST API returns a HTTP 500 highlighting a NPE as per log shown below.
4. If I remove the custom library jar / registry file from the plugin directory and restart GMS the same API call completes successfully.

**Expected behavior**
REST API should complete successfully and the custom aspect, if present, should be saved/updated.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser N/A
 - Version N/A

**Additional context**
- Containers are runnning in Docker Desktop

- Affected version: 0.11.0 and HEAD

- I've just replicated what is on the documentation in terms of custom entity https://github.com/datahub-project/datahub/tree/master/metadata-models-custom

- Stack trace of the issue in GMS 
2023-09-25 16:14:15,094 [qtp2006034581-20] ERROR i.d.openapi.util.OpenApiEntitiesUtil:101 - Error reflecting entity: dataset aspect: customDataQualityRules
...
2023-09-25 17:14:15 Caused by: 
2023-09-25 17:14:15 java.lang.NullPointerException
2023-09-25 17:14:15     at io.datahubproject.openapi.util.OpenApiEntitiesUtil.lambda$convertEntityToUpsert$0(OpenApiEntitiesUtil.java:85)
2023-09-25 17:14:15     at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
2023-09-25 17:14:15     at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1655)

- custom model is correctly loaded at startup.
2023-09-25 19:06:58 2023-09-25 18:06:58,079 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:110 - Loading custom config entity file: /etc/datahub/plugins/models/mycompany-dq-model/0.0.1/entity-registry.yaml, dir: /etc/datahub/plugins/models/mycompany-dq-model/0.0.1
2023-09-25 19:06:58 2023-09-25 18:06:58,079 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:110 - Loading custom config entity file: /etc/datahub/plugins/models/mycompany-dq-model/0.0.1/entity-registry.yaml, dir: /etc/datahub/plugins/models/mycompany-dq-model/0.0.1
2023-09-25 19:07:04 2023-09-25 18:07:04,047 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:147 - Discovered entity dataset with aspects customDataQualityRules
2023-09-25 19:07:04 2023-09-25 18:07:04,047 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:147 - Discovered entity dataset with aspects customDataQualityRules
2023-09-25 19:07:04 2023-09-25 18:07:04,048 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:158 - Adding aspect customDataQualityRules with spec com.linkedin.metadata.models.AspectSpec@9357a343
2023-09-25 19:07:04 2023-09-25 18:07:04,048 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:158 - Adding aspect customDataQualityRules with spec com.linkedin.metadata.models.AspectSpec@9357a343
2023-09-25 19:07:04 2023-09-25 18:07:04,049 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:147 - Discovered entity container with aspects customDataQualityRules
2023-09-25 19:07:04 2023-09-25 18:07:04,049 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:147 - Discovered entity container with aspects customDataQualityRules
2023-09-25 19:07:04 2023-09-25 18:07:04,049 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:158 - Adding aspect customDataQualityRules with spec com.linkedin.metadata.models.AspectSpec@9357a343
2023-09-25 19:07:04 2023-09-25 18:07:04,049 [pool-2-thread-1] INFO  c.l.m.m.registry.PatchEntityRegistry:158 - Adding aspect customDataQualityRules with spec com.linkedin.metadata.models.AspectSpec@9357a343
2023-09-25 19:07:04 2023-09-25 18:07:04,050 [pool-2-thread-1] INFO  c.l.m.m.r.PluginEntityRegistryLoader:149 - Loaded registry PatchEntityRegistry[identifier=mycompany-dq-model;[entityName=container;aspects=[customDataQualityRules]][entityName=dataset;aspects=[customDataQualityRules]] successfully
2023-09-25 19:07:04 2023-09-25 18:07:04,652 [main] INFO  c.l.g.f.s.ElasticSearchServiceFactory:56 - Search configuration: SearchConfiguration(maxTermBucketSize=20, exactMatch=ExactMatchConfiguration(exclusive=false, withPrefix=true, prefixFactor=1.6, exactFactor=10.0, caseSensitivityFactor=0.7, enableStructured=true), partial=PartialConfiguration(urnFactor=0.5, factor=0.4), custom=CustomConfiguration(enabled=false, file=search_config.yml), graph=GraphQueryConfiguration(timeoutSeconds=50, batchSize=1000, maxResult=10000), wordGram=WordGramConfiguration(twoGramFactor=1.2, threeGramFactor=1.5, fourGramFactor=1.8))
2023-09-25 19:07:04 2023-09-25 18:07:04,667 [main] INFO  c.l.m.c.search.CustomConfiguration:40 - Custom search configuration disabled.

**Comment by david-leifker** [comment]
Looking at this scenario, the openapi classes would not contain the required methods for custom aspects. The openapi endpoint should protect against this NPE and allow normal operations on the non-custom aspects. restli is the primary API for use with custom aspects.

**Comment by david-leifker** [comment]
This should be fixed [here](https://github.com/datahub-project/datahub/pull/8927) the sense that the NPE should be avoided.
