### ISSUE TITLE
spark lineage : Not a valid protocol version

### ISSUE THREAD

**Issue by RUIzg** [datahub-project/datahub#8987]
**Describe the bug**

when I  execute  spark-sql command , I got a occur  , there is a detail info 
-- ----------------

 $SPARK_HOME/bin/spark-sql \
 --conf "spark.jars.packages=io.acryl:datahub-spark-lineage:0.10.4-3" \
 --conf "spark.extraListeners=datahub.spark.DatahubSparkListener" \
 --conf "spark.datahub.rest.server=http://dev-hadoop06:8080"

 
---------------- error info 
 DEBUG InternalIODispatch: http-outgoing-0 [ACTIVE] Exception
datahub.spark2.shaded.http.ProtocolException: Not a valid protocol version: [0x1e][0x1f][0x20][0x21][0x22][0x23][0x24][0x25][0x26][0x27][0x28ÿÿÿ[0x2d][0x2e][0x2f][0x30][0x31][0x32][0x33][0x34][0x35][0x36] [0x38][0x39][0x3a][0x3b][0x3c][0x3d][0x3e][0x3f][0x40][0x41][0x42][0x43][0x44][0x45][0x46][0x47]I[0x49][0x4a][0x4b][0x4c][0x4d][0x4eÿÿÿ[0x53][0x54][0x55][0x56]Unexpected HTTP/1.x request: POST /aspects?action=ingestProposal
        at datahub.spark2.shaded.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:209)
        at datahub.spark2.shaded.http.impl.nio.DefaultNHttpClientConnection.consumeInput(DefaultNHttpClientConnection.java:245)
        at datahub.spark2.shaded.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:87)
        at datahub.spark2.shaded.http.impl.nio.client.InternalIODispatch.onInputReady(InternalIODispatch.java:40)
        at datahub.spark2.shaded.http.impl.nio.reactor.AbstractIODispatch.inputReady(AbstractIODispatch.java:114)
        at datahub.spark2.shaded.http.impl.nio.reactor.BaseIOReactor.readable(BaseIOReactor.java:162)
        at datahub.spark2.shaded.http.impl.nio.reactor.AbstractIOReactor.processEvent(AbstractIOReactor.java:337)
        at datahub.spark2.shaded.http.impl.nio.reactor.AbstractIOReactor.processEvents(AbstractIOReactor.java:315)
        at datahub.spark2.shaded.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:276)
        at datahub.spark2.shaded.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
        at datahub.spark2.shaded.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:591)
        at java.lang.Thread.run(Thread.java:748)
Caused by: datahub.spark2.shaded.http.ParseException: Not a valid protocol version:ÿÿÿÿÿÿUnexpected HTTP/1.x request: POST /aspects?action=ingestProposal
        at datahub.spark2.shaded.http.message.BasicLineParser.parseProtocolVersion(BasicLineParser.java:148)
        at datahub.spark2.shaded.http.message.BasicLineParser.parseStatusLine(BasicLineParser.java:366)
        at datahub.spark2.shaded.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:112)
        at datahub.spark2.shaded.http.impl.nio.codecs.DefaultHttpResponseParser.createMessage(DefaultHttpResponseParser.java:50)
        at datahub.spark2.shaded.http.impl.nio.codecs.AbstractMessageParser.parseHeadLine(AbstractMessageParser.java:156)
        at datahub.spark2.shaded.http.impl.nio.codecs.AbstractMessageParser.parse(AbstractMessageParser.java:207)
        ... 11 more
23/10/11 16:19:12 DEBUG ManagedNHttpClientConnectionImpl: http-outgoing-0 10.100.7.171:49470<->10.100.7.171:8080[ACTIVE][r:r]: Shutdown
23/10/11 16:19:12 DEBUG ManagedNHttpClientConnectionImpl: http-outgoing-0 0.0.0.0:49470<->10.100.7.171:8080[CLOSED][]: Shutdown

 

**Expected behavior**
It should no exception , and datahub get a normal spark lineage . 
 

**Desktop (please complete the following information):**
 - OS: CentOS Linux release 7.9.2009 (Core)
  - Version spark 2.2.2 
  - datahub:  0.10.4
  - jar package file:  datahub-spark-lineage-0.10.4-3.jar

**Comment by treff7es** [comment]
@RUIzg, please, can you check if the datahub is URL where you point to http://dev-hadoop06:8080/ ?
It seems the spark plugin connects and tries to do a POST but it returns a non-valid http response.
The above error says it was unable to parse the Status-Line from the response:
`Not a valid protocol version:ÿÿÿÿÿÿ`

From the HTTP RFC:
```
6.1 Status-Line
The first line of a Response message is the Status-Line, consisting of the protocol version followed by a numeric status code and its associated textual phrase, with each element separated by SP characters. No CR or LF is allowed except in the final CRLF sequence.
```
