### ISSUE TITLE
[cli] ERROR {datahub.entrypoints:201} - Command failed: ('Unable to emit metadata to DataHub GMS: INTERNAL SERVER ERROR', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': 'INTERNAL SERVER ERROR', 'status': 500})

### ISSUE THREAD

**Issue by YuriyGavrilov** [datahub-project/datahub#9057]
**Describe the bug**

Hi,

There is an fresh error with cli. Iam trying to delete everythig by tag and receive this error:

```
datahub delete --urn 'urn:li:product.BI'
[2023-10-20 11:47:27,716] INFO     {datahub.cli.delete_cli:341} - Using DataHubGraph: configured to talk to https://catalog.edp.s7.aero/api/gms with token: eyJh**********3-XU
[2023-10-20 11:47:56,003] ERROR    {datahub.entrypoints:201} - Command failed: ('Unable to emit metadata to DataHub GMS: INTERNAL SERVER ERROR', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': 'INTERNAL SERVER ERROR', 'status': 500})
```

Full stack trace:

```
Traceback (most recent call last):
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/emitter/rest_emitter.py", line 282, in _emit_generic
    response.raise_for_status()
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://catalog.edp.s7.aero/api/gms/aspects?action=ingestProposal

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/entrypoints.py", line 188, in main
    sys.exit(datahub(standalone_mode=False, **kwargs))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/upgrade/upgrade.py", line 398, in async_wrapper
    loop.run_until_complete(run_func_check_upgrade())
  File "/usr/local/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/upgrade/upgrade.py", line 385, in run_func_check_upgrade
    ret = await the_one_future
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/upgrade/upgrade.py", line 378, in run_inner_func
    return await loop.run_in_executor(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/telemetry/telemetry.py", line 448, in wrapper
    raise e
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/telemetry/telemetry.py", line 397, in wrapper
    res = func(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/cli/delete_cli.py", line 415, in by_filter
    one_result = _delete_one_urn(
                 ^^^^^^^^^^^^^^^^
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/cli/delete_cli.py", line 561, in _delete_one_urn
    graph.soft_delete_entity(urn=urn, run_id=run_id)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/ingestion/graph/client.py", line 872, in soft_delete_entity
    self.emit_mcp(
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/emitter/rest_emitter.py", line 261, in emit_mcp
    self._emit_generic(url, payload)
  File "/home/yu.gavrilov@group.s7/venv/lib/python3.11/site-packages/datahub/emitter/rest_emitter.py", line 290, in _emit_generic
    raise OperationalError(
datahub.configuration.common.OperationalError: ('Unable to emit metadata to DataHub GMS: INTERNAL SERVER ERROR', {'exceptionClass': 'com.linkedin.restli.server.RestLiServiceException', 'message': 'INTERNAL SERVER ERROR', 'status': 500})
```

datahub cli veriosion:

```
(venv) yu.gavrilov@S7-13-038829:~$ datahub version
DataHub CLI version: 0.11.0.5
Python version: 3.11.6 (main, Oct 20 2023, 11:27:05) [GCC 8.3.0]
```

**To Reproduce**
1. Go to 'terminal and run `datahub delete --urn 'urn:li:product.BI'`'
2. Scroll down to 'the end'

**Expected behavior**
There should be no error at all. Datahub-cli should ask aggreement for deleting. 

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - Browser [e.g. chromium]
 - Version [e.g. cli - 0.11.0.5]

**Additional context**
it seems it works with other kind of delete or get requests.

**Comment by TonyOuyangGit** [comment]
Do you see any error logs from GMS? You'll probably find more information from GMS log. And also do you have `METADATA_SERVICE_AUTH_ENABLED` or `REST_API_AUTHORIZATION_ENABLED` set to `true` in GMS env?

**Comment by YuriyGavrilov** [comment]
@TonyOuyangGit Thx for ideas, will try to find some.
