### ISSUE TITLE
Admin user could not roll back ingestion when REST_API_AUTHORIZATION_ENABLED is set to true

### ISSUE THREAD

**Issue by TonyOuyangGit** [datahub-project/datahub#9088]
**Describe the bug**
In the latest release v0.11.0 with env variable REST_API_AUTHORIZATION_ENABLED is set to true. The ingestion roll back seems failing and the GMS log shows that the user is not authorized to delete entities, even though we are logged in as datahub root user who didn’t touch anything on permissions

**To Reproduce**
1. Locally deploy a latest Datahub release with env variable REST_API_AUTHORIZATION_ENABLED set to true
2. log in as datahub user
3. Run a sample ingestion which will produce some metadata
4. Roll back ingestion, you'll see the failure

**Expected behavior**
User with admin role or root user should be able to roll back ingestion

**Additional context**
GMS log is saying user is unauthorized to delete entities.
```
Caused by: com.linkedin.restli.server.RestLiServiceException: User is unauthorized to delete entities.
	at com.linkedin.metadata.resources.entity.BatchIngestionRunResource.lambda$rollback$7(BatchIngestionRunResource.java:133)
	at com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:30)
	at com.linkedin.metadata.restli.RestliUtil.toTask(RestliUtil.java:50)
	at com.linkedin.metadata.resources.entity.BatchIngestionRunResource.rollback(BatchIngestionRunResource.java:112)
```

**Comment by TonyOuyangGit** [comment]
This is resolved by the #9092
