### ISSUE TITLE
Sinking Superset to Datahub; 'NoneType' object has no attribute and SSLError caused

### ISSUE THREAD

**Issue by realthered** [datahub-project/datahub#9139]
**Describe the bug**
When sinking superset information to datahub (0.10.5 and 0.11.0 both), below error is occurred and some data cannot emitted to datahub.
The data not emitted is changed every time I tried.
And after sink, dataset is not shown in Chart Lineage although it is already in datahub.

Below is error while Sinking

```
ERROR:root:'NoneType' object has no attribute 'startswith'
Traceback (most recent call last):
  File "/mnt/c/Users/<username>/Desktop/scripts/datahub_test.py", line 46, in <module>
    datahub_ingest_yaml(datahub_superset_ingest_yaml)
  File "/mnt/c/Users/<username>/Desktop/scripts/datahub_test.py", line 15, in datahub_ingest_yaml
    pipeline.run()
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/run/pipeline.py", line 367, in run
    for wu in itertools.islice(
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 119, in auto_stale_entity_removal
    for wu in stream:
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 143, in auto_workunit_reporter
    for wu in stream:
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 208, in auto_browse_path_v2
    for urn, batch in _batch_workunits_by_urn(stream):
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 346, in _batch_workunits_by_urn
    for wu in stream:
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 156, in auto_materialize_referenced_tags
    for wu in stream:
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/api/source_helpers.py", line 70, in auto_status_aspect
    for wu in stream:
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/superset.py", line 403, in get_workunits_internal
    yield from self.emit_chart_mces()
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/superset.py", line 396, in emit_chart_mces
    chart_snapshot = self.construct_chart_from_chart_data(chart_data)
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/superset.py", line 326, in construct_chart_from_chart_data
    datasource_urn = self.get_datasource_urn_from_id(datasource_id)
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/superset.py", line 219, in get_datasource_urn_from_id
    platform = self.get_platform_from_database_id(database_id)
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/superset.py", line 203, in get_platform_from_database_id
    return sql_common.get_platform_from_sqlalchemy_uri(sqlalchemy_uri)
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/sql/sql_common.py", line 147, in get_platform_from_sqlalchemy_uri
    if tester(sqlalchemy_uri):
  File "/home/red/.local/lib/python3.10/site-packages/datahub/ingestion/source/sql/sql_common.py", line 109, in <lambda>
    return platform, lambda x: x.startswith(
AttributeError: 'NoneType' object has no attribute 'startswith'
```

```

DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,28)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,14)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,11)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,2)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,9)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,23)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,21)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,8)
DEBUG:datahub.ingestion.run.pipeline: sink wrote workunit urn:li:dashboard:(superset,25)
ERROR:datahub.ingestion.run.pipeline: failed to write record with workunit urn:li:dashboard:(superset,16) with ('Unable to emit metadata to DataHub GMS', {'message': "HTTPSConnectionPool(host='<hostname>', port=443): Max retries exceeded with url: /api/gms/entities?action=ingest (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))", 'id': 'urn:li:dashboard:(superset,16)'}) and info {'message': "HTTPSConnectionPool(host='<hostname>', port=443): Max retries exceeded with url: /api/gms/entities?action=ingest (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))", 'id': 'urn:li:dashboard:(superset,16)'}
ERROR:datahub.ingestion.run.pipeline: failed to write record with workunit urn:li:dashboard:(superset,15) with ('Unable to emit metadata to DataHub GMS', {'message': "HTTPSConnectionPool(host='<hostname>', port=443): Max retries exceeded with url: /api/gms/entities?action=ingest (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))", 'id': 'urn:li:dashboard:(superset,15)'}) and info {'message': "HTTPSConnectionPool(host='<hostname>', port=443): Max retries exceeded with url: /api/gms/entities?action=ingest (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))", 'id': 'urn:li:dashboard:(superset,15)'}
ERROR:datahub.ingestion.run.pipeline: failed to write record with workunit urn:li:dashboard:(superset,12) with ('Unable to emit metadata to DataHub GMS', {'message': "HTTPSConnectionPool(host='<hostname>', port=443): Max retries exceeded with url: /api/gms/entities?action=ingest (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))", 'id': 'urn:li:dashboard:(superset,12)'}) and info {'message': "HTTPSConnectionPool(host='<hostname>', port=443): Max retries exceeded with url: /api/gms/entities?action=ingest (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:997)')))", 'id': 'urn:li:dashboard:(superset,12)'}
```

Below is ingest yaml code
```

def datahub_ingest_yaml(ingest_yaml: str):
    pipeline: Pipeline = Pipeline.create(yaml.full_load(ingest_yaml))

    pipeline.run()
    pipeline.pretty_print_summary()
    pipeline.raise_from_status()

datahub_superset_ingest_yaml = """
source:
  type: superset
  config:
    connect_uri: <superset hostname>
    display_uri: <superset hostname>
    provider: "db"
    username: "admin"
    password: <password>
    stateful_ingestion:
        enabled: True
sink:
  type: datahub-rest
  config:
    server: <hostname>/api/gms
    token: <token>
    retry_max_times: 10
pipeline_name: superset_pipeline
"""

try:
    datahub_ingest_yaml(datahub_superset_ingest_yaml)
except Exception as e:
    logging.exception(e)
    pass
```

**To Reproduce**
1. Install Datahub 0.10.5 or 0.11.0 and Superset 3.0.0rc2
2. Execute above python code

**Expected behavior**
- Working fine without exceeding max retries
- Datasource is shown in chart lineage when succeeded sometimes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Chrome 118.0.5993, Windows 10, python 3.10.6

**Additional context**
Superset and Datahub both are running in Kubernetes by Helm chart.

**Comment by hsheth2** [comment]
@realthered Looks like two different issues

Re superset - what db is superset connected to?

Re SSL errors - it doesn't really make sense that some metadata was written to GMS successfully and others failed - do you have a proxy / load balancer / something else sitting in the middle?

**Comment by realthered** [comment]
> @realthered Looks like two different issues
> 
> Re superset - what db is superset connected to?
> 
> Re SSL errors - it doesn't really make sense that some metadata was written to GMS successfully and others failed - do you have a proxy / load balancer / something else sitting in the middle?

Superset: is connected to snowflake

SSL errors: We're using kubernetes so to access datahub pod from local, there's a network load balancer which is L4 LB so I don't think LB or other kubernetes things affects this.
In case of `dbt` or `snowflake` source, datahub sinking works well.

Is there any idea that this issue is related to any superset source structure changed?

**Comment by realthered** [comment]
+ update
after update to 0.12.0 image, SSL issue is not occured. But still superset snowflake data source is not shown in chart lineage.

**Comment by realthered** [comment]
I found the root cause.
Superset Database name was different to its original snowflake database name.
After I found this, it worked well.
Sorry for interruption 😭
