### ISSUE TITLE
Profiling errors on Snowflake ingestion using limit

### ISSUE THREAD

**Issue by rospe** [datahub-project/datahub#9461]
**Describe the bug**
I encounter errors when ingesting Snowflake (v0.11) with enabled profiling and limit. When I do not use a limit, the errors do not appear anymore.
Database and schema usage rights for the role used are granted.

see https://datahubspace.slack.com/archives/CUMUWQU66/p1701765566885429 for the initial report

The stacktrace:
```
2023-12-11T08:17:47.006637201Z ⏳ Pipeline running with at least 1 warnings so far; produced 18018 events in 2 minutes and 20.06 seconds.
2023-12-11T08:17:55.003501242Z [2023-12-11 08:17:55,003] INFO     {datahub.ingestion.source.ge_data_profiler:909} - Will profile 857 table(s) with 40 worker(s) - this may take a while
2023-12-11T08:17:55.014098699Z [2023-12-11 08:17:55,012] INFO     {great_expectations.util:1938} - Could not find local context root directory
2023-12-11T08:17:55.016267858Z [2023-12-11 08:17:55,016] INFO     {great_expectations.data_context.data_context.abstract_data_context:5420} - EphemeralDataContext has not implemented `_load_zep_config()` returning empty `GxConfig`
2023-12-11T08:17:55.017484066Z [2023-12-11 08:17:55,017] INFO     {great_expectations.experimental.datasources.config:53} - Loading 'datasources' ->
2023-12-11T08:17:55.017715820Z {}
2023-12-11T08:17:55.019475270Z [2023-12-11 08:17:55,019] INFO     {great_expectations.experimental.datasources.config:79} - Loaded 'datasources' ->
2023-12-11T08:17:55.019506141Z {}
2023-12-11T08:17:55.032821269Z [2023-12-11 08:17:55,032] INFO     {great_expectations.data_context.data_context.abstract_data_context:4495} - Usage statistics is disabled; skipping initialization.
2023-12-11T08:17:55.046327051Z [2023-12-11 08:17:55,045] INFO     {datahub.ingestion.source.ge_data_profiler:1063} - Profiling prod01_db_cds_edw.core_consumption.XXXXXXXX
2023-12-11T08:17:55.052498669Z [2023-12-11 08:17:55,052] WARNING  {py.warnings:109} - /usr/local/lib/python3.10/site-packages/great_expectations/data_context/data_context/abstract_data_context.py:2705: DeprecationWarning: create_expectation_suite is deprecated as of v0.15.48 and will be removed in v0.18. Please use add_expectation_suite or add_or_update_expectation_suite instead.
2023-12-11T08:17:55.052548411Z   warnings.warn(
2023-12-11T08:17:55.052554680Z 
2023-12-11T08:17:55.058564545Z [2023-12-11 08:17:55,058] INFO     {great_expectations.datasource.sqlalchemy_datasource:430} - Generating query from table batch_kwargs based on limit and offset
2023-12-11T08:17:55.062685117Z [2023-12-11 08:17:55,062] INFO     {great_expectations.dataset.sqlalchemy_dataset:1682} - Creating temporary table ge_temp_21f52991
2023-12-11T08:17:56.389700236Z [2023-12-11 08:17:56,202] ERROR    {datahub.ingestion.source.ge_data_profiler:1094} - Encountered exception while profiling prod01_db_cds_edw.core_consumption.XXXXXXXX
2023-12-11T08:17:56.389747887Z Traceback (most recent call last):
2023-12-11T08:17:56.389754898Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-12-11T08:17:56.389759838Z     self.dialect.do_execute(
2023-12-11T08:17:56.389764597Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-12-11T08:17:56.389769088Z     cursor.execute(statement, parameters)
2023-12-11T08:17:56.389773428Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 827, in execute
2023-12-11T08:17:56.389777997Z     Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
2023-12-11T08:17:56.389782388Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 275, in errorhandler_wrapper
2023-12-11T08:17:56.389787088Z     handed_over = Error.hand_to_other_handler(
2023-12-11T08:17:56.389791529Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 330, in hand_to_other_handler
2023-12-11T08:17:56.389807109Z     cursor.errorhandler(connection, cursor, error_class, error_value)
2023-12-11T08:17:56.389811809Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 209, in default_errorhandler
2023-12-11T08:17:56.389816218Z     raise error_class(
2023-12-11T08:17:56.389820729Z snowflake.connector.errors.ProgrammingError: 090106 (22000): Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
2023-12-11T08:17:56.389824779Z 
2023-12-11T08:17:56.389829120Z The above exception was the direct cause of the following exception:
2023-12-11T08:17:56.389833099Z 
2023-12-11T08:17:56.389839309Z Traceback (most recent call last):
2023-12-11T08:17:56.389844120Z   File "/datahub-ingestion/.local/lib/python3.10/site-packages/datahub/ingestion/source/ge_data_profiler.py", line 1065, in _generate_single_profile
2023-12-11T08:17:56.389848239Z     batch = self._get_ge_dataset(
2023-12-11T08:17:56.389852369Z   File "/datahub-ingestion/.local/lib/python3.10/site-packages/datahub/ingestion/source/ge_data_profiler.py", line 1128, in _get_ge_dataset
2023-12-11T08:17:56.389856580Z     batch = ge_context.data_context.get_batch(
2023-12-11T08:17:56.389860920Z   File "/usr/local/lib/python3.10/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1076, in get_batch
2023-12-11T08:17:56.389865299Z     return self._get_batch_v2(
2023-12-11T08:17:56.389869570Z   File "/usr/local/lib/python3.10/site-packages/great_expectations/data_context/data_context/abstract_data_context.py", line 1204, in _get_batch_v2
2023-12-11T08:17:56.389873960Z     return validator.get_dataset()
2023-12-11T08:17:56.389878370Z   File "/usr/local/lib/python3.10/site-packages/great_expectations/validator/validator.py", line 2122, in get_dataset
2023-12-11T08:17:56.389882740Z     return self.expectation_engine(
2023-12-11T08:17:56.389898361Z   File "/usr/local/lib/python3.10/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 887, in __init__
2023-12-11T08:17:56.389902890Z     self.create_temporary_table(
2023-12-11T08:17:56.389907171Z   File "/usr/local/lib/python3.10/site-packages/great_expectations/dataset/sqlalchemy_dataset.py", line 1739, in create_temporary_table
2023-12-11T08:17:56.389916671Z     self.engine.execute(stmt)
2023-12-11T08:17:56.389920961Z   File "/datahub-ingestion/.local/lib/python3.10/site-packages/datahub/utilities/sqlalchemy_query_combiner.py", line 273, in _sa_execute_fake
2023-12-11T08:17:56.389927081Z     return _sa_execute_underlying_method(conn, query, *args, **kwargs)
2023-12-11T08:17:56.389931402Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1365, in execute
2023-12-11T08:17:56.389935651Z     return self._exec_driver_sql(
2023-12-11T08:17:56.389939851Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1669, in _exec_driver_sql
2023-12-11T08:17:56.389944192Z     ret = self._execute_context(
2023-12-11T08:17:56.389948412Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1943, in _execute_context
2023-12-11T08:17:56.389957852Z     self._handle_dbapi_exception(
2023-12-11T08:17:56.389963672Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2124, in _handle_dbapi_exception
2023-12-11T08:17:56.389967913Z     util.raise_(
2023-12-11T08:17:56.389972442Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
2023-12-11T08:17:56.389976662Z     raise exception
2023-12-11T08:17:56.389980863Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1900, in _execute_context
2023-12-11T08:17:56.389985033Z     self.dialect.do_execute(
2023-12-11T08:17:56.389989172Z   File "/usr/local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
2023-12-11T08:17:56.389993403Z     cursor.execute(statement, parameters)
2023-12-11T08:17:56.389997563Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/cursor.py", line 827, in execute
2023-12-11T08:17:56.390001773Z     Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
2023-12-11T08:17:56.390012723Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 275, in errorhandler_wrapper
2023-12-11T08:17:56.390016993Z     handed_over = Error.hand_to_other_handler(
2023-12-11T08:17:56.390021144Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 330, in hand_to_other_handler
2023-12-11T08:17:56.390030374Z     cursor.errorhandler(connection, cursor, error_class, error_value)
2023-12-11T08:17:56.390034644Z   File "/usr/local/lib/python3.10/site-packages/snowflake/connector/errors.py", line 209, in default_errorhandler
2023-12-11T08:17:56.390038844Z     raise error_class(
2023-12-11T08:17:56.390043464Z sqlalchemy.exc.ProgrammingError: (snowflake.connector.errors.ProgrammingError) 090106 (22000): Cannot perform CREATE TEMPTABLE. This session does not have a current schema. Call 'USE SCHEMA', or use a qualified name.
2023-12-11T08:17:56.390047774Z [SQL: CREATE OR REPLACE TEMPORARY TABLE ge_temp_21f52991 AS SELECT * 
2023-12-11T08:17:56.390052224Z FROM "CORE_CONSUMPTION"."XXXXXXXX"
2023-12-11T08:17:56.390056505Z  LIMIT 100]
2023-12-11T08:17:56.390060764Z (Background on this error at: https://sqlalche.me/e/14/f405)`
```
**To Reproduce**

My recipe snippet:
```yaml
profiling:
    enabled: true
    turn_off_expensive_profiling_metrics: true
    limit: 100
    max_number_of_fields_to_profile: 50
    sample_size: 1000
    use_sampling: false
    #profile_day_of_week: 5 #only on saturdays
```

**Expected behavior**
I want to use limits while profiling without any errors.

**Additional context**
Some of our tables are really huge, so not using the limit is not really an option

**Comment by hsheth2** [comment]
@rospe we're looking into this one.

cc @mayurinehate - this looks similar to the issue we were seeing with `tablesample`.
